import type {Metadata} from "next";import {LegalPage,LegalSection} from "../../components/legal-page";
export const metadata:Metadata={title:"Datenschutz für Dienstleister",description:"Datenschutzhinweise für Dienstleister auf B2B Matching."};
export default function Page(){return <LegalPage eyebrow="DATENSCHUTZ FÜR ANBIETER" title="Datenschutz für Dienstleister" intro="So verarbeiten wir Anbieter-, Leistungs-, Matching- und Vertragsdaten auf B2B Matching.">
<LegalSection title="1. Verantwortlicher"><p>Media Online Innovations Group, Inhaber Martin Kelm, Im Weidenblech 25, 51371 Leverkusen, E-Mail: <a href="mailto:mail@media-online-innovations.group">mail@media-online-innovations.group</a>, Telefon: 0214 / 330 140 60.</p></LegalSection>
<LegalSection title="2. Daten und Zwecke"><p>Wir verarbeiten Konto- und Ansprechpartnerdaten, Unternehmens-, Branchen- und Leistungsdaten, Inhalte der Leistungsseite, Referenzen, Prüfstatus, Matchings, Freigaben, Ablehnungen, Chat- und Termindaten, Aktivitätsprotokolle sowie Abonnement-, Rechnungs- und Zahlungsstatus. Dies dient Profilprüfung, Darstellung, Matching, Kommunikation, Vertragsverwaltung, Abrechnung, Sicherheit und Support.</p></LegalSection>
<LegalSection title="3. Rechtsgrundlagen"><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO, lit. c für gesetzliche Pflichten, lit. f für Sicherheit, Betrugsprävention, Qualität und Plattformverbesserung sowie lit. a bei einwilligungsbedürftigen Verarbeitungen.</p></LegalSection>
<LegalSection title="4. Profilprüfung, Matching und KI"><p>Leistungstexte können automatisiert auf Verständlichkeit, Vollständigkeit, Plausibilität und Regelkonformität geprüft werden. Kriterien werden zu einer Match-Empfehlung zusammengeführt. Automatische Ergebnisse führen nicht allein zu einem Vertrag oder einer ähnlich erheblichen Entscheidung. Suchende entscheiden über die Freigabe; bei Zurückweisung oder Sperre steht ein menschlicher Prüfweg zur Verfügung.</p></LegalSection>
<LegalSection title="5. Sichtbarkeit und Empfänger"><p>Freigegebene Leistungsseiten sind bestimmungsgemäß sichtbar. Weitere Empfänger sind berechtigte Beschäftigte und vertraglich gebundene Anbieter für Hosting, Datenbank, E-Mail, Support, Sicherheit, Zahlung und technische KI-Verarbeitung. Bei Übermittlungen außerhalb des EWR werden gesetzliche Garantien eingesetzt.</p></LegalSection>
<LegalSection title="6. Speicherdauer"><p>Profil- und Vertragsdaten werden während der Nutzung gespeichert. Handels- und steuerrechtliche Unterlagen bewahren wir entsprechend den gesetzlichen Fristen auf. Übrige Daten löschen oder anonymisieren wir nach Zweckfortfall, soweit keine Aufbewahrung, Rechtsverteidigung, Sicherheit oder offenen Ansprüche entgegenstehen.</p></LegalSection>
<LegalSection title="7. Rechte"><p>Sie haben nach den gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und Widerruf. Beschwerden können an eine Datenschutzaufsichtsbehörde gerichtet werden, insbesondere an die Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen.</p></LegalSection>
<LegalSection title="8. Pflichtangaben"><p>Gekennzeichnete Konto-, Unternehmens-, Leistungs- und Abrechnungsangaben sind für die jeweilige Funktion erforderlich. Ohne sie sind Freigabe, Matching oder kostenpflichtige Nutzung gegebenenfalls nicht möglich.</p></LegalSection>
</LegalPage>}
