import {PortalPanel,PortalShell,PortalStats,Status} from "../../components/portal-shell";
export default function DienstleisterPortal(){return <PortalShell role="dienstleister" title="Ihre nächsten Chancen warten." intro="Positionieren Sie Ihre Leistungen, bearbeiten Sie freigegebene Matches und entwickeln Sie neue Geschäftskontakte." action={<button className="portalPrimary">Leistungsseite bearbeiten</button>}>
<PortalStats items={[["87 %","Profilqualität","3 Angaben fehlen"],["9","Neue Chancen","4 über 90 %"],["6","Profilbesucher","+24 % im Monat"],["2","Aktive Gespräche","1 Termin geplant"]]}/>
<div className="portalGrid wideLeft"><div>
<PortalPanel id="matches" eyebrow="FÜR SIE FREIGEGEBEN" title="Neue Geschäftschancen" action={<button className="portalLink">Alle Chancen →</button>}><div className="opportunities">{[["94","Externe IT-Sicherheitsprüfung","Maschinenbau · NRW","Projektstart September","Neu"],["89","Cloud-Infrastruktur modernisieren","Logistik · Deutschland","Start innerhalb 8 Wochen","Prüfen"],["84","Datenschutz-Audit und Maßnahmenplan","Gesundheitswesen · Remote","Laufzeit 3–4 Monate","Vorgemerkt"]].map(([s,t,m,d,status],i)=><article key={t}><b>{s}<small>%</small></b><div><Status tone={i===0?"teal":i===1?"blue":"amber"}>{status}</Status><h3>{t}</h3><p>{m} · {d}</p><small>Ihre Spezialisierung und Referenzen stimmen mit den wichtigsten Kriterien überein.</small></div><button className="portalPrimary">Chance ansehen</button></article>)}</div></PortalPanel>
<PortalPanel id="profil" eyebrow="IHRE POSITIONIERUNG" title="Leistungsprofil und Landingpage"><div className="profileQuality"><div><span><b>87%</b> vollständig</span><div><i style={{width:"87%"}}/></div><p>Ergänzen Sie Verfügbarkeit, zwei Referenzen und Ihr bevorzugtes Auftragsvolumen.</p></div><ul><li><b>✓</b> Unternehmensdaten und Ansprechpartner</li><li><b>✓</b> Leistungen und Spezialisierungen</li><li><b>✓</b> Branchen und Regionen</li><li><b>○</b> Referenzen und Nachweise</li></ul></div><div className="profileActions"><button className="portalSecondary">Vorschau öffnen</button><button className="portalPrimary">Profil vervollständigen</button></div></PortalPanel>
<PortalPanel id="nachrichten" eyebrow="KONTAKTE" title="Aktive Gespräche"><div className="conversationRows">{[["BW","Bergwerk GmbH","Vielen Dank. Passt Ihnen Freitag um 10 Uhr?","vor 12 Min.","2"],["HM","Hanseatic Maschinenbau","Wir haben noch eine Frage zu Ihrer Vorgehensweise.","gestern",""]].map(([a,n,msg,time,count])=><article key={n}><b>{a}</b><div><h3>{n}</h3><p>{msg}</p></div><span>{time}{count&&<i>{count}</i>}</span></article>)}</div></PortalPanel>
</div><aside>
<PortalPanel title="Ihr nächster Schritt" className="portalNext"><ol><li><b>Referenz ergänzen</b><span>Profilqualität erhöhen</span></li><li><b>Neue Chance prüfen</b><span>94 % Übereinstimmung</span></li><li><b>Termin bestätigen</b><span>Freitag, 10:00 Uhr</span></li></ol></PortalPanel>
<PortalPanel id="besucher" title="Profilbesucher"><div className="compactPeople">{[["BW","Anonymes Unternehmen","Profil vor 2 Std. angesehen"],["HM","Hanseatic Maschinenbau","Kontakt bereits freigegeben"],["—","Anonymes Unternehmen","Profil gestern angesehen"]].map(([a,n,r])=><p key={n+r}><b>{a}</b><span><strong>{n}</strong><small>{r}</small></span></p>)}</div></PortalPanel>
<PortalPanel id="abonnement" title="Abonnement"><Status tone="teal">Professional aktiv</Status><h3 className="planTitle">Volle Sichtbarkeit und alle Matches</h3><p className="panelNote">Nächste Vorauszahlung am 01.10.2026</p><button className="portalSecondary full">Abonnement verwalten</button></PortalPanel>
</aside></div></PortalShell>}
