import {PortalEmpty,PortalPanel,PortalShell,PortalStats,Status} from "../../components/portal-shell";
export default function DienstleisterPortal(){return <PortalShell role="dienstleister" title="Richten Sie Ihr Dienstleisterprofil ein." intro="Erst nach vollständiger Prüfung kann Ihr Profil in passende Matchings aufgenommen werden." action={<button className="portalPrimary">Leistungsseite bearbeiten</button>}>
<div className="portalSetup"><div><span>PROFILFREIGABE</span><h2>Vier Schritte bis zu Ihren ersten Geschäftschancen.</h2></div><b>20 %</b><div className="setupBar"><i style={{width:"20%"}}/></div><ol><li className="done">E-Mail-Adresse bestätigt</li><li>Unternehmensdaten ergänzen</li><li>Leistungen und Referenzen beschreiben</li><li>Profil zur Prüfung einreichen</li></ol></div>
<PortalStats items={[["20 %","Profilqualität","Einrichtung begonnen"],["0","Geschäftschancen","Nach Profilfreigabe"],["0","Profilbesucher","Noch keine Aufrufe"],["0","Aktive Gespräche","Keine Gespräche"]]}/>
<div className="portalGrid wideLeft"><div>
<PortalPanel id="profil" eyebrow="IHRE POSITIONIERUNG" title="Leistungsprofil und Landingpage"><div className="profileQuality"><div><span><b>20%</b> vollständig</span><div><i style={{width:"20%"}}/></div><p>Ergänzen Sie Unternehmensdaten, Leistungen, Spezialisierungen, Regionen, Referenzen und Verfügbarkeit.</p></div><ul><li><b>✓</b> E-Mail-Adresse bestätigt</li><li><b>○</b> Unternehmensdaten</li><li><b>○</b> Leistungen und Spezialisierungen</li><li><b>○</b> Referenzen und Nachweise</li></ul></div><div className="profileActions"><button className="portalSecondary">Leere Vorschau öffnen</button><button className="portalPrimary">Profil vervollständigen</button></div></PortalPanel>
<PortalPanel id="matches" eyebrow="GESCHÄFTSCHANCEN" title="Freigegebene Bedarfe"><PortalEmpty icon="◎" title="Noch keine Geschäftschancen" text="Nach Profilfreigabe und einem passenden Match sehen Sie hier ausschließlich Bedarfe, die vom suchenden Unternehmen für Sie freigegeben wurden." action="Aufbau einer Geschäftschance ansehen"/></PortalPanel>
<PortalPanel id="nachrichten" eyebrow="KOMMUNIKATION" title="Nachrichten und Termine"><PortalEmpty icon="✉" title="Noch keine Gespräche" text="Nach einer beiderseitigen Freigabe können Sie hier sicher schreiben und Online- oder Vor-Ort-Termine vereinbaren."/></PortalPanel>
</div><aside>
<PortalPanel title="Nächste Schritte" className="portalNext"><ol><li><b>Unternehmensdaten ergänzen</b><span>Grundlage der Profilprüfung</span></li><li><b>Leistungen beschreiben</b><span>Grundlage des Matchings</span></li><li><b>Referenzen hinterlegen</b><span>Vertrauen und Profilqualität</span></li></ol></PortalPanel>
<PortalPanel id="besucher" title="Profilbesucher"><PortalEmpty icon="◫" title="Keine Profilaufrufe" text="Freigegebene Besucher und anonyme Aufrufzahlen erscheinen nach Veröffentlichung."/></PortalPanel>
<PortalPanel id="abonnement" title="Abonnement"><Status tone="gray">Noch kein Tarif</Status><h3 className="planTitle">Dienstleisterfunktionen aktivieren</h3><p className="panelNote">Tarif, Preis, dreimonatige Mindestlaufzeit und Vorauszahlung werden vor Abschluss vollständig angezeigt.</p><button className="portalSecondary full">Tarife ansehen</button></PortalPanel>
</aside></div></PortalShell>}
