import type {Metadata} from "next";import {LegalPage,LegalSection} from "../../components/legal-page";
export const metadata:Metadata={title:"Datenschutz für Unternehmen",description:"Datenschutzhinweise für suchende Unternehmen auf B2B Matching."};
export default function Page(){return <LegalPage eyebrow="DATENSCHUTZ FÜR SUCHENDE" title="Datenschutz für Unternehmen" intro="So verarbeiten wir Daten von Unternehmen und Ansprechpartnern, die geschäftliche Dienstleistungen suchen.">
<LegalSection title="1. Verantwortlicher"><p>Media Online Innovations Group, Inhaber Martin Kelm, Im Weidenblech 25, 51371 Leverkusen, E-Mail: <a href="mailto:service@b2b-matching.de">service@b2b-matching.de</a>, Telefon: 0214 / 330 140 60.</p></LegalSection>
<LegalSection title="2. Daten und Zwecke"><p>Wir verarbeiten Konto-, Kontakt-, Unternehmens- und Profildaten, Bedarfsbeschreibungen, Freigaben, Ablehnungen, Matching- und Statusdaten, Chat- und Termininformationen sowie Sicherheits-, Protokoll- und Supportdaten. Dies dient Registrierung, Profilprüfung, sicherem Portalbetrieb, anonymisierter Bedarfssuche, Matching, kontrollierter Kontaktfreigabe, Kommunikation und Dokumentation. Vor Ihrer Freigabe sehen Dienstleister grundsätzlich nur den Bedarf, nicht Ihre Unternehmensidentität.</p></LegalSection>
<LegalSection title="3. Rechtsgrundlagen"><p>Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO für Vertrag und vorvertragliche Maßnahmen, lit. c für gesetzliche Pflichten, lit. f für Sicherheit, Missbrauchsprävention, Qualität und Weiterentwicklung sowie lit. a, soweit wir eine Einwilligung einholen.</p></LegalSection>
<LegalSection title="4. Matching und KI-Unterstützung"><p>Bedarfe und Profildaten können automatisiert semantisch analysiert und verglichen werden. Das Ergebnis ist eine prozentuale Empfehlung, keine alleinige Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung. Sie prüfen das Profil und entscheiden selbst über Sichtbarkeit, Ablehnung und Kontakt. Technische KI-Unterauftragnehmer können als vertraglich gebundene Empfänger eingesetzt werden.</p></LegalSection>
<LegalSection title="5. Empfänger und Drittland"><p>Zugriff erhalten berechtigte Beschäftigte und sorgfältig ausgewählte Auftragsverarbeiter, etwa für Hosting, Datenbank, E-Mail, Support, Sicherheit und KI-Verarbeitung. Andere Nutzer erhalten Daten nur entsprechend Ihrer Freigabe. Bei Verarbeitung außerhalb des EWR setzen wir die gesetzlich vorgesehenen Garantien ein, insbesondere Angemessenheitsbeschlüsse oder EU-Standardvertragsklauseln.</p></LegalSection>
<LegalSection title="6. Speicherdauer"><p>Kontodaten speichern wir während der Nutzung und anschließend, soweit Aufbewahrung, Rechtsverteidigung oder Sicherheit dies erfordern. Übrige Daten werden nach Zweckfortfall oder Kontolöschung gelöscht beziehungsweise anonymisiert, sofern keine gesetzlichen Fristen entgegenstehen.</p></LegalSection>
<LegalSection title="7. Rechte"><p>Sie haben nach Maßgabe der DSGVO Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie auf Widerruf erteilter Einwilligungen. Beschwerden können an eine Datenschutzaufsichtsbehörde gerichtet werden, in Nordrhein-Westfalen an die Landesbeauftragte für Datenschutz und Informationsfreiheit NRW.</p></LegalSection>
<LegalSection title="8. Pflichtangaben und Sicherheit"><p>Gekennzeichnete Angaben sind für Konto oder Funktion erforderlich. Wir treffen angemessene technische und organisatorische Schutzmaßnahmen. Stellen Sie keine unnötigen besonderen Kategorien personenbezogener Daten oder fremden Geschäftsgeheimnisse ein.</p></LegalSection>
</LegalPage>}
