import Link from "next/link";
import {NetworkShell} from "../../../components/network-shell";
import {networkBase} from "../../../lib/network-config";

export default function Page(){
 return <NetworkShell title="Guten Morgen, Dirk." intro="Steuern Sie Mitglieder, Treffen und Zusammenarbeit in Ihrem geschlossenen Unternehmernetzwerk." action={<Link className="networkPrimary" href={`${networkBase}/veranstaltungen`}>＋ Veranstaltung anlegen</Link>}>
  <section className="networkHero"><div><span>NETZWERKSTATUS</span><h2>Gemeinsam stark im Oberbergischen Kreis.</h2><p>Alle zentralen Aktivitäten Ihres Netzwerks an einem Ort – geschützt, nachvollziehbar und für Mitglieder einfach erreichbar.</p></div><strong>21<small>aktive Unternehmen</small></strong></section>
  <section className="networkStats">{[["21","Aktive Mitglieder","+ 2 im letzten Monat"],["1","Offener Aufnahmeantrag","Prüfung erforderlich"],["4","Kommende Veranstaltungen","Nächste am Dienstag"],["0","Neue interne Matches","Matching startet mit Profilen"]].map(([value,label,note])=><article key={label}><strong>{value}</strong><span>{label}<small>{note}</small></span></article>)}</section>
  <div className="networkDashboardGrid"><div><section className="networkCard"><header><div><span>NÄCHSTE TERMINE</span><h2>Veranstaltungen und Treffen</h2></div><Link href={`${networkBase}/veranstaltungen`}>Alle ansehen →</Link></header><div className="networkEventRows"><article><time><b>DI</b><strong>21</strong><small>JUL</small></time><div><h3>Unternehmerfrühstück</h3><p>06:45–08:30 Uhr · Hotel zur Post, Wiehl</p><small>14 Zusagen · 3 Plätze frei</small></div><Link href={`${networkBase}/veranstaltungen`}>Verwalten</Link></article><article><time><b>DI</b><strong>28</strong><small>JUL</small></time><div><h3>Unternehmerfrühstück</h3><p>06:45–08:30 Uhr · Hotel zur Post, Wiehl</p><small>8 Zusagen · Anmeldung geöffnet</small></div><Link href={`${networkBase}/veranstaltungen`}>Verwalten</Link></article></div></section><section className="networkCard"><header><div><span>NETZWERKAKTIVITÄT</span><h2>Was gerade passiert</h2></div><Link href={`${networkBase}/auswertungen`}>Auswertung →</Link></header><div className="networkActivity"><p><b>DP</b><span><strong>Neuer Aufnahmeantrag eingegangen</strong><small>Beispielunternehmen GmbH · vor 2 Stunden</small></span></p><p><b>SB</b><span><strong>Unternehmensprofil aktualisiert</strong><small>Kiwis & Brownies · gestern</small></span></p><p><b>UF</b><span><strong>Neue Veranstaltung veröffentlicht</strong><small>Unternehmerfrühstück · vor 3 Tagen</small></span></p></div></section></div><aside><section className="networkCard networkPending"><span>AUFMERKSAMKEIT</span><h2>1 Aufnahmeantrag wartet</h2><p>Prüfen Sie das Unternehmen und entscheiden Sie über die Aufnahme in das Netzwerk.</p><Link className="networkPrimary" href={`${networkBase}/mitglieder`}>Antrag jetzt prüfen</Link></section><section className="networkCard"><header><div><span>PROFILQUALITÄT</span><h2>Netzwerk vollständig machen</h2></div></header><div className="networkQuality"><strong>71%</strong><i><span style={{width:"71%"}}/></i><p>15 von 21 Unternehmen haben ein ausreichend vollständiges Profil.</p><Link href={`${networkBase}/mitglieder`}>Unvollständige Profile anzeigen →</Link></div></section><section className="networkCard"><header><div><span>SCHNELLZUGRIFF</span><h2>Häufige Aufgaben</h2></div></header><nav className="networkQuickLinks"><Link href={`${networkBase}/mitglieder`}>Mitglied einladen <b>→</b></Link><Link href={`${networkBase}/veranstaltungen`}>Treffen planen <b>→</b></Link><Link href={`${networkBase}/themen`}>Ankündigung erstellen <b>→</b></Link><Link href={`${networkBase}/dokumente`}>Dokument bereitstellen <b>→</b></Link></nav></section></aside></div>
 </NetworkShell>;
}
