import {PortalPanel,PortalShell,PortalStats,Status} from "../../components/portal-shell";
export default function AdminPortal(){return <PortalShell role="admin" title="Das Portal im Überblick." intro="Prüfen Sie neue Mitglieder, überwachen Sie Qualität und steuern Sie sämtliche Aktivitäten zentral." action={<button className="portalPrimary">＋ Mitglied anlegen</button>}>
<PortalStats items={[["248","Mitglieder","+17 im Monat"],["14","Profile in Prüfung","6 mit hoher Priorität"],["73","Aktive Bedarfe","21 neue Matches"],["8","Offene Meldungen","2 sicherheitsrelevant"]]}/>
<div className="adminAlert"><span>!</span><div><strong>6 Profile warten länger als 24 Stunden auf Freigabe.</strong><p>Eine zeitnahe Prüfung verbessert Aktivierung und Profilqualität.</p></div><button>Jetzt bearbeiten</button></div>
<div className="portalGrid equal"><div>
<PortalPanel id="freigaben" eyebrow="QUALITÄTSSICHERUNG" title="Offene Profilprüfungen" action={<button className="portalLink">Prüfzentrum →</button>}><div className="reviewRows">{[["NS","Nordstern Systems GmbH","Dienstleister","KI-Prüfung: 91 %","Hoch"],["BM","Bergmann & Partner","Unternehmen","E-Mail bestätigt","Normal"],["KT","Klartext Consulting","Dienstleister","2 Auffälligkeiten","Prüfen"],["WL","Westlicht Logistik","Unternehmen","E-Mail bestätigt","Normal"]].map(([a,n,r,note,status],i)=><article key={n}><b>{a}</b><div><h3>{n}</h3><p>{r} · {note}</p></div><Status tone={i===0?"red":i===2?"amber":"gray"}>{status}</Status><button className="portalSecondary">Prüfen</button></article>)}</div></PortalPanel>
<PortalPanel id="mitglieder" eyebrow="NETZWERK" title="Mitgliederentwicklung"><div className="adminChart"><div className="chartPlot">{[34,42,39,55,61,58,72,76,84,91,96,108].map((h,i)=><b key={i} style={{height:`${h/1.15}%`}}/>)}</div><div className="chartLegend"><span><b/>Unternehmen 142</span><span><b/>Dienstleister 106</span></div></div></PortalPanel>
<PortalPanel id="protokoll" eyebrow="NACHVOLLZIEHBARKEIT" title="Letzte Systemaktivitäten"><div className="activity">{[["10:41","Profil Nordstern Systems durch Admin freigegeben"],["10:28","KI-Prüfung für Klartext Consulting abgeschlossen"],["09:55","Bedarf „Interim HR-Leitung“ deaktiviert"],["09:31","Dienstleisterkonto wegen fehlender Zahlung eingeschränkt"]].map(([time,text])=><p key={time}><span/><small>{time}</small><strong>{text}</strong></p>)}</div></PortalPanel>
</div><aside>
<PortalPanel id="matches" title="Matching-Qualität"><div className="qualityRing"><b>86<small>%</small></b><span>durchschnittliche Passung</span></div><div className="qualityLines"><p><span>Matches über 90 %</span><b>38</b></p><p><span>Freigabequote</span><b>64 %</b></p><p><span>Kontaktquote</span><b>41 %</b></p></div></PortalPanel>
<PortalPanel title="Portalstatus"><div className="systemRows"><p><span><i className="ok"/>Web-Anwendung</span><b>Stabil</b></p><p><span><i className="ok"/>API</span><b>Stabil</b></p><p><span><i className="ok"/>Matching-Jobs</span><b>Aktiv</b></p><p><span><i className="warn"/>E-Mail-Versand</span><b>Einrichten</b></p></div></PortalPanel>
<PortalPanel id="kommunikation" title="Offene Aufgaben"><div className="taskRows"><label><input type="checkbox"/>6 Profile manuell prüfen</label><label><input type="checkbox"/>Zahlungsanbieter konfigurieren</label><label><input type="checkbox"/>Datenschutz-Auftragsverträge prüfen</label><label><input type="checkbox"/>Willkommensmails freigeben</label></div></PortalPanel>
</aside></div></PortalShell>}
