"use client";
import {useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
type Organization={id:string};
type Need={id:string;title:string;description:string;categoryId:string;submittedAt?:string|null;details?:Array<{label:string;value:string}>;organization?:{displayName:string}};
export function AdminReviewWorkspace(){
 const [profileCount,setProfileCount]=useState(0);const [needs,setNeeds]=useState<Need[]>([]);const [selected,setSelected]=useState<Need|null>(null);const [message,setMessage]=useState("Prüfdaten werden geladen …");
 async function load(){const token=getPortalSession();if(!token){setMessage("Bitte melden Sie sich erneut als Plattformadministrator an.");return}try{const [profiles,submittedNeeds]=await Promise.all([portalRequest<Organization[]>("/admin/reviews",{token}),portalRequest<Need[]>("/admin/reviews/needs/queue",{token})]);setProfileCount(profiles.length);setNeeds(submittedNeeds);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Die Prüfliste konnte nicht geladen werden.")}}
 useEffect(()=>{const refresh=()=>void load();refresh();window.addEventListener("b2b-admin-reviews-updated",refresh);return()=>window.removeEventListener("b2b-admin-reviews-updated",refresh)},[]);
 async function decide(decision:"approved"|"changes_requested"|"rejected"){if(!selected)return;const token=getPortalSession();if(!token)return;const reason=window.prompt("Begründung für die dokumentierte Entscheidung:",decision==="approved"?"Bedarf und Pflichtangaben geprüft.":"Bitte Bedarf prüfen und überarbeiten.");if(!reason)return;try{await portalRequest(`/admin/reviews/needs/${selected.id}/decision`,{token,body:{decision,reason,scope:"need"}});setSelected(null);setMessage("Nur der ausgewählte Bedarf wurde entschieden. Das Unternehmensprofil bleibt unverändert.");window.dispatchEvent(new Event("b2b-admin-reviews-updated"));await load()}catch(error){setMessage(error instanceof Error?error.message:"Die Entscheidung konnte nicht gespeichert werden.")}}
 return <div className="adminReviewWorkspace">{message&&<div className="adminAlert"><span>i</span><div><strong>Prüfzentrum</strong><p>{message}</p></div></div>}<div className="portalStats">{[[profileCount,"Profile in Prüfung"],[needs.length,"Bedarfe in Prüfung"],[profileCount+needs.length,"Offene Entscheidungen"],[0,"Offene Rückfragen"]].map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="portalPanel adminNeedReviewPanel"><header><div><span>BEDARFSMITTEILUNGEN</span><h2>Bedarfe zur Freigabe</h2></div></header>{needs.length?<div className="reviewRows">{needs.map(item=><article key={item.id}><b>BE</b><div><h3>{item.title}</h3><p>{item.organization?.displayName||"Unternehmen"} · {item.categoryId}</p></div><button className="needIconAction primary" aria-label="Bedarf vollständig prüfen" title="Bedarf vollständig prüfen" onClick={()=>setSelected(item)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg><span>Bedarf vollständig prüfen</span></button></article>)}</div>:<p className="panelNote">Aktuell liegen keine eingereichten Bedarfe vor.</p>}</section>{selected&&<div className="needModalBackdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="needManageModal adminReviewModal" role="dialog" aria-modal="true"><header><div><span>BEDARF PRÜFEN</span><h2>{selected.title}</h2></div><button onClick={()=>setSelected(null)} aria-label="Schließen">×</button></header><div className="adminReviewDetails"><dl><div><dt>Unternehmen</dt><dd>{selected.organization?.displayName||"—"}</dd></div><div><dt>Kategorie</dt><dd>{selected.categoryId}</dd></div><div><dt>Eingereicht</dt><dd>{selected.submittedAt?new Date(selected.submittedAt).toLocaleString("de-DE"):"—"}</dd></div></dl><section><h3>Beschreibung</h3><p>{selected.description}</p></section>{selected.details?.map((detail,index)=><section key={`${detail.label}-${index}`}><h3>{detail.label}</h3><p>{detail.value}</p></section>)}</div><footer><button className="portalReject" onClick={()=>void decide("rejected")}>Ablehnen</button><button className="portalSecondary" onClick={()=>void decide("changes_requested")}>Änderungen anfordern</button><button className="portalPrimary" onClick={()=>void decide("approved")}>Freigeben</button></footer></section></div>}</div>;
}
