"use client";
import {useCallback,useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
type Organization={id:string};
type Need={id:string;title:string;description:string;categoryId:string;submittedAt?:string|null;organization?:{displayName:string}};
type ServicePage={id:string;title:string;summary:string;description:string;categoryId:string;skills:string[]};

export function AdminReviewWorkspace(){
 const [profiles,setProfiles]=useState<Organization[]>([]),[needs,setNeeds]=useState<Need[]>([]),[services,setServices]=useState<ServicePage[]>([]),[message,setMessage]=useState("Prüfdaten werden geladen …");
 const load=useCallback(async()=>{const token=getPortalSession();if(!token){setMessage("Bitte melden Sie sich erneut als Plattformadministrator an.");return}try{const [p,n,s]=await Promise.all([portalRequest<Organization[]>("/admin/reviews",{token}),portalRequest<Need[]>("/admin/reviews/needs/queue",{token}),portalRequest<ServicePage[]>("/admin/reviews/services/queue",{token})]);setProfiles(p);setNeeds(n);setServices(s);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Die Prüfliste konnte nicht geladen werden.")}},[]);
 useEffect(()=>{void load();const listener=()=>void load();window.addEventListener("b2b-admin-reviews-updated",listener);return()=>window.removeEventListener("b2b-admin-reviews-updated",listener)},[load]);
 const decide=async(kind:"needs"|"services",id:string,decision:"approved"|"changes_requested"|"rejected")=>{const token=getPortalSession();if(!token)return;const reason=window.prompt("Begründung für diese eigenständige Entscheidung:",decision==="approved"?"Inhalt und Pflichtangaben geprüft.":"Bitte Angaben überarbeiten.");if(!reason)return;try{await portalRequest(`/admin/reviews/${kind}/${id}/decision`,{token,body:{decision,reason,...(kind==="needs"?{scope:"need"}:{})}});setMessage(kind==="needs"?"Nur der Bedarf wurde entschieden.":"Nur die Leistungsseite wurde entschieden.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Die Entscheidung konnte nicht gespeichert werden.")}};
 const total=profiles.length+needs.length+services.length;
 return <div className="adminReviewWorkspace">{message&&<div className="adminAlert"><span>i</span><div><strong>Prüfzentrum</strong><p>{message}</p></div></div>}<div className="portalStats">{[[profiles.length,"Profile in Prüfung"],[needs.length,"Bedarfe in Prüfung"],[services.length,"Leistungen in Prüfung"],[total,"Offene Entscheidungen"]].map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div>
 <ReviewSection title="Bedarfe zur Freigabe" eyebrow="BEDARFSMITTEILUNGEN" empty="Keine eingereichten Bedarfe.">{needs.map(item=><ReviewRow key={item.id} title={item.title} text={`${item.organization?.displayName||"Unternehmen"} · ${item.categoryId}`} onDecision={decision=>void decide("needs",item.id,decision)}/>)}</ReviewSection>
 <ReviewSection title="Leistungsseiten zur Freigabe" eyebrow="DIENSTLEISTER" empty="Keine eingereichten Leistungsseiten.">{services.map(item=><ReviewRow key={item.id} title={item.title} text={`${item.categoryId} · ${item.summary}`} onDecision={decision=>void decide("services",item.id,decision)}/>)}</ReviewSection></div>;
}

function ReviewSection({title,eyebrow,empty,children}:{title:string;eyebrow:string;empty:string;children:React.ReactNode}){return <section className="portalPanel adminNeedReviewPanel"><header><div><span>{eyebrow}</span><h2>{title}</h2></div></header>{Array.isArray(children)&&children.length===0?<p className="panelNote">{empty}</p>:children}</section>}
function ReviewRow({title,text,onDecision}:{title:string;text:string;onDecision:(decision:"approved"|"changes_requested"|"rejected")=>void}){return <article className="reviewRows"><b>PR</b><div><h3>{title}</h3><p>{text}</p></div><div className="needIconActions"><button className="needIconAction danger" title="Ablehnen" onClick={()=>onDecision("rejected")}>×</button><button className="needIconAction" title="Änderung anfordern" onClick={()=>onDecision("changes_requested")}>✎</button><button className="needIconAction primary" title="Freigeben" onClick={()=>onDecision("approved")}>✓</button></div></article>}
