"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalEmpty,PortalPanel,PortalStats,Status} from "./portal-shell";

type Need={id:string;title:string;status:string};
type Match={id:string;score:number;components:Record<string,number|null>;explanation:string[];status:string;createdAt:string};
type Service={title:string;summary:string;description:string;skills:string[];targetIndustries:string[];serviceRegions:string[];deliveryModes:string[]};
type Provider={id:string;displayName:string;legalName:string;websiteUrl:string|null;profileData:Record<string,string|boolean>};
type MatchDetail={match:Match;servicePage:Service;provider:Provider;need:Need};
const statusLabel:Record<string,string>={buyer_review:"Neu",deferred:"Zurückgestellt",released_anonymously:"Für Dienstleister freigegeben",provider_interested:"Dienstleister interessiert",mutual_match:"Kontakt freigegeben",rejected_by_buyer:"Abgelehnt",rejected_by_provider:"Vom Dienstleister abgelehnt",closed:"Abgeschlossen"};

export function BuyerMatchWorkspace(){
 const [items,setItems]=useState<MatchDetail[]>([]),[selected,setSelected]=useState<MatchDetail|null>(null),[filter,setFilter]=useState("offen"),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{const token=getPortalSession();if(!token){setMessage("Bitte melden Sie sich erneut an.");setLoading(false);return}try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");const needs=await portalRequest<Need[]>(`/organizations/${organizations[0].id}/needs`,{token});const eligible=needs.filter(need=>["active","paused"].includes(need.status));const groups=await Promise.all(eligible.map(async need=>(await portalRequest<Omit<MatchDetail,"need">[]>(`/needs/${need.id}/match-details`,{token})).map(item=>({...item,need}))));const next=groups.flat().sort((a,b)=>b.match.score-a.match.score);setItems(next);setSelected(current=>current?next.find(item=>item.match.id===current.match.id)||null:null);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Matches konnten nicht geladen werden.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const matchesFilter=(item:MatchDetail,value:string)=>value==="alle"||value==="offen"&&["buyer_review","deferred"].includes(item.match.status)||value==="freigegeben"&&["released_anonymously","provider_interested","mutual_match"].includes(item.match.status)||value==="abgelehnt"&&item.match.status.startsWith("rejected");
 const visible=useMemo(()=>items.filter(item=>matchesFilter(item,filter)),[filter,items]);
 const act=async(path:string)=>{const token=getPortalSession();if(!token)return;try{await portalRequest(path,{token,body:{}});await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Entscheidung konnte nicht gespeichert werden.")}};
 const saveFavorite=async(matchId:string)=>{const token=getPortalSession();if(!token)return;try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");await portalRequest(`/organizations/${organizations[0].id}/favorites`,{token,body:{matchId}});setMessage("Dienstleister wurde in Ihren Favoriten gespeichert.")}catch(error){setMessage(error instanceof Error?error.message:"Favorit konnte nicht gespeichert werden.")}};
 const mutual=items.filter(item=>item.match.status==="mutual_match").length,average=items.length?Math.round(items.reduce((sum,item)=>sum+item.match.score,0)/items.length):0;
 return <>{message&&<p className="portalInlineAlert" role="status">{message}</p>}<div className="workspaceToolbar"><div className="workspaceTabs" role="tablist" aria-label="Matches filtern">{[["offen","Offen"],["freigegeben","Freigegeben"],["abgelehnt","Abgelehnt"],["alle","Alle"]].map(([value,label])=><button key={value} role="tab" aria-selected={filter===value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label} <b>{value==="alle"?items.length:items.filter(item=>matchesFilter(item,value)).length}</b></button>)}</div>{selected&&<button className="portalSecondary" type="button" onClick={()=>void saveFavorite(selected.match.id)}>☆ Dienstleister merken</button>}</div>
 <PortalStats items={[[String(items.filter(item=>["buyer_review","deferred"].includes(item.match.status)).length),"Offene Matches","Ihre Entscheidung"],[items.length?`${average} %`:"—","Ø Passung","Alle Empfehlungen"],[String(items.filter(item=>["released_anonymously","provider_interested","mutual_match"].includes(item.match.status)).length),"Freigaben","Kontrolliert erteilt"],[String(mutual),"Aktive Kontakte","Beidseitig freigegeben"]]}/>
 <div className="portalGrid wideLeft"><PortalPanel eyebrow="EMPFEHLUNGEN" title="Passende Dienstleister">{loading?<p className="panelNote" role="status">Matches werden geladen …</p>:visible.length?<div className="buyerMatchRows">{visible.map(item=><article key={item.match.id} className={selected?.match.id===item.match.id?"selected":""}><button type="button" className="buyerMatchSelect" onClick={()=>setSelected(item)} aria-label={`${item.provider.displayName} mit ${item.match.score} Prozent Passung prüfen`}><span className="buyerMatchScore">{item.match.score}<small>%</small></span><span><Status tone={item.match.status==="mutual_match"?"teal":item.match.status.startsWith("rejected")?"gray":"blue"}>{statusLabel[item.match.status]||item.match.status}</Status><strong>{item.provider.displayName}</strong><small>{item.need.title} · {item.servicePage.title}</small></span><b aria-hidden="true">›</b></button></article>)}</div>:<PortalEmpty icon="◎" title="Keine Matches in dieser Ansicht" text={items.length?"Wählen Sie einen anderen Statusfilter.":"Nach Freigabe eines Bedarfs werden passende geprüfte Dienstleister hier angezeigt."}/>}</PortalPanel>
 <aside>{selected?<PortalPanel eyebrow="MATCHDETAIL" title={selected.provider.displayName}><div className="buyerMatchDetail"><div className="buyerMatchHero"><span>{selected.match.score}<small>%</small></span><div><Status tone="blue">{statusLabel[selected.match.status]||selected.match.status}</Status><h3>{selected.servicePage.title}</h3><p>{selected.servicePage.summary}</p></div></div><section><h4>Warum dieser Match?</h4>{Object.entries(selected.match.components).map(([key,value])=><p className="buyerFactor" key={key}><span>{key==="skills"?"Fachkompetenz":key==="industry"?"Branchenerfahrung":key==="delivery"?"Arbeitsmodell":"Region"}</span><i><b style={{width:`${value||0}%`}}/></i><strong>{value||0} %</strong></p>)}</section><section><h4>Leistungsprofil</h4><p>{selected.servicePage.description}</p><div className="keywordExamples">{selected.servicePage.skills.map(skill=><span key={skill}>{skill}</span>)}</div></section><section><h4>Unternehmen</h4><dl><div><dt>Firmierung</dt><dd>{selected.provider.legalName}</dd></div><div><dt>Website</dt><dd>{selected.provider.websiteUrl||"Nicht angegeben"}</dd></div><div><dt>Regionen</dt><dd>{selected.servicePage.serviceRegions.join(", ")}</dd></div><div><dt>Arbeitsmodell</dt><dd>{selected.servicePage.deliveryModes.join(", ")}</dd></div></dl></section><div className="buyerMatchActions">{["buyer_review","deferred"].includes(selected.match.status)&&<><button className="portalReject" onClick={()=>void act(`/matches/${selected.match.id}/reject`)}>Ablehnen</button><button className="portalPrimary" onClick={()=>void act(`/matches/${selected.match.id}/release`)}>Bedarf anonym freigeben</button></>}{selected.match.status==="provider_interested"&&<button className="portalPrimary" onClick={()=>void act(`/matches/${selected.match.id}/release-identity`)}>Identität und Kontakt freigeben</button>}{selected.match.status==="mutual_match"&&<a className="portalPrimary" href="/portal/unternehmen/nachrichten">Gespräch öffnen</a>}</div></div></PortalPanel>:<PortalPanel title="Match prüfen"><PortalEmpty icon="↗" title="Dienstleister auswählen" text="Öffnen Sie einen Match, um Profil, Leistung, Matchfaktoren und Freigabestatus vollständig zu prüfen."/></PortalPanel>}</aside></div></>;
}
