"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalEmpty,Status} from "./portal-shell";

type Need={id:string;title:string;status:string};
type Match={id:string;score:number;status:string};
type Provider={displayName:string};
type MatchDetail={match:Match;provider:Provider;need:Need};
type Message={id:string;senderUserId:string;body:string;createdAt:string};
type Meeting={id:string;title:string;startsAt:string;durationMinutes:number;mode:"online"|"onsite";location:string|null;status:"proposed"|"confirmed"|"cancelled"};
type Conversation={messages:Message[];meetings:Meeting[]};
type CurrentUser={userId:string};

export function BuyerCommunicationWorkspace(){
 const [matches,setMatches]=useState<MatchDetail[]>([]),[selected,setSelected]=useState<MatchDetail|null>(null),[conversation,setConversation]=useState<Conversation>({messages:[],meetings:[]}),[currentUser,setCurrentUser]=useState<CurrentUser|null>(null),[body,setBody]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[showMeeting,setShowMeeting]=useState(false);
 const loadConversation=useCallback(async(match:MatchDetail,token:string)=>{const result=await portalRequest<Conversation>(`/matches/${match.match.id}/conversation`,{token});setConversation(result)},[]);
 const refresh=useCallback(async()=>{const token=getPortalSession();if(!token){setNotice("Bitte melden Sie sich erneut an.");setLoading(false);return}try{const [user,organizations]=await Promise.all([portalRequest<CurrentUser>("/auth/session/check",{token,body:{}}),portalRequest<Array<{id:string}>>("/organizations/mine",{token})]);setCurrentUser(user);if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");const needs=await portalRequest<Need[]>(`/organizations/${organizations[0].id}/needs`,{token});const groups=await Promise.all(needs.filter(need=>["active","paused"].includes(need.status)).map(async need=>(await portalRequest<Array<{match:Match;provider:Provider}>>(`/needs/${need.id}/match-details`,{token})).filter(item=>item.match.status==="mutual_match").map(item=>({...item,need}))));const next=groups.flat();setMatches(next);const active=selected?next.find(item=>item.match.id===selected.match.id):next[0];setSelected(active||null);if(active)await loadConversation(active,token);else setConversation({messages:[],meetings:[]});setNotice("")}catch(error){setNotice(error instanceof Error?error.message:"Kommunikation konnte nicht geladen werden.")}finally{setLoading(false)}},[loadConversation,selected]);
 useEffect(()=>{void refresh()},[]);// refresh intentionally only on initial mount
 const send=async(event:FormEvent)=>{event.preventDefault();const token=getPortalSession();if(!token||!selected||!body.trim())return;try{await portalRequest(`/matches/${selected.match.id}/messages`,{token,body:{body:body.trim()}});setBody("");await loadConversation(selected,token);setNotice("Nachricht wurde gesendet.")}catch(error){setNotice(error instanceof Error?error.message:"Nachricht konnte nicht gesendet werden.")}};
 const choose=async(item:MatchDetail)=>{const token=getPortalSession();if(!token)return;setSelected(item);setShowMeeting(false);try{await loadConversation(item,token);setNotice("")}catch(error){setNotice(error instanceof Error?error.message:"Gespräch konnte nicht geladen werden.")}};
 const updateMeeting=async(meeting:Meeting,status:"confirmed"|"cancelled")=>{const token=getPortalSession();if(!token||!selected)return;try{await portalRequest(`/meetings/${meeting.id}/status`,{token,body:{status}});await loadConversation(selected,token);setNotice(status==="confirmed"?"Termin wurde bestätigt.":"Termin wurde abgesagt.")}catch(error){setNotice(error instanceof Error?error.message:"Terminstatus konnte nicht geändert werden.")}};
 const upcoming=useMemo(()=>conversation.meetings.filter(meeting=>meeting.status!=="cancelled"),[conversation.meetings]);
 return <>{notice&&<p className="portalInlineAlert" role="status" aria-live="polite">{notice}</p>}<div className="communicationShell realCommunication">
  <section className="inbox" aria-labelledby="conversation-list-title"><header><h2 id="conversation-list-title">Unterhaltungen</h2><span className="conversationCount" aria-label={`${matches.length} Unterhaltungen`}>{matches.length}</span></header>{loading?<p className="communicationLoading" role="status">Unterhaltungen werden geladen …</p>:matches.length?<div className="conversationRows">{matches.map(item=><button key={item.match.id} type="button" className={selected?.match.id===item.match.id?"active":""} aria-pressed={selected?.match.id===item.match.id} onClick={()=>void choose(item)}><span>{item.provider.displayName.slice(0,2).toUpperCase()}</span><span><strong>{item.provider.displayName}</strong><small>{item.need.title}</small></span><Status tone="blue">{item.match.score} %</Status></button>)}</div>:<PortalEmpty icon="✉" title="Keine Unterhaltungen" text="Gespräche entstehen nach einer beiderseitigen Match-Freigabe."/>}</section>
  <section className="chatPane" aria-labelledby="chat-title">{selected?<><header><div><small>Beidseitig freigegebener Kontakt</small><h2 id="chat-title">{selected.provider.displayName}</h2><p>{selected.need.title}</p></div><button className="portalIconCta" type="button" aria-expanded={showMeeting} aria-controls="meeting-form" aria-label="Neuen Termin vorschlagen" title="Neuen Termin vorschlagen" onClick={()=>setShowMeeting(value=>!value)}>◫</button></header><div className="chatMessages" aria-live="polite">{conversation.messages.length?conversation.messages.map(message=><article key={message.id} className={message.senderUserId===currentUser?.userId?"own":""}><p>{message.body}</p><time dateTime={message.createdAt}>{new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(message.createdAt))}</time></article>):<PortalEmpty icon="✉" title="Gespräch beginnen" text="Schreiben Sie eine erste Nachricht oder schlagen Sie direkt einen Termin vor."/ >}</div>{showMeeting&&<MeetingForm matchId={selected.match.id} onSaved={async()=>{const token=getPortalSession();if(token)await loadConversation(selected,token);setShowMeeting(false);setNotice("Terminvorschlag wurde versendet.")}}/>}<form className="chatComposer" onSubmit={send}><label className="srOnly" htmlFor="chat-message">Nachricht an {selected.provider.displayName}</label><textarea id="chat-message" value={body} onChange={event=>setBody(event.target.value)} maxLength={5000} placeholder="Nachricht schreiben …" required/><button className="portalPrimary" type="submit" disabled={!body.trim()}>Senden</button></form></>:<div className="chatEmpty"><span aria-hidden="true">✉</span><h2 id="chat-title">Keine aktive Unterhaltung</h2><p>Nach einer beiderseitigen Freigabe stehen Nachrichten und Termine hier zur Verfügung.</p></div>}</section>
  <aside className="appointmentPane" id="termine" aria-labelledby="appointment-title"><header><h2 id="appointment-title">Termine</h2><span className="conversationCount" aria-label={`${upcoming.length} Termine`}>{upcoming.length}</span></header>{upcoming.length?<div className="meetingRows">{upcoming.map(meeting=><article key={meeting.id}><Status tone={meeting.status==="confirmed"?"teal":"amber"}>{meeting.status==="confirmed"?"Bestätigt":"Vorgeschlagen"}</Status><h3>{meeting.title}</h3><time dateTime={meeting.startsAt}>{new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(meeting.startsAt))}</time><p>{meeting.durationMinutes} Minuten · {meeting.mode==="online"?"Online":meeting.location||"Vor Ort"}</p>{meeting.status==="proposed"&&<div><button className="portalIconCta" title="Termin bestätigen" aria-label={`${meeting.title} bestätigen`} onClick={()=>void updateMeeting(meeting,"confirmed")}>✓</button><button className="portalIconCta danger" title="Termin absagen" aria-label={`${meeting.title} absagen`} onClick={()=>void updateMeeting(meeting,"cancelled")}>×</button></div>}</article>)}</div>:<PortalEmpty icon="◫" title="Keine Termine" text="Vorgeschlagene und bestätigte Termine erscheinen hier."/>}</aside>
 </div></>;
}

function MeetingForm({matchId,onSaved}:{matchId:string;onSaved:()=>Promise<void>}){
 const [error,setError]=useState("");
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const token=getPortalSession();if(!token)return;const data=new FormData(event.currentTarget);try{await portalRequest(`/matches/${matchId}/meetings`,{token,body:{title:data.get("title"),startsAt:data.get("startsAt"),durationMinutes:Number(data.get("durationMinutes")),mode:data.get("mode"),location:data.get("location")}});await onSaved()}catch(reason){setError(reason instanceof Error?reason.message:"Termin konnte nicht vorgeschlagen werden.")}};
 return <form id="meeting-form" className="meetingForm" onSubmit={submit} aria-labelledby="meeting-form-title"><h3 id="meeting-form-title">Termin vorschlagen</h3>{error&&<p role="alert">{error}</p>}<label>Titel<input name="title" minLength={3} maxLength={200} required/></label><label>Beginn<input name="startsAt" type="datetime-local" required/></label><label>Dauer<select name="durationMinutes" defaultValue="30"><option value="30">30 Minuten</option><option value="45">45 Minuten</option><option value="60">60 Minuten</option><option value="90">90 Minuten</option></select></label><label>Format<select name="mode" defaultValue="online"><option value="online">Online</option><option value="onsite">Vor Ort</option></select></label><label className="wide">Ort oder Einwahllink<input name="location"/></label><button className="portalPrimary" type="submit">Terminvorschlag senden</button></form>;
}
