"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalPanel,PortalShell} from "./portal-shell";
type Preferences={notifyMatches:boolean;notifyMessages:boolean;notifyNeedStatus:boolean;notifyProduct:boolean;defaultAnonymous:boolean};
const defaults:Preferences={notifyMatches:true,notifyMessages:true,notifyNeedStatus:true,notifyProduct:false,defaultAnonymous:true};
export function BuyerSettingsWorkspace(){
 const[org,setOrg]=useState("");const[prefs,setPrefs]=useState(defaults);const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const token=getPortalSession();if(!token)return setNotice("Bitte erneut anmelden.");try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");setOrg(organizations[0].id);setPrefs(await portalRequest<Preferences>(`/organizations/${organizations[0].id}/preferences`,{token}))}catch(error){setNotice(error instanceof Error?error.message:"Einstellungen nicht verfügbar.")}},[]);
 useEffect(()=>{void load()},[load]);
 async function save(event:FormEvent){event.preventDefault();const token=getPortalSession();if(!token)return;setBusy(true);try{setPrefs(await portalRequest<Preferences>(`/organizations/${org}/preferences`,{token,body:prefs}));setNotice("Einstellungen wurden gespeichert.")}catch(error){setNotice(error instanceof Error?error.message:"Speichern nicht möglich.")}finally{setBusy(false)}}
 async function exportData(){const token=getPortalSession();if(!token)return;try{const data=await portalRequest(`/organizations/${org}/export`,{token});const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download=`b2b-matching-export-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setNotice("Datenexport wurde erstellt.")}catch(error){setNotice(error instanceof Error?error.message:"Export nicht möglich.")}}
 const toggle=(key:keyof Preferences)=><input type="checkbox" checked={prefs[key]} onChange={event=>setPrefs(current=>({...current,[key]:event.target.checked}))}/>;
 return <PortalShell role="unternehmen" title="Einstellungen" intro="Verwalten Sie Benachrichtigungen, Standardsichtbarkeit und Ihre gespeicherten Daten.">{notice&&<p className="portalNotice" role="status">{notice}</p>}<form onSubmit={save}><div className="settingsGrid"><PortalPanel title="Konto und Sicherheit"><div className="settingsRows"><Link href="/passwort-vergessen"><span>Passwort ändern<small>Sicheren Link per E-Mail anfordern</small></span><b aria-hidden="true">→</b></Link></div></PortalPanel><PortalPanel title="Benachrichtigungen"><div className="toggleRows"><label><span>Neue Matches<small>Passende Dienstleister</small></span>{toggle("notifyMatches")}</label><label><span>Nachrichten<small>Nachrichten und Termine</small></span>{toggle("notifyMessages")}</label><label><span>Bedarfsstatus<small>Prüfung, Freigabe und Laufzeit</small></span>{toggle("notifyNeedStatus")}</label><label><span>Produktinformationen<small>Neuigkeiten und Funktionsupdates</small></span>{toggle("notifyProduct")}</label></div></PortalPanel><PortalPanel title="Datenschutz und Sichtbarkeit"><div className="toggleRows"><label><span>Neue Bedarfe standardmäßig anonym<small>Identität erst nach Ihrer ausdrücklichen Freigabe anzeigen</small></span>{toggle("defaultAnonymous")}</label></div><div className="settingsRows"><button type="button" onClick={()=>void exportData()}><span>Datenexport herunterladen<small>Konto-, Profil-, Bedarfs- und Favoritendaten</small></span><b aria-hidden="true">↓</b></button><Link href="/cookies"><span>Cookie-Einstellungen<small>Einwilligungen verwalten</small></span><b aria-hidden="true">→</b></Link></div></PortalPanel></div><div className="formActions"><button className="portalPrimary" type="submit" disabled={busy}>{busy?"Wird gespeichert …":"Einstellungen speichern"}</button></div></form></PortalShell>
}
