"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalEmpty,PortalPanel,PortalStats} from "./portal-shell";

type Need={id:string;title:string;status:string};
type Match={id:string;status:string};
type MatchDetail={match:Match;need:Need};
type Activity={id:string;matchId:string;type:string;data:Record<string,unknown>;createdAt:string};
const labels:Record<string,string>={"conversation.opened":"Gespräch geöffnet","message.sent":"Nachricht gesendet","meeting.proposed":"Termin vorgeschlagen","meeting.confirmed":"Termin bestätigt","meeting.cancelled":"Termin abgesagt","match.identity_released":"Kontakt freigegeben","match.released":"Bedarf anonym freigegeben"};

export function BuyerActivityWorkspace(){
 const [activities,setActivities]=useState<Array<Activity&{needTitle:string}>>([]),[needs,setNeeds]=useState<Need[]>([]),[matches,setMatches]=useState<MatchDetail[]>([]),[period,setPeriod]=useState("30"),[needId,setNeedId]=useState("all"),[kind,setKind]=useState("all"),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const token=getPortalSession();if(!token){setError("Bitte melden Sie sich erneut an.");setLoading(false);return}try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");const loadedNeeds=await portalRequest<Need[]>(`/organizations/${organizations[0].id}/needs`,{token});setNeeds(loadedNeeds);const groups=await Promise.all(loadedNeeds.filter(need=>["active","paused","closed"].includes(need.status)).map(async need=>(await portalRequest<Array<{match:Match}>>(`/needs/${need.id}/match-details`,{token})).map(item=>({...item,need}))));const loadedMatches=groups.flat();setMatches(loadedMatches);const mutual=loadedMatches.filter(item=>item.match.status==="mutual_match");const histories=await Promise.all(mutual.map(async item=>(await portalRequest<Activity[]>(`/matches/${item.match.id}/timeline`,{token})).map(activity=>({...activity,needTitle:item.need.title}))));setActivities(histories.flat().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Aktivitäten konnten nicht geladen werden.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>{const since=period==="all"?0:Date.now()-Number(period)*86_400_000;return activities.filter(item=>(!since||Date.parse(item.createdAt)>=since)&&(needId==="all"||matches.find(match=>match.match.id===item.matchId)?.need.id===needId)&&(kind==="all"||item.type.startsWith(kind)))},[activities,kind,matches,needId,period]);
 const meetings=activities.filter(item=>item.type.startsWith("meeting.")).length,messages=activities.filter(item=>item.type==="message.sent").length,contacts=matches.filter(item=>item.match.status==="mutual_match").length;
 const exportCsv=()=>{const rows=[["Datum","Bedarf","Aktivität"],...visible.map(item=>[new Date(item.createdAt).toLocaleString("de-DE"),item.needTitle,labels[item.type]||item.type])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(";")).join("\n");const url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`b2b-matching-aktivitaeten-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)};
 return <>{error&&<p className="portalInlineAlert" role="alert">{error}</p>}<PortalStats items={[[String(needs.length),"Bedarfe","Gesamt gespeichert"],[String(matches.length),"Matches","Alle Status"],[String(contacts),"Freigegebene Kontakte","Beidseitig bestätigt"],[String(meetings),"Termine","Dokumentierte Vorgänge"]]}/><div className="portalGrid wideLeft"><div><PortalPanel eyebrow="DOKUMENTATION" title="Vollständige Historie">{loading?<p role="status">Aktivitäten werden geladen …</p>:visible.length?<ol className="activityTimeline">{visible.map(item=><li key={item.id}><span aria-hidden="true"/><div><time dateTime={item.createdAt}>{new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.createdAt))}</time><h3>{labels[item.type]||item.type}</h3><p>{item.needTitle}</p></div></li>)}</ol>:<PortalEmpty icon="↗" title="Keine Aktivitäten im gewählten Filter" text="Freigaben, Nachrichten und Termine werden nach beidseitigen Matches hier chronologisch dokumentiert."/ >}</PortalPanel></div><aside><PortalPanel title="Filter"><div className="filterStack"><label>Zeitraum<select value={period} onChange={event=>setPeriod(event.target.value)}><option value="30">Letzte 30 Tage</option><option value="90">Letzte 90 Tage</option><option value="365">Dieses Jahr</option><option value="all">Gesamter Zeitraum</option></select></label><label>Bedarf<select value={needId} onChange={event=>setNeedId(event.target.value)}><option value="all">Alle Bedarfe</option>{needs.map(need=><option key={need.id} value={need.id}>{need.title}</option>)}</select></label><label>Aktivität<select value={kind} onChange={event=>setKind(event.target.value)}><option value="all">Alle Aktivitäten</option><option value="match.">Freigaben</option><option value="message.">Nachrichten</option><option value="meeting.">Termine</option></select></label></div></PortalPanel><PortalPanel title="Datenexport"><p className="panelNote">{visible.length} gefilterte Einträge als CSV exportieren.</p><button className="portalSecondary full" type="button" onClick={exportCsv} disabled={!visible.length}>CSV herunterladen</button></PortalPanel><PortalPanel title="Zusammenfassung"><dl className="activitySummary"><div><dt>Nachrichten</dt><dd>{messages}</dd></div><div><dt>Terminvorgänge</dt><dd>{meetings}</dd></div></dl></PortalPanel></aside></div></>;
}
