"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalEmpty,PortalPanel,PortalShell,Status} from "./portal-shell";
type List="later"|"priority"|"contacted";
type Favorite={id:string;list:List;provider:{displayName:string};match:{score:number};services:Array<{summary:string}>};
const labels:Record<List,string>={later:"Für später",priority:"Priorität",contacted:"Bereits kontaktiert"};
export function BuyerFavoritesWorkspace(){
 const[org,setOrg]=useState("");const[items,setItems]=useState<Favorite[]>([]);const[filter,setFilter]=useState<"all"|List>("all");const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const token=getPortalSession();if(!token)return setNotice("Bitte erneut anmelden.");try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");setOrg(organizations[0].id);setItems(await portalRequest<Favorite[]>(`/organizations/${organizations[0].id}/favorites`,{token}));setNotice("")}catch(error){setNotice(error instanceof Error?error.message:"Favoriten nicht verfügbar.")}},[]);
 useEffect(()=>{void load()},[load]);const shown=useMemo(()=>filter==="all"?items:items.filter(item=>item.list===filter),[filter,items]);
 async function update(id:string,list:List){const token=getPortalSession();if(!token)return;await portalRequest(`/organizations/${org}/favorites/${id}/update`,{token,body:{list}});await load()}
 async function remove(id:string){const token=getPortalSession();if(!token)return;await portalRequest(`/organizations/${org}/favorites/${id}/remove`,{token,body:{}});await load()}
 return <PortalShell role="unternehmen" title="Favoriten und Merklisten" intro="Ordnen Sie interessante Dienstleister und behalten Sie Ihre nächsten Entscheidungen im Blick.">{notice&&<p className="portalNotice" role="status">{notice}</p>}<div className="workspaceToolbar"><div className="workspaceTabs" role="group" aria-label="Favoriten filtern"><button type="button" className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Alle <b>{items.length}</b></button>{(["later","priority","contacted"]as List[]).map(list=><button type="button" className={filter===list?"active":""} onClick={()=>setFilter(list)} key={list}>{labels[list]} <b>{items.filter(item=>item.list===list).length}</b></button>)}</div></div><PortalPanel eyebrow="GESPEICHERTE DIENSTLEISTER" title={`${shown.length} Favoriten`}>{shown.length?<div className="favoriteGrid">{shown.map(item=><article className="favoriteCard" key={item.id}><header><div><small>{item.match.score} % Passung</small><h3>{item.provider.displayName}</h3></div><Status tone={item.list==="priority"?"amber":"teal"}>{labels[item.list]}</Status></header><p>{item.services[0]?.summary||"Gespeicherter Dienstleister aus Ihrer Matching-Zentrale."}</p><label>Merkliste<select value={item.list} onChange={event=>void update(item.id,event.target.value as List)}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><footer><Link className="portalSecondary" href="/portal/unternehmen/matches">Match öffnen</Link><button className="portalIconCta" type="button" aria-label={`${item.provider.displayName} entfernen`} title="Favorit entfernen" onClick={()=>void remove(item.id)}>⌫</button></footer></article>)}</div>:<PortalEmpty icon="☆" title="Noch keine Dienstleister gespeichert" text="Speichern Sie interessante Dienstleister direkt in der Matching-Zentrale." action="Matches ansehen"/>}</PortalPanel></PortalShell>
}
