"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalEmpty,PortalPanel,PortalShell,Status} from "./portal-shell";
type Role="admin"|"needs_manager"|"communication"|"viewer";
type Member={userId:string;firstName:string;lastName:string;email:string;role:Role};
type Invitation={id:string;email:string;role:Role;expiresAt:string};
const names:Record<Role,string>={admin:"Administrator",needs_manager:"Bedarfsmanager",communication:"Kommunikation",viewer:"Leserechte"};
export function CompanyTeamWorkspace(){
 const[org,setOrg]=useState("");const[members,setMembers]=useState<Member[]>([]);const[invitations,setInvitations]=useState<Invitation[]>([]);const[open,setOpen]=useState(false);const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const token=getPortalSession();if(!token)return setNotice("Bitte erneut anmelden.");try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");setOrg(organizations[0].id);const data=await portalRequest<{members:Member[];invitations:Invitation[]}>(`/organizations/${organizations[0].id}/team`,{token});setMembers(data.members);setInvitations(data.invitations);setNotice("")}catch(error){setNotice(error instanceof Error?error.message:"Team konnte nicht geladen werden.")}},[]);
 useEffect(()=>{void load()},[load]);
 async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const token=getPortalSession();if(!token)return;const data=new FormData(event.currentTarget);try{await portalRequest(`/organizations/${org}/team/invite`,{token,body:{email:data.get("email"),role:data.get("role")}});setOpen(false);setNotice("Persönliche Einladung wurde versendet.");await load()}catch(error){setNotice(error instanceof Error?error.message:"Einladung nicht möglich.")}}
 async function role(userId:string,value:Role){const token=getPortalSession();if(!token)return;try{await portalRequest(`/organizations/${org}/team/${userId}/role`,{token,body:{role:value}});await load()}catch(error){setNotice(error instanceof Error?error.message:"Rolle nicht änderbar.")}}
 async function remove(member:Member){if(!confirm(`${member.firstName} ${member.lastName} wirklich entfernen?`))return;const token=getPortalSession();if(!token)return;try{await portalRequest(`/organizations/${org}/team/${member.userId}/remove`,{token,body:{}});await load()}catch(error){setNotice(error instanceof Error?error.message:"Zugang nicht entfernbar.")}}
 return <PortalShell role="unternehmen" title="Team und Zugänge" intro="Laden Sie Mitarbeitende persönlich ein und vergeben Sie passende Zugriffsrechte." action={<button className="portalPrimary" type="button" onClick={()=>setOpen(true)}>＋ Teammitglied einladen</button>}>{notice&&<p className="portalNotice" role="status">{notice}</p>}<PortalPanel eyebrow="BENUTZERKONTEN" title={`Aktive Zugänge (${members.length})`}>{members.map(member=><article className="teamOwner" key={member.userId}><span aria-hidden="true">{member.firstName[0]}{member.lastName[0]}</span><div><h3>{member.firstName} {member.lastName}</h3><p>{member.email}</p></div><Status tone="teal">Aktiv</Status><label><span className="srOnly">Rolle</span><select value={member.role} onChange={event=>void role(member.userId,event.target.value as Role)}>{Object.entries(names).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button className="portalIconCta" type="button" aria-label={`${member.firstName} entfernen`} onClick={()=>void remove(member)}>⌫</button></article>)}{!members.length&&<PortalEmpty icon="＋" title="Noch keine Teamzugänge" text="Laden Sie die erste zuständige Person ein."/ >}</PortalPanel><PortalPanel eyebrow="OFFENE EINLADUNGEN" title={`${invitations.length} noch nicht angenommen`}>{invitations.length?invitations.map(item=><article className="teamOwner" key={item.id}><span aria-hidden="true">✉</span><div><h3>{item.email}</h3><p>{names[item.role]} · gültig bis {new Intl.DateTimeFormat("de-DE").format(new Date(item.expiresAt))}</p></div><Status tone="amber">Eingeladen</Status></article>):<PortalEmpty icon="✓" title="Keine offenen Einladungen" text="Derzeit wartet keine Einladung auf Annahme."/ >}</PortalPanel>{open&&<div className="portalModalBackdrop"><section className="portalModal" role="dialog" aria-modal="true" aria-labelledby="invite-title"><header><div><small>UNTERNEHMENSZUGANG</small><h2 id="invite-title">Teammitglied einladen</h2></div><button type="button" aria-label="Schließen" onClick={()=>setOpen(false)}>×</button></header><form onSubmit={invite}><div className="portalFormGrid"><label className="full">Geschäftliche E-Mail-Adresse<input name="email" type="email" required/></label><label className="full">Rolle<select name="role" defaultValue="needs_manager">{Object.entries(names).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><p>Der persönliche Einladungslink ist 14 Tage gültig.</p><footer><button className="portalSecondary" type="button" onClick={()=>setOpen(false)}>Abbrechen</button><button className="portalPrimary" type="submit">Einladung senden</button></footer></form></section></div>}</PortalShell>
}
