"use client";
import { useEffect, useState } from "react";
type Choice={necessary:true;statistics:boolean;marketing:boolean;date:string};
const KEY="b2b-matching-consent-v1";
export function CookieConsent(){
  const [open,setOpen]=useState(false);const [details,setDetails]=useState(false);const [statistics,setStatistics]=useState(false);const [marketing,setMarketing]=useState(false);
  useEffect(()=>{setOpen(!localStorage.getItem(KEY));const handler=()=>setOpen(true);window.addEventListener("open-cookie-settings",handler);return()=>window.removeEventListener("open-cookie-settings",handler)},[]);
  function save(stats:boolean,ads:boolean){const choice:Choice={necessary:true,statistics:stats,marketing:ads,date:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(choice));setOpen(false);window.dispatchEvent(new CustomEvent("consent-updated",{detail:choice}))}
  if(!open)return null;
  return <div className="consentBackdrop"><section className="consentDialog" role="dialog" aria-modal="true" aria-labelledby="consent-title"><span className="consentIcon" aria-hidden="true">B2</span><div><h2 id="consent-title">Ihre Privatsphäre. Ihre Entscheidung.</h2><p>Notwendige Technologien sichern Anmeldung, Einstellungen und Betrieb. Statistik und Marketing bleiben deaktiviert, bis Sie ausdrücklich zustimmen. Aktuell sind keine optionalen Trackingdienste eingebunden.</p></div>{details&&<div className="consentOptions"><label><span><strong>Notwendig</strong><small>Immer aktiv · Sicherheit, Sitzung, Consent und Web-App</small></span><input type="checkbox" checked disabled/></label><label><span><strong>Statistik</strong><small>Anonyme Nutzungsanalyse – derzeit kein Dienst aktiv</small></span><input type="checkbox" checked={statistics} onChange={e=>setStatistics(e.target.checked)}/></label><label><span><strong>Marketing</strong><small>Personalisierung und Kampagnenmessung – derzeit kein Dienst aktiv</small></span><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/></label></div>}<div className="consentActions"><button className="consentSecondary" onClick={()=>setDetails(!details)}>{details?"Einstellungen schließen":"Individuelle Einstellungen"}</button><button className="consentSecondary" onClick={()=>save(false,false)}>Nur notwendige</button><button className="consentPrimary" onClick={()=>save(details?statistics:true,details?marketing:true)}>Alle akzeptieren</button></div><p className="consentLinks"><a href="/cookies">Cookie-Richtlinie</a> · <a href="/datenschutz/unternehmen">Datenschutz</a></p></section></div>
}
export function CookieSettingsButton(){return <button className="cookieSettings" onClick={()=>window.dispatchEvent(new Event("open-cookie-settings"))}>Cookie-Einstellungen</button>}
