"use client";
import {useEffect,useMemo,useState} from "react";
import {PORTAL_UPDATE_EVENT,readNeeds,StoredNeed,writeNeeds} from "../lib/entrepreneur-state";

const tabs=["Alle","Entwürfe","In Prüfung","Aktiv","Pausiert","Archiv"];
const tabStatus:Record<string,StoredNeed["status"]|undefined>={"Entwürfe":"Entwurf","In Prüfung":"In Prüfung","Aktiv":"Aktiv","Pausiert":"Pausiert","Archiv":"Archiv"};

export function NeedsWorkspace(){
 const [needs,setNeeds]=useState<StoredNeed[]>([]);
 const [tab,setTab]=useState("Alle");
 const [query,setQuery]=useState("");
 const refresh=()=>setNeeds(readNeeds());
 useEffect(()=>{refresh();window.addEventListener(PORTAL_UPDATE_EVENT,refresh);return()=>window.removeEventListener(PORTAL_UPDATE_EVENT,refresh)},[]);
 const visible=useMemo(()=>needs.filter(need=>(!tabStatus[tab]||need.status===tabStatus[tab])&&(!query||`${need.title} ${need.category} ${need.summary}`.toLowerCase().includes(query.toLowerCase()))),[needs,query,tab]);
 function update(id:string,status:StoredNeed["status"]){writeNeeds(needs.map(need=>need.id===id?{...need,status,updatedAt:new Date().toISOString()}:need));refresh()}
 function duplicate(need:StoredNeed){writeNeeds([{...need,id:crypto.randomUUID(),title:`${need.title} (Kopie)`,status:"Entwurf",updatedAt:new Date().toISOString()},...needs]);refresh()}
 return <><div className="workspaceToolbar"><div className="workspaceTabs">{tabs.map(item=><button type="button" className={tab===item?"active":""} key={item} onClick={event=>{event.stopPropagation();setTab(item)}}>{item} <b>{item==="Alle"?needs.length:needs.filter(need=>need.status===tabStatus[item]).length}</b></button>)}</div><label className="workspaceFilter"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Bedarfe filtern" aria-label="Bedarfe filtern"/></label></div><div className="portalStats">{[[""+needs.length,"Gesamte Bedarfe"],[""+needs.filter(n=>n.status==="Aktiv").length,"Aktive Suchen"],["0","Gefundene Matches"],["0","Profilaufrufe"]].map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}<small>{needs.length?"Aktueller Stand":"Noch keine Einträge"}</small></span></article>)}</div><section className="portalPanel"><div className="portalPanelTitle"><span>BEDARFSZENTRALE</span><h2>Ihre Bedarfe</h2></div>{visible.length?<div className="needRows">{visible.map(need=><article key={need.id}><div><span className={`status ${need.status==="Aktiv"?"teal":need.status==="Archiv"?"gray":"amber"}`}>{need.status}</span><h3>{need.title}</h3><p>{need.category}{need.summary?` · ${need.summary}`:""}</p><small>Zuletzt geändert: {new Date(need.updatedAt).toLocaleDateString("de-DE")}</small></div><div><button type="button" className="portalSecondary" onClick={event=>{event.stopPropagation();duplicate(need)}}>Duplizieren</button>{need.status!=="Aktiv"&&need.status!=="Archiv"&&<button type="button" className="portalPrimary" onClick={event=>{event.stopPropagation();update(need.id,"Aktiv")}}>Veröffentlichen</button>}{need.status==="Aktiv"&&<button type="button" className="portalSecondary" onClick={event=>{event.stopPropagation();update(need.id,"Pausiert")}}>Pausieren</button>}{need.status!=="Archiv"&&<button type="button" className="portalSecondary" onClick={event=>{event.stopPropagation();update(need.id,"Archiv")}}>Archivieren</button>}</div></article>)}</div>:<div className="portalEmpty"><span aria-hidden="true">◇</span><h3>{needs.length?"Keine Bedarfe in dieser Ansicht":"Erstellen Sie Ihren ersten Bedarf"}</h3><p>{needs.length?"Ändern Sie Filter oder Statusauswahl.":"Nutzen Sie die ausführliche Erfassung oder lassen Sie einen strukturierten Entwurf mit dem KI-Assistenten erstellen."}</p>{!needs.length&&<button className="portalSecondary">Ersten Bedarf erstellen</button>}</div>}</section></>;
}
