"use client";

import {ChangeEvent,FormEvent,useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {useNetworkAccess} from "./network-shell";

type EventItem={id:string;title:string;description:string;status:string;startsAt:string|null;updatedAt:string;data:{recapSummary?:string;recapResults?:string;recapImages?:string[]}};

export function NetworkEventRecapWorkspace(){
 const access=useNetworkAccess(),[events,setEvents]=useState<EventItem[]>([]),[editing,setEditing]=useState<EventItem|null>(null),[images,setImages]=useState<string[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const token=getPortalSession();if(!token||!access?.networkId)return;portalRequest<EventItem[]>(`/networks/${access.networkId}/content?type=event`,{token}).then(items=>setEvents(items.sort((a,b)=>(b.startsAt||b.updatedAt).localeCompare(a.startsAt||a.updatedAt)))).catch(error=>setNotice(error instanceof Error?error.message:"Rückblicke konnten nicht geladen werden."))},[access?.networkId]);
 function edit(item:EventItem){setEditing(item);setImages(item.data.recapImages||[])}
 function addImages(event:ChangeEvent<HTMLInputElement>){const files=[...(event.target.files||[])];if(images.length+files.length>6){setNotice("Pro Veranstaltung können höchstens sechs Bilder veröffentlicht werden.");return}for(const file of files){if(!file.type.startsWith("image/")||file.size>1_500_000){setNotice("Jedes Bild muss eine Bilddatei mit maximal 1,5 MB sein.");continue}const reader=new FileReader();reader.onload=()=>{if(typeof reader.result==="string")setImages(current=>[...current,reader.result as string].slice(0,6))};reader.readAsDataURL(file)}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing||!access?.networkId)return;const token=getPortalSession();if(!token)return;const form=new FormData(event.currentTarget);setBusy(true);try{const updated=await portalRequest<EventItem>(`/networks/${access.networkId}/content/${editing.id}`,{token,body:{status:"completed",data:{recapSummary:form.get("recapSummary"),recapResults:form.get("recapResults"),recapImages:images,recapPublishedAt:new Date().toISOString()}}});setEvents(current=>current.map(item=>item.id===updated.id?updated:item));setEditing(null);setNotice("Der Veranstaltungsrückblick wurde veröffentlicht.")}catch(error){setNotice(error instanceof Error?error.message:"Rückblick konnte nicht gespeichert werden.")}finally{setBusy(false)}}
 const published=events.filter(item=>item.data.recapSummary);
 return <div className="networkFunctionalWorkspace">
  {notice&&<div className="networkNotice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
  <section className="networkCard"><header><div><span>CHRONOLOGISCHES ARCHIV</span><h2>Vergangene Netzwerkveranstaltungen</h2></div></header>
   <div className="networkRecapGrid">{published.map(item=><article key={item.id}>{item.data.recapImages?.[0]&&<img src={item.data.recapImages[0]} alt=""/>}<div><time>{new Date(item.startsAt||item.updatedAt).toLocaleDateString("de-DE")}</time><h3>{item.title}</h3><p>{item.data.recapSummary}</p>{item.data.recapResults&&<aside><b>Ergebnisse</b><p>{item.data.recapResults}</p></aside>}{access?.isInitiator&&<button type="button" onClick={()=>edit(item)}>Rückblick bearbeiten</button>}</div></article>)}{!published.length&&<div className="networkEmpty"><b>Noch keine Rückblicke veröffentlicht</b><p>Nach einer Veranstaltung kann der Initiator Bilder, Zusammenfassung und Ergebnisse ergänzen.</p></div>}</div>
  </section>
  {access?.isInitiator&&<section className="networkCard"><header><div><span>FÜR DEN INITIATOR</span><h2>Rückblick zu einer Veranstaltung anlegen</h2></div></header><div className="networkRecapEventList">{events.map(item=><button type="button" key={item.id} onClick={()=>edit(item)}><span>{new Date(item.startsAt||item.updatedAt).toLocaleDateString("de-DE")}</span><b>{item.title}</b><small>{item.data.recapSummary?"Rückblick vorhanden":"Noch ohne Rückblick"}</small></button>)}</div></section>}
  {editing&&<div className="networkModalBackdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setEditing(null)}}><section className="networkModal networkContentModal" role="dialog" aria-modal="true"><header><div><span>VERANSTALTUNGSRÜCKBLICK</span><h2>{editing.title}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></header><form onSubmit={save}><label>Worum ging es?<textarea name="recapSummary" required minLength={20} rows={5} defaultValue={editing.data.recapSummary||""}/></label><label>Ergebnisse und nächste Schritte<textarea name="recapResults" rows={4} defaultValue={editing.data.recapResults||""}/></label><label>Bilder<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={addImages}/><small>Bis zu sechs Bilder, jeweils maximal 1,5 MB.</small></label>{images.length>0&&<div className="networkRecapImages">{images.map((image,index)=><button type="button" key={index} onClick={()=>setImages(current=>current.filter((_,i)=>i!==index))}><img src={image} alt={`Rückblickbild ${index+1}`}/><span>Entfernen</span></button>)}</div>}<footer className="adminNetworkDialogActions"><button type="button" onClick={()=>setEditing(null)}>Abbrechen</button><button className="portalPrimary" disabled={busy}>{busy?"Wird veröffentlicht …":"Rückblick veröffentlichen"}</button></footer></form></section></div>}
 </div>
}
