"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
type Network={id:string;name:string;status:string;offeredModules:string[]};
type Module={id:string;name:string;shortDescription:string;unitNetCents:number;required?:boolean};
type Catalog={modules:Module[];completeUnitNetCents:number;setupNetCents:number;currency:string;billingUnit:string};
type Order={id:string;status:string;submittedAt:string;billingCycle:"annual";participantCount:number;selectedModules:string[];pricingMode:"individual"|"complete";monthlyNetCents:number;setupNetCents:number};
const money=(cents:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(cents/100);
export function NetworkBookingWorkspace({slug}:{slug:string}){
 const[network,setNetwork]=useState<Network|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[existing,setExisting]=useState<Order|null>(null),[error,setError]=useState(""),[submitting,setSubmitting]=useState(false),[participants]=useState(1),[mode,setMode]=useState<"individual"|"complete">("individual"),[selected,setSelected]=useState<string[]>(["profiles"]);
 useEffect(()=>{const token=getPortalSession();if(!token)return;Promise.all([portalRequest<Network>(`/networks/public/${slug}`,{token}),portalRequest<Catalog>("/networks/modules/catalog")]).then(async([found,moduleCatalog])=>{const personalCatalog={...moduleCatalog,modules:moduleCatalog.modules.filter(item=>found.offeredModules.includes(item.id))};setNetwork(found);setCatalog(personalCatalog);setSelected(personalCatalog.modules.filter(item=>item.required).map(item=>item.id));const orders=await portalRequest<Order[]>(`/networks/${found.id}/orders`,{token});setExisting(orders.find(item=>["submitted","accepted"].includes(item.status))||null)}).catch(reason=>setError(reason instanceof Error?reason.message:"Die Buchungsdaten konnten nicht geladen werden."))},[slug]);
 const chosen=useMemo(()=>catalog?(mode==="complete"?catalog.modules:catalog.modules.filter(item=>selected.includes(item.id))):[],[catalog,mode,selected]);
 const unitNetCents=catalog?(mode==="complete"?catalog.completeUnitNetCents:chosen.reduce((sum,item)=>sum+item.unitNetCents,0)):0,monthlyNetCents=unitNetCents*participants;
 function toggle(id:string){if(catalog?.modules.find(item=>item.id===id)?.required)return;setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id])}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!network||!catalog||submitting)return;setSubmitting(true);setError("");const token=getPortalSession(),form=new FormData(event.currentTarget);try{const order=await portalRequest<Order>(`/networks/${network.id}/orders`,{token:token||undefined,body:{invoiceCompany:form.get("invoiceCompany"),invoiceContact:form.get("invoiceContact"),invoiceEmail:form.get("invoiceEmail"),invoiceStreet:form.get("invoiceStreet"),invoicePostalCode:form.get("invoicePostalCode"),invoiceCity:form.get("invoiceCity"),invoiceCountry:form.get("invoiceCountry"),purchaseOrderReference:form.get("purchaseOrderReference"),billingCycle:form.get("billingCycle"),participantCount:participants,pricingMode:mode,selectedModules:chosen.map(item=>item.id),authorityConfirmed:form.get("authorityConfirmed")==="on",termsAccepted:form.get("termsAccepted")==="on",paymentObligationAccepted:form.get("paymentObligationAccepted")==="on"}});setExisting(order)}catch(reason){setError(reason instanceof Error?reason.message:"Die Bestellung konnte nicht gespeichert werden.")}finally{setSubmitting(false)}}
 if(existing)return <section className="networkOrderSuccess"><span>ZUGANG AKTIVIERT</span><h2>Ihre Module sind sofort nutzbar.</h2><p><strong>1 persönlicher Nutzerzugang</strong> · {existing.selectedModules.length} kostenpflichtige Module<br/><strong>{money(existing.monthlyNetCents)} netto pro Monat</strong> · zwölf Monate im Voraus</p><p>Bestellnummer {existing.id}<br/>Aktiviert am {new Date(existing.submittedAt).toLocaleString("de-DE")}</p><div><b>Rechnung</b><p>Die verbindliche Buchung wurde aktiviert. Die Rechnung ist innerhalb von 14 Tagen zu begleichen.</p></div><Link href={`/portal/netzwerk/${slug}` as never}>Zum Netzwerkportal →</Link></section>;
 if(!network||!catalog)return <section className="networkCard networkLoading"><p>{error||"Modulkatalog wird geladen …"}</p></section>;
 const annual=monthlyNetCents*12;
 return <form className="networkBooking" onSubmit={submit}>
  <section className="networkBookingSummary"><div><span>PERSÖNLICHE MODULBUCHUNG</span><h2>Wählen Sie Ihren Funktionsumfang in {network.name}</h2><p>Der Initiator hat diese Module für das Netzwerk angeboten. Sie bezahlen ausschließlich die Module Ihres eigenen Zugangs.</p></div><div><p><strong>{money(monthlyNetCents)}</strong> netto / Monat</p><p><strong>1</strong> persönlicher Nutzerzugang</p><small>{money(annual)} netto für 12 Monate im Voraus</small></div></section>
  <section className="networkBookingSection"><header><span>1</span><div><h3>Ihr persönlicher Zugang</h3><p>Unternehmensseiten sind verpflichtend. Partnerverzeichnis und Whitelabel-Auftritt des Netzwerks sind kostenlos enthalten.</p></div></header><div className="networkBillingOptions"><label><input type="radio" checked={mode==="individual"} onChange={()=>setMode("individual")}/><span><b>Module einzeln wählen</b><small>Sie bezahlen nur Ihre persönliche Auswahl.</small></span></label>{catalog.modules.length===10&&<label><input type="radio" checked={mode==="complete"} onChange={()=>setMode("complete")}/><span><b>Komplettpaket</b><small>{money(catalog.completeUnitNetCents)} netto je Monat für alle Module</small></span></label>}</div></section>
  <section className="networkBookingSection"><header><span>2</span><div><h3>Module auswählen</h3><p>Alle Preise gelten netto je aktivem Nutzer und Monat und sind für zwölf Monate im Voraus zu zahlen.</p></div></header><div className="networkModuleCatalog">{catalog.modules.map(item=><label className={mode==="complete"||selected.includes(item.id)?"selected":""} key={item.id}><input type="checkbox" checked={mode==="complete"||selected.includes(item.id)} disabled={mode==="complete"||item.required} onChange={()=>toggle(item.id)}/><span><b>{item.name}{item.required?" · Basis":""}</b><small>{item.shortDescription}</small></span><strong>{money(item.unitNetCents)}<small> / Nutzer</small></strong></label>)}</div><p>Immer kostenlos enthalten: geschlossenes Partnerverzeichnis sowie Netzwerkname, Logo, Farben und Whitelabel-Auftritt.</p></section>
  <section className="networkBookingSection"><header><span>3</span><div><h3>Rechnungsempfänger</h3><p>Bitte geben Sie die vollständigen geschäftlichen Rechnungsdaten an.</p></div></header><div className="networkBookingFields"><label className="wide">Firma / Organisation<input name="invoiceCompany" required maxLength={200}/></label><label>Ansprechpartner<input name="invoiceContact" required maxLength={160}/></label><label>Rechnungs-E-Mail<input name="invoiceEmail" type="email" required maxLength={250}/></label><label className="wide">Straße und Hausnummer<input name="invoiceStreet" required maxLength={200}/></label><label>Postleitzahl<input name="invoicePostalCode" required maxLength={12}/></label><label>Ort<input name="invoiceCity" required maxLength={120}/></label><label>Land<input name="invoiceCountry" defaultValue="Deutschland" required maxLength={80}/></label><label>Bestellreferenz (optional)<input name="purchaseOrderReference" maxLength={120}/></label></div></section>
  <section className="networkBookingSection"><header><span>4</span><div><h3>Jährliche Vorauszahlung</h3><p>Alle Modulpreise werden verbindlich für zwölf Monate im Voraus abgerechnet.</p></div></header><input type="hidden" name="billingCycle" value="annual"/><div className="networkBillingOptions"><label><input type="radio" checked readOnly/><span><b>12 Monate im Voraus</b><small>{money(annual)} netto für Ihren Zugang</small></span></label></div></section>
  <section className="networkBookingSection"><header><span>5</span><div><h3>Vertrag verbindlich abschließen</h3><p>Prüfen und bestätigen Sie Teilnehmerzahl, Module und Abrechnung.</p></div></header><div className="networkBookingConsents"><label><input type="checkbox" name="authorityConfirmed" required/><span>Ich bestätige, für den Rechnungsempfänger vertretungs- oder entscheidungsberechtigt zu sein.</span></label><label><input type="checkbox" name="termsAccepted" required/><span>Ich akzeptiere die <Link href="/agb" target="_blank">AGB</Link> und die ausgewählten Module, Preise, Mindestlaufzeit und Vorauszahlung.</span></label><label><input type="checkbox" name="paymentObligationAccepted" required/><span>Ich bestätige ausdrücklich, dass diese Bestellung kostenpflichtig ist und die Einrichtung zusätzlich berechnet wird.</span></label></div></section>
  {error&&<p className="networkBookingError" role="alert">{error}</p>}<footer className="networkBookingFooter"><p><b>{money(annual)} netto für 12 Monate</b><small>1 Nutzer · {chosen.length} kostenpflichtige Module · keine Einrichtungsgebühr</small></p><button type="submit" disabled={submitting}>{submitting?"Bestellung wird übermittelt …":"Meine Module zahlungspflichtig bestellen"}</button></footer>
 </form>;
}
