"use client";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {createContext,useContext,useEffect,useState,type CSSProperties,type ReactNode} from "react";
import {clearPortalSession,getPortalSession,portalRequest} from "../lib/portal-api";
type Access={networkId:string;slug:string;networkName:string;role:string;canManage:boolean;isInitiator:boolean;readOnly:boolean;status:string;enabledModules:string[];offeredModules:string[];logoUrl:string|null;primaryColor:string;secondaryColor:string};
type Mine={membership:{role:string};network:{id:string;slug:string;name:string;status:string;trialEndsAt:string|null}};
const NetworkAccessContext=createContext<Access|null>(null);export const useNetworkAccess=()=>useContext(NetworkAccessContext);
const primaryPartnerItems=[{path:"",label:"Netzwerk-Startseite",icon:"⌂"},{path:"mitglieder",label:"Partnerverzeichnis",icon:"♙",module:"profiles"},{path:"veranstaltungen",label:"Veranstaltungen",icon:"□",module:"events"},{path:"kommunikation",label:"Nachrichten",icon:"✉",module:"communication"},{path:"profil",label:"Meine Partnerseite",icon:"▣",module:"profiles"}];
const morePartnerItems=[{path:"rueckblicke",label:"Veranstaltungsrückblicke",icon:"◫",module:"events"},{path:"angebote",label:"Angebote & Leistungen",icon:"◇",module:"services"},{path:"themen",label:"Community",icon:"◉",module:"community"},{path:"aufgaben",label:"Aufgaben",icon:"✓",module:"tasks"},{path:"dokumente",label:"Dokumente",icon:"▤",module:"documents"}];
const adminItems=[{path:"einstellungen",label:"Branding & Module",icon:"⚙"},{path:"mitglieder",label:"Mitglieder & Einladungen",icon:"♙",module:"profiles"},{path:"veranstaltungen",label:"Veranstaltungen verwalten",icon:"□",module:"events"},{path:"themen",label:"Mitteilungen & Community",icon:"◉",module:"community"},{path:"auswertungen",label:"Auswertungen",icon:"↗",module:"analytics"},{path:"umsaetze",label:"Vermittelter Umsatz",icon:"€",module:"revenue"}];
export function NetworkShell({title,intro,children,action,slug,networkName="Netzwerk"}:{title:string;intro:string;children:ReactNode;action?:ReactNode;slug:string;networkName?:string}){
 const pathname=usePathname(),router=useRouter(),[account,setAccount]=useState(false),[access,setAccess]=useState<Access|null>(null),[error,setError]=useState(""),[trialAcknowledged,setTrialAcknowledged]=useState(false),base=`/portal/netzwerk/${slug}`;
 useEffect(()=>{let active=true;const validate=async()=>{const token=getPortalSession();if(!token){router.replace(`/anmelden?network=${encodeURIComponent(slug)}` as never);return}try{const[session,network,mine]=await Promise.all([portalRequest<{accountRole:string}>("/auth/session/check",{token,body:{}}),portalRequest<{id:string;slug:string;name:string;status:string;enabledModules:string[];offeredModules:string[];logoUrl:string|null;primaryColor:string;secondaryColor:string}>(`/networks/public/${slug}`,{token}),portalRequest<Mine[]>("/networks/mine",{token})]);const membership=mine.find(item=>item.network.id===network.id);if(session.accountRole!=="platform_admin"&&!membership)throw new Error("Sie sind diesem Netzwerk nicht als aktives Mitglied zugeordnet.");const role=session.accountRole==="platform_admin"?"platform_admin":membership!.membership.role,isInitiator=session.accountRole==="platform_admin"||role==="network_admin";if(active)setAccess({networkId:network.id,slug:network.slug,networkName:network.name,role,canManage:isInitiator||role==="moderator",isInitiator,readOnly:network.status==="trial",status:network.status,enabledModules:network.enabledModules,offeredModules:network.offeredModules,logoUrl:network.logoUrl,primaryColor:network.primaryColor,secondaryColor:network.secondaryColor})}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Der Netzwerkzugang konnte nicht geprüft werden.")}};void validate();return()=>{active=false}},[pathname,router,slug]);
 useEffect(()=>{if(!access)return;if(!access.readOnly){setTrialAcknowledged(true);return}setTrialAcknowledged(sessionStorage.getItem(`network-trial-understood:${access.networkId}`)==="yes")},[access]);
 if(error)return <main className="networkAccessState"><section><span>ZUGRIFF GESCHÜTZT</span><h1>Dieser Netzwerkbereich ist nicht verfügbar.</h1><p>{error}</p></section></main>;
 if(!access)return <main className="networkAccessState"><section><span>SICHERER ZUGANG</span><h1>Netzwerkzugang wird geprüft.</h1></section></main>;
 const shownName=access.networkName||networkName,initials=shownName.slice(0,2).toUpperCase(),visiblePrimary=primaryPartnerItems.filter(item=>!item.module||access.enabledModules.includes(item.module)),visibleMore=morePartnerItems.filter(item=>!item.module||access.enabledModules.includes(item.module)),visibleAdmin=adminItems.filter(item=>!item.module||access.enabledModules.includes(item.module)),href=(path:string)=>path?`${base}/${path}`:base,isActive=(path:string)=>pathname===href(path),logout=()=>{clearPortalSession();router.replace(`/anmelden?network=${encodeURIComponent(slug)}` as never)},style={"--network-accent":access.primaryColor,"--network-dark":access.secondaryColor,"--network-soft":`${access.primaryColor}18`} as CSSProperties;
 const itemLink=(item:{path:string;label:string;icon:string})=><Link key={item.path||"home"} className={isActive(item.path)?"active":""} href={href(item.path) as never}><span>{item.icon}</span>{item.label}</Link>;
 const navigation=<><nav className="networkSimpleNav" aria-label="Netzwerk"><small>NETZWERK</small>{visiblePrimary.map(itemLink)}</nav>{visibleMore.length>0&&<details className="networkMoreNav"><summary><span>＋</span><b>Weitere Funktionen</b></summary><nav>{visibleMore.map(itemLink)}</nav></details>}{access.isInitiator&&<details className="networkAdminNav"><summary><span>⚙</span><b>Netzwerk-Verwaltung</b><small>Initiator</small></summary><nav>{visibleAdmin.map(itemLink)}</nav></details>}</>;
 const acknowledgeTrial=()=>{sessionStorage.setItem(`network-trial-understood:${access.networkId}`,"yes");setTrialAcknowledged(true)};
 return <NetworkAccessContext.Provider value={access}><main className="networkPortal" style={style}><aside className="networkSidebar"><Link href={base as never} className="networkBrand"><span>{access.logoUrl?<img src={access.logoUrl} alt=""/>:initials}</span><div><strong>{shownName}</strong><small>Partnerportal</small></div></Link>{navigation}<div className="networkSupport"><b>Hilfe & Kontakt</b><p>Fragen zum Netzwerkzugang?</p><a href="mailto:service@b2b-matching.de">Support kontaktieren</a></div></aside><section className="networkMain"><header className="networkTop"><details className="networkMobileNav"><summary aria-label="Netzwerkmenü öffnen">☰</summary>{navigation}</details><div className="networkContext">{access.logoUrl?<img src={access.logoUrl} alt=""/>:<span>{initials}</span>}<p><b>{shownName}</b><small>Geschlossenes Partnernetzwerk</small></p></div><div className="networkTopActions">{access.enabledModules.includes("communication")&&<Link href={`${base}/kommunikation` as never} aria-label="Nachrichten">✉</Link>}<button type="button" onClick={()=>setAccount(!account)} aria-expanded={account}><span>{initials}</span><p><b>{access.isInitiator?"Initiator":"Netzwerkpartner"}</b><small>Mein Zugang</small></p></button>{account&&<div className="networkAccountMenu">{access.isInitiator&&<Link href={`${base}/einstellungen` as never}>Netzwerk-Verwaltung</Link>}<Link href={`${base}/profil` as never}>Meine Partnerseite</Link><button type="button" onClick={logout}>Abmelden</button></div>}</div></header><div className="networkContent">{access.readOnly&&<div className="networkReadOnlyNotice">Testansicht: Änderungen und Einladungen sind bis zur Aktivierung eingeschränkt.</div>}<header className="networkWelcome"><div><span>{shownName.toUpperCase()}</span><h1>{title}</h1><p>{intro}</p></div>{action}</header>{children}</div></section></main>{access.readOnly&&!trialAcknowledged&&<div className="networkTrialGate"><section role="dialog" aria-modal="true"><span>TESTANSICHT</span><h2>Willkommen bei {shownName}</h2><p>Sie können Aufbau und Funktionen ansehen. Produktive Einladungen und Veröffentlichungen werden nach der Aktivierung freigeschaltet.</p><button type="button" onClick={acknowledgeTrial}>Verstanden – Netzwerk öffnen</button></section></div>}</NetworkAccessContext.Provider>
}
