"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {useNetworkAccess} from "./network-shell";
type Member={id:string;status:string;user:{firstName:string;lastName:string}|null;organization:{displayName:string;legalName:string}|null};
type Revenue={id:string;amountNetCents:number;periodFrom:string;periodTo:string;status:"recorded"|"confirmed"|"paid"|"cancelled";note:string|null;referring:{organizationName:string;contactName:string};beneficiary:{organizationName:string;contactName:string}};
const statusLabels={recorded:"Erfasst",confirmed:"Bestätigt",paid:"Abgerechnet",cancelled:"Storniert"};
export function NetworkRevenueWorkspace(){
 const access=useNetworkAccess(),networkId=access?.networkId||"",[members,setMembers]=useState<Member[]>([]),[rows,setRows]=useState<Revenue[]>([]),[dialog,setDialog]=useState(false),[notice,setNotice]=useState("");
 const allowed=access?.role==="platform_admin"||access?.role==="network_admin";
 async function load(){const token=getPortalSession();if(!token||!networkId||!allowed)return;try{const [m,r]=await Promise.all([portalRequest<Member[]>(`/networks/${networkId}/memberships`,{token}),portalRequest<Revenue[]>(`/networks/${networkId}/revenues`,{token})]);setMembers(m.filter(x=>x.status==="active"));setRows(r)}catch(e){setNotice(e instanceof Error?e.message:"Umsätze konnten nicht geladen werden.")}}
 useEffect(()=>{void load()},[networkId,allowed]);
 const total=useMemo(()=>rows.filter(x=>x.status!=="cancelled").reduce((sum,x)=>sum+x.amountNetCents,0),[rows]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const token=getPortalSession();if(!token)return;const form=new FormData(event.currentTarget);try{await portalRequest(`/networks/${networkId}/revenues`,{token,body:Object.fromEntries(form)});setDialog(false);await load();setNotice("Vermittelter Umsatz wurde vertraulich gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Speichern nicht möglich.")}}
 function exportExcel(){const lines=[["Zeitraum","Vermittelndes Mitglied","Begünstigtes Mitglied","Betrag netto","Status"],...rows.map(x=>[`${x.periodFrom} – ${x.periodTo}`,x.referring.organizationName,x.beneficiary.organizationName,(x.amountNetCents/100).toFixed(2),statusLabels[x.status]])];const html=`<table>${lines.map(r=>`<tr>${r.map(c=>`<td>${String(c).replaceAll("&","&amp;").replaceAll("<","&lt;")}</td>`).join("")}</tr>`).join("")}</table>`,a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",html],{type:"application/vnd.ms-excel"}));a.download="vermittelter-umsatz.xls";a.click();URL.revokeObjectURL(a.href)}
 if(!allowed)return <section className="networkCard"><div className="networkEmpty"><b>Geschützter Verwaltungsbereich</b><p>Vermittelte Umsätze sind ausschließlich für berechtigte Netzwerkadministratoren sichtbar.</p></div></section>;
 const name=(m:Member)=>m.organization?.displayName||m.organization?.legalName||`${m.user?.firstName||""} ${m.user?.lastName||""}`.trim()||"Mitglied";
 return <div className="networkFunctionalWorkspace"><div className="networkMemberStats"><button><strong>{rows.length}</strong><span>Vermittlungen</span></button><button><strong>{(total/100).toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</strong><span>Gesamt netto</span></button><button><strong>{rows.filter(x=>x.status==="confirmed").length}</strong><span>Bestätigt</span></button></div><section className="networkCard"><header><div><span>VERTRAULICHE AUSWERTUNG</span><h2>Vermittelter Umsatz</h2></div><div><button onClick={exportExcel} disabled={!rows.length}>Excel</button>{!access?.readOnly&&<button className="networkPrimary" onClick={()=>setDialog(true)}>＋ Umsatz erfassen</button>}</div></header><div className="networkContentRows">{rows.map(row=><article key={row.id}><div><span className={`networkMemberStatus ${row.status}`}>{statusLabels[row.status]}</span><h3>{row.referring.organizationName} → {row.beneficiary.organizationName}</h3><p>{row.periodFrom} bis {row.periodTo}{row.note?` · ${row.note}`:""}</p></div><strong>{(row.amountNetCents/100).toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</strong></article>)}</div>{!rows.length&&<div className="networkEmpty"><b>Noch keine vermittelten Umsätze erfasst</b><p>Die Angaben bleiben vollständig innerhalb der berechtigten Netzwerkadministration.</p></div>}</section>{dialog&&<div className="networkModalBackdrop"><section className="networkModal networkContentModal"><header><div><span>VERTRAULICHE ERFASSUNG</span><h2>Vermittelten Umsatz erfassen</h2></div><button onClick={()=>setDialog(false)}>×</button></header><form onSubmit={submit}><div><label>Vermittelndes Mitglied<select name="referringMembershipId" required>{members.map(m=><option value={m.id} key={m.id}>{name(m)}</option>)}</select></label><label>Begünstigtes Mitglied<select name="beneficiaryMembershipId" required>{members.map(m=><option value={m.id} key={m.id}>{name(m)}</option>)}</select></label></div><div><label>Umsatzbetrag netto<input name="amount" type="number" min="0" step="0.01" required/></label><label>Status<select name="status"><option value="recorded">Erfasst</option><option value="confirmed">Bestätigt</option><option value="paid">Abgerechnet</option><option value="cancelled">Storniert</option></select></label></div><div><label>Zeitraum von<input name="periodFrom" type="date" required/></label><label>Zeitraum bis<input name="periodTo" type="date" required/></label></div><label>Interne Notiz<textarea name="note" rows={3}/></label><div className="adminNetworkDialogActions"><button type="button" onClick={()=>setDialog(false)}>Abbrechen</button><button className="networkPrimary">Vertraulich speichern</button></div></form></section></div>}{notice&&<div className="networkNotice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</div>
}
