"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
type Member={id:string;role:string;status:"pending"|"active"|"rejected"|"suspended"|"left";updatedAt:string;user:{firstName:string;lastName:string;email:string}|null;organization:{displayName:string;legalName:string}|null};
const labels={pending:"Antrag",active:"Aktiv",rejected:"Abgelehnt",suspended:"Deaktiviert",left:"Ausgetreten"} as const;
export function NetworkMembersWorkspace({slug="unternehmerfreunde-nrw"}:{slug?:string}){
 const [networkId,setNetworkId]=useState(""),[members,setMembers]=useState<Member[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("Alle"),[invite,setInvite]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const token=getPortalSession();if(!token){setNotice("Bitte melden Sie sich erneut an.");return}try{const n=await portalRequest<{id:string}>(`/networks/public/${slug}`);setNetworkId(n.id);setMembers(await portalRequest<Member[]>(`/networks/${n.id}/memberships`,{token}))}catch(e){setNotice(e instanceof Error?e.message:"Mitglieder konnten nicht geladen werden.")}}
 useEffect(()=>{void load()},[slug]);
 const visible=useMemo(()=>members.filter(m=>(filter==="Alle"||labels[m.status]===filter)&&`${m.organization?.displayName||""} ${m.user?.firstName||""} ${m.user?.lastName||""} ${m.user?.email||""}`.toLowerCase().includes(query.toLowerCase())),[members,query,filter]);
 async function change(member:Member,status:Member["status"]){const token=getPortalSession();if(!token)return;try{const updated=await portalRequest<Member>(`/networks/${networkId}/memberships/${member.id}/status`,{token,body:{status}});setMembers(all=>all.map(m=>m.id===updated.id?{...m,...updated}:m));setNotice("Mitgliederstatus aktualisiert.")}catch(e){setNotice(e instanceof Error?e.message:"Änderung nicht möglich.")}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const token=getPortalSession();if(!token)return;const form=new FormData(event.currentTarget);setBusy(true);try{const result=await portalRequest<{registrationRequired?:boolean}>(`/networks/${networkId}/memberships/invite`,{token,body:{email:form.get("email"),role:form.get("role")}});setInvite(false);await load();setNotice(result.registrationRequired?"Ein persönlicher Registrierungslink wurde per E-Mail versendet.":"Das bestehende Konto wurde hinzugefügt.")}catch(e){setNotice(e instanceof Error?e.message:"Einladung nicht möglich.")}finally{setBusy(false)}}
 function exportCsv(){const rows=[["Unternehmen","Kontakt","E-Mail","Rolle","Status"],...visible.map(m=>[m.organization?.displayName||m.organization?.legalName||"",`${m.user?.firstName||""} ${m.user?.lastName||""}`.trim(),m.user?.email||"",m.role,labels[m.status]])],csv=rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(";")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv"}));a.download="netzwerkmitglieder.csv";a.click();URL.revokeObjectURL(a.href)}
 return <div className="adminNetworkWorkspace"><div className="networkMemberToolbar"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Unternehmen, Person oder E-Mail suchen"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Status filtern"><option>Alle</option>{Object.values(labels).map(l=><option key={l}>{l}</option>)}</select><button className="networkPrimary" onClick={()=>setInvite(true)}>＋ Mitglied einladen</button></div>
 <div className="networkMemberStats">{["Alle","Aktiv","Antrag","Deaktiviert"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}><strong>{x==="Alle"?members.length:members.filter(m=>labels[m.status]===x).length}</strong><span>{x}</span></button>)}</div>
 <section className="networkCard"><header><div><span>MITGLIEDSUNTERNEHMEN</span><h2>Mitglieder und Aufnahmeanträge</h2></div><button onClick={exportCsv} disabled={!visible.length}>CSV exportieren</button></header><div className="networkMemberTable">{visible.map(m=><article key={m.id}><span className="networkMemberAvatar">{(m.organization?.displayName||"UN").slice(0,2).toUpperCase()}</span><div><h3>{m.organization?.displayName||m.organization?.legalName||"Unternehmen"}</h3><p>{m.user?`${m.user.firstName} ${m.user.lastName} · ${m.user.email}`:"Kein Ansprechpartner"}</p><small>{m.role} · {new Date(m.updatedAt).toLocaleDateString("de-DE")}</small></div><b className={`networkMemberStatus ${m.status}`}>{labels[m.status]}</b><div className="networkMemberActions">{m.status==="pending"&&<><button onClick={()=>void change(m,"active")} title="Freigeben">✓</button><button onClick={()=>void change(m,"rejected")} title="Ablehnen">×</button></>}{m.status==="active"&&<button onClick={()=>void change(m,"suspended")} title="Deaktivieren">⊘</button>}{["suspended","rejected"].includes(m.status)&&<button onClick={()=>void change(m,"active")} title="Reaktivieren">↻</button>}</div></article>)}</div>{!visible.length&&<div className="networkEmpty"><b>Keine passenden Mitglieder</b><p>Ändern Sie Suche oder Filter.</p></div>}</section>
 {invite&&<div className="networkModalBackdrop"><section className="networkModal adminNetworkModal" role="dialog" aria-modal="true"><header><div><span>MITGLIEDERVERWALTUNG</span><h2>Persönlich einladen</h2></div><button onClick={()=>setInvite(false)}>×</button></header><form onSubmit={submit}><p>Der Link ordnet das neue Unternehmenskonto ausschließlich diesem geschlossenen Netzwerk zu.</p><label>Geschäftliche E-Mail<input name="email" type="email" required/></label><label>Rolle<select name="role"><option value="organization_admin">Unternehmensadministrator</option><option value="member">Mitglied</option><option value="moderator">Moderator</option></select></label><div className="adminNetworkDialogActions"><button type="button" onClick={()=>setInvite(false)}>Abbrechen</button><button className="networkPrimary" disabled={busy}>{busy?"Wird versendet …":"Einladung versenden"}</button></div></form></section></div>}{notice&&<div className="networkNotice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</div>;
}
