"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
type Dashboard={network:{id:string;name:string;status:string;trialEndsAt:string|null};members:{total:number;active:number;pending:number};content:{total:number;events:number;topics:number;tasks:number;documents:number};recent:Array<{id:string;type:string;title:string;updatedAt:string}>};
export function NetworkDashboardWorkspace({slug="unternehmerfreunde-nrw"}:{slug?:string}){
 const [data,setData]=useState<Dashboard|null>(null),[message,setMessage]=useState(""),base=`/portal/netzwerk/${slug}`;
 useEffect(()=>{const token=getPortalSession();if(!token){setMessage("Bitte melden Sie sich erneut an.");return}portalRequest<{id:string}>(`/networks/public/${slug}`).then(n=>portalRequest<Dashboard>(`/networks/${n.id}/dashboard`,{token})).then(setData).catch(e=>setMessage(e instanceof Error?e.message:"Die Netzwerkübersicht konnte nicht geladen werden."))},[slug]);
 if(!data)return <section className="networkCard networkLoading"><p>{message||"Netzwerkübersicht wird geladen …"}</p></section>;
 const trial=data.network.status==="trial",days=data.network.trialEndsAt?Math.max(0,Math.ceil((Date.parse(data.network.trialEndsAt)-Date.now())/86_400_000)):0;
 return <>{trial&&<section className="networkTrialBanner"><div><span>UNVERBINDLICHE TESTANSICHT</span><h2>Noch {days} Tage Oberfläche erkunden</h2><p>Speichern, Einladen, Veröffentlichen, Matching und Kommunikation werden erst nach der Buchung freigeschaltet.</p></div><Link href="mailto:service@b2b-matching.de?subject=Netzwerkportal%20aktivieren">Portal buchen</Link></section>}
 <section className="networkHero"><div><span>NETZWERKSTATUS</span><h2>{data.network.name}</h2><p>Geschlossener, mandantengetrennter Netzwerkbereich.</p></div><strong>{data.members.active}<small>aktive Unternehmen</small></strong></section>
 <section className="networkStats">{[[data.members.active,"Mitglieder"],[data.content.events,"Veranstaltungen"],[data.content.tasks,"Aufgaben"],[data.content.total,"Inhalte"]].map(([v,l])=><article key={String(l)}><strong>{v}</strong><span>{l}<small>Aktueller Stand</small></span></article>)}</section>
 <div className="networkDashboardGrid"><section className="networkCard"><header><div><span>AKTIVITÄTEN</span><h2>Was im Netzwerk passiert</h2></div><Link href={`${base}/auswertungen` as never}>Auswertung →</Link></header><div className="networkActivity">{data.recent.map(i=><p key={i.id}><b>{i.type.slice(0,2).toUpperCase()}</b><span><strong>{i.title}</strong><small>{new Date(i.updatedAt).toLocaleString("de-DE")}</small></span></p>)}{!data.recent.length&&<div className="networkEmpty"><b>Noch keine Aktivitäten</b><p>Im Demomodus bleiben die Daten unverändert.</p></div>}</div></section><aside><section className="networkCard"><header><div><span>SCHNELLZUGRIFF</span><h2>Netzwerkbereiche</h2></div></header><nav className="networkQuickLinks">{[["mitglieder","Mitglieder verwalten"],["veranstaltungen","Treffen planen"],["matching","Bedarfe & Matching"],["einstellungen","Netzwerk einrichten"]].map(([p,l])=><Link key={p} href={`${base}/${p}` as never}>{l}<b>→</b></Link>)}</nav></section></aside></div></>;
}
