"use client";

import {useEffect,useState,type ChangeEvent} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {useNetworkAccess} from "./network-shell";

type Profile={status:"draft"|"published";logoUrl:string|null;companyName:string;tagline:string;description:string;services:string;industries:string;street:string;postalCode:string;city:string;country:string;websiteUrl:string|null;contactName:string;contactPosition:string;contactEmail:string;contactPhone:string;updatedAt:string;publishedAt:string|null};
type Response={organization:{displayName:string;legalName:string;websiteUrl:string|null};profile:Profile|null;canEdit:boolean};

export function NetworkProfileWorkspace(){
 const access=useNetworkAccess(),networkId=access?.networkId||"",[data,setData]=useState<Response|null>(null),[logo,setLogo]=useState<string|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const token=getPortalSession();if(!token||!networkId)return;portalRequest<Response>(`/networks/${networkId}/profile`,{token}).then(value=>{setData(value);setLogo(value.profile?.logoUrl||null)}).catch(error=>setNotice(error instanceof Error?error.message:"Partnerseite konnte nicht geladen werden."))},[networkId]);
 function chooseLogo(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){setNotice("Bitte wählen Sie eine Bilddatei.");return}if(file.size>1_500_000){setNotice("Das Logo darf maximal 1,5 MB groß sein.");return}const reader=new FileReader();reader.onload=()=>setLogo(typeof reader.result==="string"?reader.result:null);reader.readAsDataURL(file)}
 async function save(formElement:HTMLFormElement,publish:boolean){const token=getPortalSession();if(!token||!networkId)return;const form=new FormData(formElement);setBusy(true);try{const profile=await portalRequest<Profile>(`/networks/${networkId}/profile`,{token,body:{companyName:form.get("companyName"),tagline:form.get("tagline"),description:form.get("description"),services:form.get("services"),industries:form.get("industries"),street:form.get("street"),postalCode:form.get("postalCode"),city:form.get("city"),country:form.get("country"),websiteUrl:form.get("websiteUrl"),contactName:form.get("contactName"),contactPosition:form.get("contactPosition"),contactEmail:form.get("contactEmail"),contactPhone:form.get("contactPhone"),logoUrl:logo,publish}});setData(current=>current?{...current,profile}:current);setNotice(publish?"Ihre Partnerseite ist jetzt im Netzwerk veröffentlicht.":"Entwurf gespeichert. Nur Sie und der Initiator können ihn sehen.")}catch(error){setNotice(error instanceof Error?error.message:"Partnerseite konnte nicht gespeichert werden.")}finally{setBusy(false)}}
 if(!data)return <p role="status">Partnerseite wird geladen …</p>;
 const p=data.profile;
 return <div className="networkProfileWorkspace">
  <section className="networkProfileGuide"><div><span>IHRE PARTNERSEITE</span><h2>In drei übersichtlichen Schritten sichtbar werden</h2><p>Diese Angaben sind ausschließlich für freigegebene Mitglieder dieses Netzwerks sichtbar. Sie erscheinen nicht öffentlich und nicht in anderen Netzwerken.</p></div><ol><li><b>1</b><span><strong>Unternehmen zeigen</strong><small>Logo, Name, Kurzbeschreibung und Adresse</small></span></li><li><b>2</b><span><strong>Leistungen erklären</strong><small>Was Sie anbieten und für wen Sie arbeiten</small></span></li><li><b>3</b><span><strong>Kontakt ermöglichen</strong><small>Persönlicher Ansprechpartner und direkte Kontaktdaten</small></span></li></ol></section>
  {!data.canEdit&&<div className="networkNotice">Nur der Unternehmensadministrator kann diese Partnerseite bearbeiten.</div>}
  <form onSubmit={event=>{event.preventDefault();void save(event.currentTarget,false)}}>
   <div className="networkProfileLayout"><div className="networkProfileForm">
    <section className="networkCard"><header><div><span>SCHRITT 1</span><h2>Unternehmen und Auftritt</h2><p>So erkennen andere Mitglieder Ihr Unternehmen auf den ersten Blick.</p></div></header><div className="networkProfileFields">
     <label className="networkLogoUpload"><span>Firmenlogo</span><div>{logo?<img src={logo} alt="Logo-Vorschau"/>:<b aria-hidden="true">＋</b>}<p><strong>Logo auswählen</strong><small>PNG, JPG oder WebP · maximal 1,5 MB</small></p></div><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={chooseLogo} disabled={!data.canEdit}/></label>
     <label>Unternehmensname<input name="companyName" required defaultValue={p?.companyName||data.organization.displayName} disabled={!data.canEdit}/></label><label>Kurzversprechen<input name="tagline" required maxLength={180} defaultValue={p?.tagline||""} placeholder="In einem Satz: Wofür steht Ihr Unternehmen?" disabled={!data.canEdit}/></label>
     <label className="wide">Persönliche Unternehmensbeschreibung<textarea name="description" required rows={6} maxLength={3000} defaultValue={p?.description||""} placeholder="Wer sind Sie, was zeichnet Sie aus und wie arbeiten Sie mit Partnern zusammen?" disabled={!data.canEdit}/></label>
     <label>Straße und Hausnummer<input name="street" required defaultValue={p?.street||""} disabled={!data.canEdit}/></label><label>Postleitzahl<input name="postalCode" required defaultValue={p?.postalCode||""} disabled={!data.canEdit}/></label><label>Ort<input name="city" required defaultValue={p?.city||""} disabled={!data.canEdit}/></label><label>Land<input name="country" required defaultValue={p?.country||"Deutschland"} disabled={!data.canEdit}/></label><label className="wide">Firmenhomepage<input name="websiteUrl" type="url" defaultValue={p?.websiteUrl||data.organization.websiteUrl||""} placeholder="https://www.ihr-unternehmen.de" disabled={!data.canEdit}/></label>
    </div></section>
    <section className="networkCard"><header><div><span>SCHRITT 2</span><h2>Leistungen und Erfahrung</h2><p>Beschreiben Sie verständlich, wobei andere Partner Sie ansprechen können.</p></div></header><div className="networkProfileFields"><label className="wide">Leistungen und Kompetenzen<textarea name="services" required rows={7} maxLength={2000} defaultValue={p?.services||""} placeholder="Welche Leistungen bieten Sie konkret an? Welche Probleme lösen Sie?" disabled={!data.canEdit}/></label><label className="wide">Branchen und Zielgruppen<input name="industries" maxLength={800} defaultValue={p?.industries||""} placeholder="z. B. Sport, Mittelstand, Handel, Industrie" disabled={!data.canEdit}/></label></div></section>
    <section className="networkCard"><header><div><span>SCHRITT 3</span><h2>Persönlicher Ansprechpartner</h2><p>Mitglieder können unmittelbar die richtige Person kontaktieren.</p></div></header><div className="networkProfileFields"><label>Name<input name="contactName" required defaultValue={p?.contactName||""} disabled={!data.canEdit}/></label><label>Position / Funktion<input name="contactPosition" required defaultValue={p?.contactPosition||""} disabled={!data.canEdit}/></label><label>E-Mail<input name="contactEmail" type="email" required defaultValue={p?.contactEmail||""} disabled={!data.canEdit}/></label><label>Telefon<input name="contactPhone" type="tel" required defaultValue={p?.contactPhone||""} disabled={!data.canEdit}/></label></div></section>
   </div><aside className="networkProfilePreview"><small>VORSCHAU IM PARTNERVERZEICHNIS</small><div className="networkProfileLogo">{logo?<img src={logo} alt=""/>:(p?.companyName||data.organization.displayName).slice(0,2).toUpperCase()}</div><span className={`networkMemberStatus ${p?.status==="published"?"active":"pending"}`}>{p?.status==="published"?"Veröffentlicht":"Entwurf"}</span><h2>{p?.companyName||data.organization.displayName}</h2><p>{p?.tagline||"Ihr Kurzversprechen erscheint hier."}</p><hr/><b>Was wir anbieten</b><p>{p?.services||"Beschreiben Sie Ihre wichtigsten Leistungen und Kompetenzen."}</p><small>Nur innerhalb dieses Netzwerks sichtbar</small></aside></div>
   {data.canEdit&&<div className="networkProfileActions"><button type="submit" disabled={busy}>Entwurf speichern</button><button className="networkPrimary" type="button" disabled={busy} onClick={event=>{const form=event.currentTarget.form;if(form?.reportValidity())void save(form,true)}}>{busy?"Wird gespeichert …":"Partnerseite veröffentlichen"}</button></div>}
  </form>{notice&&<div className="networkNotice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Meldung schließen">×</button></div>}
 </div>;
}
