"use client";
import {FormEvent,useEffect,useState} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {useNetworkAccess} from "./network-shell";

type Network={id:string;name:string;legalName:string|null;websiteUrl:string|null;logoUrl:string|null;primaryColor:string;secondaryColor:string;offeredModules:string[];settings:{admissionRules:string|null}};
type Dashboard={members:{active:number;pending:number};content:{total:number;events:number};recent:Array<{id:string;title:string;type:string;updatedAt:string}>};
type Catalog={modules:Array<{id:string;name:string;shortDescription:string;required?:boolean}>};

export function NetworkAdministrationWorkspace({mode,slug}:{mode:"settings"|"analytics";slug:string}){
 const access=useNetworkAccess();
 const[network,setNetwork]=useState<Network|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[offered,setOffered]=useState<string[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const token=getPortalSession();if(!token){setNotice("Bitte melden Sie sich erneut an.");return}try{const[n,c]=await Promise.all([portalRequest<Network>(`/networks/public/${slug}`,{token}),portalRequest<Catalog>("/networks/modules/catalog")]);setNetwork(n);setCatalog(c);setOffered(n.offeredModules.filter(module=>c.modules.some(item=>item.id===module)));setDashboard(await portalRequest<Dashboard>(`/networks/${n.id}/dashboard`,{token}))}catch(e){setNotice(e instanceof Error?e.message:"Netzwerkverwaltung konnte nicht geladen werden.")}}
 useEffect(()=>{void load()},[slug]);
 function toggle(id:string,required?:boolean){if(required)return;setOffered(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!network)return;const token=getPortalSession();if(!token)return;const f=new FormData(event.currentTarget);setBusy(true);try{await portalRequest(`/networks/${network.id}/settings`,{token,body:{name:f.get("name"),legalName:f.get("legalName"),websiteUrl:f.get("websiteUrl"),logoUrl:f.get("logoUrl"),primaryColor:f.get("primaryColor"),secondaryColor:f.get("secondaryColor"),admissionRules:f.get("admissionRules"),enabledModules:offered}});setNotice("Whitelabel und Modulangebot wurden gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Speichern nicht möglich.")}finally{setBusy(false)}}
 if(!network||!dashboard)return <section className="networkCard networkLoading"><p>{notice||"Netzwerkdaten werden geladen …"}</p></section>;
 if(mode==="analytics")return <div className="networkAnalytics"><section className="networkStats">{[[dashboard.members.active,"Aktive Nutzer"],[dashboard.members.pending,"Offene Aufnahmen"],[dashboard.content.events,"Veranstaltungen"],[dashboard.content.total,"Inhalte"]].map(([v,l])=><article key={String(l)}><strong>{v}</strong><span>{l}<small>Aktueller Datenstand</small></span></article>)}</section><section className="networkCard"><header><div><span>AKTIVITÄT</span><h2>Letzte Netzwerkaktivitäten</h2></div><button onClick={()=>window.print()}>Drucken</button></header><div className="networkActivity">{dashboard.recent.map(i=><p key={i.id}><b>{i.type.slice(0,2).toUpperCase()}</b><span><strong>{i.title}</strong><small>{new Date(i.updatedAt).toLocaleString("de-DE")}</small></span></p>)}{!dashboard.recent.length&&<div className="networkEmpty"><b>Noch keine Aktivitäten</b></div>}</div></section></div>;
 if(!access?.isInitiator)return <section className="networkCard networkLoading"><p>Nur der Initiator darf Modulangebot und Whitelabel verwalten.</p></section>;
 return <form className="networkSettingsForm" onSubmit={save}>
  <section className="networkCard"><header><div><span>KOSTENLOS INKLUSIVE</span><h2>Whitelabel und Stammdaten</h2></div></header><div className="networkSettingsFields"><label>Netzwerkname<input name="name" required defaultValue={network.name}/></label><label>Rechtlicher Name<input name="legalName" defaultValue={network.legalName||""}/></label><label>Website<input name="websiteUrl" type="url" defaultValue={network.websiteUrl||""}/></label><label>Logo-Adresse<input name="logoUrl" type="url" defaultValue={network.logoUrl||""}/></label><label>Primärfarbe<input name="primaryColor" type="color" defaultValue={network.primaryColor}/></label><label>Sekundärfarbe<input name="secondaryColor" type="color" defaultValue={network.secondaryColor}/></label><p className="full">Nur der Initiator kann Logo, Farben und Netzwerkauftritt verändern.</p></div></section>
  <section className="networkCard"><header><div><span>ANGEBOT DES NETZWERKS</span><h2>Verfügbare Module festlegen</h2></div></header><div className="networkModuleCatalog">{catalog?.modules.map(item=><label className={offered.includes(item.id)?"selected":""} key={item.id}><input type="checkbox" checked={offered.includes(item.id)} disabled={item.required} onChange={()=>toggle(item.id,item.required)}/><span><b>{item.name}{item.required?" · verpflichtend":""}</b><small>{item.shortDescription}</small></span></label>)}</div><p>Jeder Partner bucht und bezahlt anschließend nur seine persönliche Auswahl aus diesem Angebot.</p></section>
  <section className="networkCard"><header><div><span>REGELN</span><h2>Aufnahmebedingungen</h2></div></header><div className="networkSettingsFields"><label className="full">Netzwerkregeln<textarea name="admissionRules" rows={6} defaultValue={network.settings.admissionRules||""}/></label><p className="full">Selbstregistrierung und netzwerkübergreifendes Matching bleiben deaktiviert.</p></div></section>
  <div className="networkSettingsActions"><button className="networkPrimary" disabled={busy}>{busy?"Wird gespeichert …":"Whitelabel und Modulangebot speichern"}</button></div>{notice&&<div className="networkNotice">{notice}<button type="button" onClick={()=>setNotice("")}>×</button></div>}
 </form>;
}
