import Link from "next/link";
import type {ReactNode} from "react";

type Role="admin"|"unternehmen"|"dienstleister";
const menus={
 admin:[["Übersicht","/portal/admin"],["Freigaben","#freigaben"],["Mitglieder","#mitglieder"],["Bedarfe","#bedarfe"],["Matches","#matches"],["Kommunikation","#kommunikation"],["Abonnements","#abonnements"],["Prüfprotokoll","#protokoll"],["Einstellungen","#einstellungen"]],
 unternehmen:[["Übersicht","/portal/unternehmen"],["Meine Bedarfe","#bedarfe"],["Matches","#matches"],["Nachrichten","#nachrichten"],["Favoriten","#favoriten"],["Profilaufrufe","#aufrufe"],["Historie","#historie"],["Unternehmensprofil","#profil"],["Einstellungen","#einstellungen"]],
 dienstleister:[["Übersicht","/portal/dienstleister"],["Leistungsprofil","#profil"],["Geschäftschancen","#matches"],["Nachrichten","#nachrichten"],["Profilbesucher","#besucher"],["Favoriten","#favoriten"],["Abonnement","#abonnement"],["Verfügbarkeit","#verfuegbarkeit"],["Einstellungen","#einstellungen"]]
} as const;
const labels={admin:"Administration",unternehmen:"Unternehmer",dienstleister:"Dienstleister"};

export function PortalShell({role,title,intro,children,action}:{role:Role;title:string;intro:string;children:ReactNode;action?:ReactNode}){
 return <main className="portalApp"><aside className="portalSidebar"><Link href="/" className="portalBrand"><img src="/icons/b2b-matching-symbol.svg" alt=""/><span>B2B <b>Matching</b></span></Link><div className="portalRole"><small>ARBEITSBEREICH</small><strong>{labels[role]}</strong></div><nav aria-label={`${labels[role]} Navigation`}>{menus[role].map(([label,href],i)=><Link key={label} className={i===0?"active":""} href={href}><span aria-hidden="true">{["⌂","◇","◎","▤","↗","✉","☆","◫","⚙"][i]}</span>{label}{label==="Nachrichten"&&<b>3</b>}</Link>)}</nav><div className="portalHelp"><strong>Hilfe benötigt?</strong><p>Unser Support begleitet Sie persönlich.</p><a href="mailto:mail@media-online-innovations.group">Support kontaktieren</a></div></aside><section className="portalMain"><header className="portalTop"><details className="portalMobileMenu"><summary aria-label="Portalmenü öffnen">☰</summary><div>{menus[role].map(([label,href])=><Link key={label} href={href}>{label}</Link>)}</div></details><label className="portalSearch"><span>⌕</span><input aria-label="Portal durchsuchen" placeholder="Im Portal suchen …"/></label><div className="portalTopActions"><button aria-label="Benachrichtigungen">♢<b>4</b></button><div className="portalUser"><span>{role==="admin"?"MK":role==="unternehmen"?"BW":"NS"}</span><p><strong>{role==="admin"?"Martin Kelm":role==="unternehmen"?"Bergwerk GmbH":"Nordlicht Digital"}</strong><small>{labels[role]}</small></p></div></div></header><div className="portalContent"><div className="portalWelcome"><div><span>{role==="admin"?"PORTALSTEUERUNG":role==="unternehmen"?"IHR UNTERNEHMENSBEREICH":"IHR ANBIETERBEREICH"}</span><h1>{title}</h1><p>{intro}</p></div>{action}</div>{children}</div></section></main>
}

export function PortalStats({items}:{items:Array<[string,string,string?]>}){return <section className="portalStats" aria-label="Kennzahlen">{items.map(([value,label,note])=><article key={label}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>)}</section>}
export function PortalPanel({id,title,eyebrow,action,children,className=""}:{id?:string;title:string;eyebrow?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section id={id} className={`portalPanel ${className}`}><header><div>{eyebrow&&<span>{eyebrow}</span>}<h2>{title}</h2></div>{action}</header>{children}</section>}
export function Status({children,tone="teal"}:{children:ReactNode;tone?:"teal"|"amber"|"red"|"blue"|"gray"}){return <span className={`portalStatus ${tone}`}>{children}</span>}
