"use client";
import type {MouseEvent,ReactNode} from "react";
import {useEffect,useState} from "react";
import Link from "next/link";
import {NEEDS_KEY,PORTAL_UPDATE_EVENT,PROFILE_KEY,readNeeds,type StoredNeed} from "../lib/entrepreneur-state";
import {getPortalSession,portalRequest} from "../lib/portal-api";

type Role="admin"|"unternehmen"|"dienstleister";
type Dialog={title:string;kind:string;context?:string}|null;
const moduleCopy:Record<string,[string,string]>={
 "Freigaben":["Freigabezentrum","Prüfen Sie neue Profile, KI-Hinweise, Nachweise und bisherige Entscheidungen."],
 "Mitglieder":["Mitgliederverwaltung","Suchen, filtern, freigeben, sperren und Rollen verwalten."],
 "Bedarfe":["Bedarfsverwaltung","Alle aktiven, pausierten und archivierten Bedarfe zentral verwalten."],
 "Matches":["Matching-Zentrale","Passungen prüfen, neu berechnen, freigeben oder dokumentiert ablehnen."],
 "Kommunikation":["Kommunikationsübersicht","Unterhaltungen und gemeldete Inhalte nachvollziehen."],
 "Abonnements":["Abonnements","Tarife, Zahlungsstatus und Laufzeiten verwalten."],
 "Prüfprotokoll":["Prüfprotokoll","Lückenlose Historie administrativer und automatisierter Prüfungen."],
 "Einstellungen":["Einstellungen","Konto, Benachrichtigungen, Datenschutz und Sicherheit konfigurieren."],
 "Meine Bedarfe":["Meine Bedarfe","Bedarfe bearbeiten, pausieren, archivieren und ihre Reichweite prüfen."],
 "Nachrichten":["Nachrichten","Gespräche, Anhänge und Terminabstimmungen an einem Ort."],
 "Favoriten":["Favoriten","Gespeicherte Unternehmen und Dienstleister organisieren."],
 "Profilaufrufe":["Profilaufrufe","Entwicklung, Herkunft und freigegebene Besucher auswerten."],
 "Historie":["Aktivitätshistorie","Aufrufe, Entscheidungen und Statusänderungen nachvollziehen."],
 "Unternehmensprofil":["Unternehmensprofil","Stammdaten, Ansprechpartner, Branche und Sichtbarkeit bearbeiten."],
 "Leistungsprofil":["Leistungsprofil","Leistungen, Spezialisierungen, Referenzen und Landingpage pflegen."],
 "Geschäftschancen":["Geschäftschancen","Freigegebene Bedarfe nach Passung und Status bearbeiten."],
 "Profilbesucher":["Profilbesucher","Sehen Sie freigegebene Besucher und anonyme Aufrufzahlen."],
 "Abonnement":["Abonnement","Tarif, Rechnungen, Laufzeit und Zahlungsart verwalten."],
 "Verfügbarkeit":["Verfügbarkeit","Kapazität, Regionen, Projektstart und Arbeitsmodell einstellen."]
};

function fields(kind:string,role:Role,accountEmail=""){
 if(kind==="account"){
  return <div className="accountMenu"><div className="accountSummary"><span>{role==="admin"?"MK":role==="unternehmen"?"UN":"DL"}</span><div><b>{role==="admin"?"Martin Kelm":role==="unternehmen"?"Unternehmenskonto":"Dienstleisterkonto"}</b><small>Angemeldeter Arbeitsbereich · Sitzung geschützt</small></div></div><nav aria-label="Kontobereiche">{role==="unternehmen"&&<><Link href="/portal/unternehmen/profil"><span>▣</span><div><b>Unternehmensprofil</b><small>Stammdaten, Ansprechpartner und Sichtbarkeit bearbeiten</small></div><strong>→</strong></Link><Link href="/portal/unternehmen/team"><span>♙</span><div><b>Team und Zugänge</b><small>Mitglieder, Rollen und Berechtigungen verwalten</small></div><strong>→</strong></Link></>}<Link href={role==="unternehmen"?"/portal/unternehmen/einstellungen":role==="dienstleister"?"/portal/dienstleister":"/portal/admin"}><span>⚙</span><div><b>Einstellungen</b><small>Konto, Benachrichtigungen, Datenschutz und Sicherheit</small></div><strong>→</strong></Link><Link href={role==="unternehmen"?"/portal/unternehmen":role==="dienstleister"?"/portal/dienstleister":"/portal/admin"}><span>⌂</span><div><b>Zur Übersicht</b><small>Zurück in Ihren persönlichen Arbeitsbereich</small></div><strong>→</strong></Link></nav><button type="button" className="accountLogout">Abmelden</button></div>;
 }
 if(kind==="new-need")return <div className="needForm">
  <div className="needFormIntro"><span>Matching-Grundlage</span><h3>Je genauer Ihr Bedarf, desto relevanter die Empfehlungen.</h3><p>Ihre Unternehmensidentität bleibt verborgen. Dienstleister sehen nach Ihrer Freigabe nur das anonymisierte Anforderungsprofil.</p></div>
  <fieldset><legend>1. Bedarf und Einordnung</legend><div className="dialogSplit"><label>Titel des Bedarfs<input placeholder="z. B. Externe IT-Sicherheitsprüfung"/></label><label>Hauptkategorie<select defaultValue=""><option value="" disabled>Kategorie wählen</option><option>IT & Digitalisierung</option><option>Marketing & Kommunikation</option><option>Personal & Organisation</option><option>Beratung & Strategie</option><option>Finanzen & Recht</option><option>Produktion & Logistik</option></select></label></div><div className="dialogSplit"><label>Unterkategorie<input placeholder="z. B. Cybersecurity / Penetrationstest"/></label><label>Bedarfsart<select><option>Einmaliges Projekt</option><option>Laufende Betreuung</option><option>Interim-Unterstützung</option><option>Strategische Partnerschaft</option><option>Rahmenvertrag</option></select></label></div><label className="full">Kurzbeschreibung für die Match-Übersicht<textarea rows={3} maxLength={500} placeholder="Fassen Sie den Bedarf in 3–5 aussagekräftigen Sätzen zusammen."/></label></fieldset>
  <fieldset><legend>2. Anonymisierter Unternehmenskontext</legend><p className="fieldHint">Diese Angaben verbessern die Passung, ohne Ihren Unternehmensnamen offenzulegen.</p><div className="dialogSplit thirds"><label>Branche<input placeholder="z. B. Maschinenbau"/></label><label>Unternehmensgröße<select><option>1–9 Beschäftigte</option><option>10–49 Beschäftigte</option><option>50–249 Beschäftigte</option><option>250–999 Beschäftigte</option><option>1.000+ Beschäftigte</option></select></label><label>Unternehmenstyp<select><option>Mittelstand</option><option>Start-up</option><option>Konzern</option><option>Verband / Organisation</option><option>Öffentliches Unternehmen</option></select></label></div><div className="dialogSplit"><label>Standort / Region<input placeholder="Bundesland oder Region"/></label><label>Marktgebiet<select><option>Regional</option><option>Deutschlandweit</option><option>DACH</option><option>Europa</option><option>International</option></select></label></div><label className="full">Ausgangslage und Unternehmensumfeld<textarea rows={5} placeholder="Was ist der Hintergrund? Welche Systeme, Strukturen, Zielgruppen oder besonderen Rahmenbedingungen bestehen bereits?"/></label></fieldset>
  <fieldset><legend>3. Ziele und Leistungsumfang</legend><label className="full">Ziel und gewünschtes Ergebnis<textarea rows={5} placeholder="Welche konkrete Veränderung oder welches messbare Ergebnis soll erreicht werden?"/></label><label className="full">Erwarteter Leistungsumfang<textarea rows={7} placeholder="Welche Aufgaben, Arbeitspakete und Liefergegenstände soll der Dienstleister übernehmen? Was gehört ausdrücklich nicht zum Auftrag?"/></label><div className="dialogSplit"><label>Muss-Kriterien<textarea rows={5} placeholder="Je Zeile ein zwingendes Kriterium, z. B. ISO-27001-Erfahrung"/></label><label>Kann-Kriterien<textarea rows={5} placeholder="Je Zeile ein wünschenswertes Kriterium"/></label></div><label className="full">Erfolgskriterien / Abnahme<textarea rows={4} placeholder="Woran erkennen Sie, dass die Zusammenarbeit erfolgreich war?"/></label></fieldset>
  <fieldset><legend>4. Gesuchte Kompetenz</legend><label className="full">Matching-Keywords<div className="keywordInput"><input placeholder="Keyword eingeben, z. B. ISO 27001"/><button type="button">＋ Hinzufügen</button></div><small>Fachbegriffe, Methoden, Systeme, Technologien und Branchenwissen. Die KI ergänzt Synonyme und verwandte Begriffe.</small></label><div className="keywordExamples"><span>Strategieberatung</span><span>Prozessoptimierung</span><span>Microsoft 365</span><span>ISO 27001</span><span>B2B</span></div><div className="dialogSplit"><label>Erforderliche Fachkenntnisse<textarea rows={4} placeholder="Methoden, Technologien, Software, Fachgebiete …"/></label><label>Nachweise und Zertifizierungen<textarea rows={4} placeholder="Zertifikate, Zulassungen, Referenzen, Mitgliedschaften …"/></label></div><div className="dialogSplit"><label>Gewünschte Branchenerfahrung<input placeholder="Branchen oder vergleichbare Umfelder"/></label><label>Sprachen<input placeholder="z. B. Deutsch C1, Englisch B2"/></label></div></fieldset>
  <fieldset><legend>5. Projekt- und Vertragsrahmen</legend><div className="dialogSplit thirds"><label>Frühester Start<input type="date"/></label><label>Spätester Start<input type="date"/></label><label>Voraussichtliche Dauer<select><option>Noch offen</option><option>Bis 1 Monat</option><option>1–3 Monate</option><option>3–6 Monate</option><option>6–12 Monate</option><option>Dauerhaft</option></select></label></div><div className="dialogSplit thirds"><label>Arbeitsmodell<select><option>Flexibel</option><option>Vor Ort</option><option>Remote</option><option>Hybrid</option></select></label><label>Erforderliche Kapazität<input placeholder="z. B. 2 Tage/Woche"/></label><label>Entscheidung geplant<select><option>Innerhalb 2 Wochen</option><option>Innerhalb 4 Wochen</option><option>Innerhalb 3 Monaten</option><option>Noch offen</option></select></label></div><div className="dialogSplit"><label>Budgetrahmen (optional)<select><option>Nicht öffentlich anzeigen</option><option>Unter 5.000 €</option><option>5.000–15.000 €</option><option>15.000–50.000 €</option><option>50.000–100.000 €</option><option>Über 100.000 €</option><option>Nach Aufwand / offen</option></select></label><label>Bevorzugtes Vergütungsmodell<select><option>Offen</option><option>Festpreis</option><option>Tagessatz</option><option>Stundensatz</option><option>Monatliche Pauschale</option><option>Erfolgsabhängig</option></select></label></div></fieldset>
  <fieldset><legend>6. Matchinggewichtung und Sichtbarkeit</legend><p className="fieldHint">Bestimmen Sie, was für die prozentuale Bewertung besonders wichtig ist.</p><div className="weightGrid"><label><span>Fachkompetenz <b>sehr wichtig</b></span><input type="range" min="1" max="5" defaultValue="5"/></label><label><span>Branchenerfahrung <b>wichtig</b></span><input type="range" min="1" max="5" defaultValue="4"/></label><label><span>Region / Arbeitsmodell <b>mittel</b></span><input type="range" min="1" max="5" defaultValue="3"/></label><label><span>Verfügbarkeit <b>wichtig</b></span><input type="range" min="1" max="5" defaultValue="4"/></label><label><span>Budgetpassung <b>mittel</b></span><input type="range" min="1" max="5" defaultValue="3"/></label></div><div className="privacyChoices"><label><input type="checkbox" defaultChecked/> Unternehmensname und Kontaktdaten bis zu meiner Freigabe vollständig verbergen</label><label><input type="checkbox" defaultChecked/> Nur verifizierte und freigegebene Dienstleister berücksichtigen</label><label><input type="checkbox"/> Bedarf nach Veröffentlichung automatisch nach 90 Tagen deaktivieren</label></div></fieldset>
  <fieldset><legend>7. Ergänzende Unterlagen</legend><div className="uploadBox"><span>⇧</span><b>Dateien hier ablegen oder auswählen</b><small>Briefings, Anforderungskataloge oder technische Unterlagen · PDF, DOCX, XLSX · vertraulich</small><button type="button" className="portalSecondary">Datei auswählen</button></div><label className="full">Interne Notiz – für Dienstleister nicht sichtbar<textarea rows={3} placeholder="Eigene Hinweise für die spätere Prüfung und Freigabe"/></label></fieldset>
 </div>;
 if(kind==="ai")return <><div className="dialogAiHint">✦ Die KI formuliert aus Ihren Angaben einen strukturierten, anonymisierten Bedarf.</div><label className="full">Beschreiben Sie Ihre Situation<textarea rows={7} placeholder="Wir möchten … Uns fehlt derzeit … Wichtig ist uns …"/></label><label><input type="checkbox" defaultChecked/> Unternehmensidentität weiterhin verbergen</label></>;
 if(kind==="profile"&&role==="unternehmen")return <div className="companyProfileForm">
  <div className="profilePrivacyIntro"><span>Geschütztes Unternehmensprofil</span><h3>Vollständige Angaben schaffen Vertrauen und bessere Matches.</h3><p>Personen-, Firmen- und Kontaktdaten bleiben für Dienstleister verborgen, bis Sie einen konkreten Match ausdrücklich freigeben.</p></div>
  <fieldset><legend>1. Persönlicher Ansprechpartner</legend><div className="dialogSplit thirds"><label>Anrede<select defaultValue=""><option value="" disabled>Bitte wählen</option><option>Frau</option><option>Herr</option><option>Divers</option><option>Keine Angabe</option></select></label><label>Vorname<input autoComplete="given-name" placeholder="Vorname"/></label><label>Nachname<input autoComplete="family-name" placeholder="Nachname"/></label></div><div className="dialogSplit"><label>Position / Funktion<input placeholder="z. B. Geschäftsführung, Einkauf, IT-Leitung"/></label><label>Abteilung / Bereich<input placeholder="z. B. Einkauf, Marketing, Personal"/></label></div><div className="dialogSplit"><label>Geschäftliche E-Mail-Adresse<input type="email" autoComplete="email" placeholder="vorname.nachname@unternehmen.de"/></label><label>Geschäftliche Telefonnummer<input type="tel" autoComplete="tel" placeholder="+49 …"/></label></div><label className="full">Bevorzugter Kontaktweg<select><option>E-Mail</option><option>Telefon</option><option>Portalnachricht</option><option>Nach Terminvereinbarung</option></select></label></fieldset>
  <fieldset><legend>2. Berechtigung und Verantwortung</legend><div className="authorityBox"><strong>Dürfen Sie für dieses Unternehmen Bedarfe einstellen und Kooperationen anbahnen?</strong><label><input type="radio" name="authority" value="yes"/> Ja, ich bin entscheidungs- oder vertretungsbevollmächtigt.</label><label><input type="radio" name="authority" value="limited"/> Teilweise – eine weitere interne Freigabe ist erforderlich.</label><label><input type="radio" name="authority" value="no"/> Nein, ich erfasse Bedarfe im Auftrag einer berechtigten Person.</label></div><div className="dialogSplit"><label>Name der freigabeberechtigten Person<input placeholder="Nur falls eine weitere Freigabe erforderlich ist"/></label><label>Funktion der freigabeberechtigten Person<input placeholder="z. B. Geschäftsführung"/></label></div><label><input type="checkbox"/> Ich bestätige, dass ich zur geschäftlichen Registrierung für das angegebene Unternehmen berechtigt bin.</label><label><input type="checkbox"/> Ich bestätige, dass Bedarfe ausschließlich für geschäftliche Zwecke eingestellt werden.</label></fieldset>
  <fieldset><legend>3. Unternehmensstammdaten</legend><div className="dialogSplit"><label>Vollständige Firmierung<input autoComplete="organization" placeholder="Unternehmen inklusive Rechtsform"/></label><label>Rechtsform<select defaultValue=""><option value="" disabled>Rechtsform wählen</option><option>Einzelunternehmen</option><option>GbR</option><option>UG (haftungsbeschränkt)</option><option>GmbH</option><option>GmbH & Co. KG</option><option>KG</option><option>AG</option><option>e. V.</option><option>Sonstige</option></select></label></div><div className="dialogSplit"><label>Handelsname / Kurzbezeichnung<input placeholder="Optional"/></label><label>Gründungsjahr<input type="number" min="1800" max="2100" placeholder="JJJJ"/></label></div><div className="dialogSplit thirds"><label>Straße<input autoComplete="street-address" placeholder="Straße"/></label><label>Hausnummer<input placeholder="Nr."/></label><label>Adresszusatz<input placeholder="Optional"/></label></div><div className="dialogSplit thirds"><label>Postleitzahl<input autoComplete="postal-code" inputMode="numeric" placeholder="PLZ"/></label><label>Ort<input autoComplete="address-level2" placeholder="Ort"/></label><label>Land<select><option>Deutschland</option><option>Österreich</option><option>Schweiz</option><option>Anderes Land</option></select></label></div><div className="dialogSplit"><label>Website<input type="url" placeholder="https://www.unternehmen.de"/></label><label>Zentrale Telefonnummer<input type="tel" placeholder="+49 …"/></label></div><div className="dialogSplit"><label>Allgemeine E-Mail-Adresse<input type="email" placeholder="info@unternehmen.de"/></label><label>Weitere Standorte<input placeholder="Städte oder Regionen, optional"/></label></div></fieldset>
  <fieldset><legend>4. Unternehmensstruktur</legend><div className="dialogSplit thirds"><label>Hauptbranche<select defaultValue=""><option value="" disabled>Branche wählen</option><option>Industrie & Produktion</option><option>Handel & E-Commerce</option><option>IT & Telekommunikation</option><option>Finanzen & Versicherungen</option><option>Gesundheit & Soziales</option><option>Bau & Immobilien</option><option>Logistik & Mobilität</option><option>Medien & Kommunikation</option><option>Beratung & Dienstleistungen</option><option>Öffentlicher Sektor</option><option>Sonstige</option></select></label><label>Mitarbeitendenzahl<select><option>1–9</option><option>10–49</option><option>50–249</option><option>250–999</option><option>1.000–4.999</option><option>5.000+</option></select></label><label>Jahresumsatz (optional)<select><option>Keine Angabe</option><option>Bis 2 Mio. €</option><option>2–10 Mio. €</option><option>10–50 Mio. €</option><option>50–250 Mio. €</option><option>Über 250 Mio. €</option></select></label></div><div className="dialogSplit"><label>Geschäftsgebiet<select><option>Regional</option><option>Deutschlandweit</option><option>DACH</option><option>Europa</option><option>International</option></select></label><label>Kundenausrichtung<select><option>B2B</option><option>B2C</option><option>B2B und B2C</option><option>Öffentlicher Sektor</option></select></label></div><label className="full">Weitere Branchen und Tätigkeitsfelder<input placeholder="Mehrere Begriffe mit Komma trennen"/></label></fieldset>
  <fieldset><legend>5. Unternehmensbeschreibung</legend><label className="full">Kurzprofil<textarea rows={4} maxLength={600} placeholder="Beschreiben Sie Ihr Unternehmen kompakt: Tätigkeit, Markt, Zielgruppen und Besonderheiten."/></label><label className="full">Ausführliche Unternehmensbeschreibung<textarea rows={8} placeholder="Geschäftsmodell, Produkte oder Leistungen, Zielgruppen, Marktposition, Standorte, Strukturen, aktuelle Entwicklung und alles, was für passende Dienstleister relevant sein kann."/></label><div className="dialogSplit"><label>Produkte und Leistungen<textarea rows={5} placeholder="Wichtigste Angebote oder Leistungsbereiche"/></label><label>Zielgruppen und Märkte<textarea rows={5} placeholder="Kundengruppen, Branchen und Absatzmärkte"/></label></div><label className="full">Unternehmens-Keywords<div className="keywordInput"><input placeholder="z. B. Maschinenbau, Mittelstand, Export"/><button type="button">＋ Hinzufügen</button></div><small>Diese Begriffe helfen, Bedarfe und Dienstleister fachlich besser einzuordnen.</small></label></fieldset>
  <fieldset><legend>6. Beschaffungs- und Kooperationsprofil</legend><div className="dialogSplit"><label>Typischer Beschaffungsbedarf<textarea rows={5} placeholder="Welche externen Leistungen benötigt Ihr Unternehmen regelmäßig?"/></label><label>Bevorzugte Zusammenarbeit<textarea rows={5} placeholder="Projektarbeit, Rahmenverträge, langfristige Betreuung, Interim …"/></label></div><div className="dialogSplit"><label>Übliche Projektgröße<select><option>Noch offen</option><option>Bis 5.000 €</option><option>5.000–15.000 €</option><option>15.000–50.000 €</option><option>50.000–100.000 €</option><option>Über 100.000 €</option></select></label><label>Bevorzugtes Arbeitsmodell<select><option>Flexibel</option><option>Vor Ort</option><option>Remote</option><option>Hybrid</option></select></label></div><label className="full">Übergeordnete Anforderungen an Dienstleister<textarea rows={4} placeholder="z. B. Zertifizierungen, Datenschutz, Nachhaltigkeit, Reaktionszeiten, Sprachkenntnisse"/></label></fieldset>
  <fieldset><legend>7. Kontostatus und optionale Nachweise</legend><div className="verificationGrid single"><div className="verifiedAccount"><strong aria-hidden="true">✓</strong><span><b>E-Mail-Adresse bestätigt</b><small>{accountEmail||"Die geschäftliche E-Mail-Adresse wurde bereits bei der Registrierung bestätigt."}</small></span></div></div><div className="uploadBox"><span>⇧</span><b>Optionalen Unternehmensnachweis hochladen</b><small>z. B. Gewerbenachweis oder Handelsregisterauszug · nicht öffentlich sichtbar</small><button type="button" className="portalSecondary">Datei auswählen</button></div></fieldset>
  <fieldset><legend>8. Sichtbarkeit und Datenschutz</legend><div className="privacyChoices"><label><input type="checkbox" defaultChecked/> Unternehmens- und Kontaktdaten vor einer Match-Freigabe vollständig verbergen</label><label><input type="checkbox" defaultChecked/> Nach Freigabe Firmenname, Beschreibung, Website und geschäftliche Kontaktdaten anzeigen</label><label><input type="checkbox"/> Ansprechpartner bereits im freigegebenen Unternehmensprofil namentlich anzeigen</label><label><input type="checkbox"/> Über passende Dienstleister und neue Matchings per E-Mail informieren</label></div><p className="fieldHint">Ihre Einstellungen können später pro Bedarf und pro Dienstleister nochmals individuell entschieden werden.</p></fieldset>
 </div>;
 if(kind==="profile")return <><div className="dialogSplit"><label>Unternehmensname<input placeholder="Vollständige Firmierung"/></label><label>Branche<input placeholder="Hauptbranche"/></label></div><label className="full">Leistungsversprechen<textarea rows={5} placeholder="Positionierung und Nutzenversprechen des Dienstleisters"/></label><div className="dialogSplit"><label>Region<input placeholder="Einsatzgebiet"/></label><label>Website<input type="url" placeholder="https://"/></label></div></>;
 if(kind==="member")return <><div className="dialogSplit"><label>Unternehmen<input placeholder="Firmenname"/></label><label>Rolle<select><option>Unternehmer</option><option>Dienstleister</option><option>Administrator</option></select></label></div><div className="dialogSplit"><label>Ansprechpartner<input placeholder="Vor- und Nachname"/></label><label>E-Mail<input type="email" placeholder="name@unternehmen.de"/></label></div><label><input type="checkbox" defaultChecked/> Einladungs-E-Mail versenden</label></>;
 if(kind==="message")return <><div className="dialogMessage"><b>Bergwerk GmbH</b><p>Vielen Dank für Ihr Interesse. Wir würden gern die nächsten Schritte abstimmen.</p><small>Heute, 09:42 Uhr</small></div><label className="full">Nachricht<textarea rows={5} placeholder="Ihre Nachricht …"/></label><div className="dialogSplit"><button type="button" className="portalSecondary">＋ Datei anhängen</button><button type="button" className="portalSecondary">Termin vorschlagen</button></div></>;
 if(kind==="review")return <><div className="reviewSummary"><span>91%</span><div><b>Automatische Qualitätsbewertung</b><p>Unternehmensdaten plausibel · Leistungstexte vollständig · ein Nachweis offen</p></div></div><label>Prüfentscheidung<select><option>Profil freigeben</option><option>Rückfrage senden</option><option>Zurückstellen</option><option>Ablehnen</option></select></label><label className="full">Interne Notiz<textarea rows={4} placeholder="Entscheidung dokumentieren …"/></label></>;
 if(kind==="search")return <><label className="full">Portal durchsuchen<input autoFocus placeholder="Unternehmen, Bedarf, Dienstleistung oder Nachricht …"/></label><div className="searchEmpty">Noch keine durchsuchbaren Inhalte vorhanden.</div></>;
 if(kind==="Geschäftschancen")return <div className="needPreview"><div className="anonymousBanner"><span>◉</span><div><b>Anonymisiertes Unternehmen</b><p>Identität und Kontaktdaten werden erst nach Freigabe sichtbar.</p></div><strong>0 %</strong></div><section><span>BEDARF</span><h3>Noch keine freigegebene Geschäftschance</h3><p>Sobald ein suchendes Unternehmen einen Match für Sie freigibt, erscheint hier das vollständige anonymisierte Anforderungsprofil.</p></section><div className="previewGrid"><article><small>Unternehmenskontext</small><b>Branche, Größe, Region, Marktgebiet</b></article><article><small>Projektumfang</small><b>Ziele, Leistungen und Ergebnisse</b></article><article><small>Anforderungen</small><b>Muss-/Kann-Kriterien und Nachweise</b></article><article><small>Rahmenbedingungen</small><b>Start, Dauer, Modell und Budget</b></article></div><section><span>MATCHING-TRANSPARENZ</span><h4>So wird die Passung erklärt</h4><div className="matchingFactors"><p><b>Fachkompetenz</b><i/><small>Keine Daten</small></p><p><b>Branchenerfahrung</b><i/><small>Keine Daten</small></p><p><b>Verfügbarkeit</b><i/><small>Keine Daten</small></p><p><b>Region & Arbeitsmodell</b><i/><small>Keine Daten</small></p></div></section></div>;
 if(kind==="provider-preview")return <div className="providerPreview"><div className="providerPreviewHero"><span>DL</span><div><small>GEPRÜFTES DIENSTLEISTERPROFIL</small><h3>Noch kein Dienstleister ausgewählt</h3><p>Hier erscheinen Positionierung, Leistungen und verifizierte Unternehmensangaben.</p></div><strong>—<small>%</small></strong></div><div className="providerPreviewNav"><button type="button" className="active">Übersicht</button><button type="button">Leistungen</button><button type="button">Referenzen</button><button type="button">Nachweise</button><button type="button">Matchanalyse</button></div><section><span>POSITIONIERUNG</span><h4>Leistungsversprechen und Unternehmensbeschreibung</h4><p>Ausführliche Informationen zur Spezialisierung, Arbeitsweise, Zielgruppe und Erfahrung des Dienstleisters.</p></section><div className="previewGrid"><article><small>Unternehmensdaten</small><b>Firmierung, Standort, Größe und Gründungsjahr</b></article><article><small>Leistungsschwerpunkte</small><b>Kategorien, Methoden, Technologien und Keywords</b></article><article><small>Erfahrung</small><b>Branchen, Referenzen und vergleichbare Projekte</b></article><article><small>Zusammenarbeit</small><b>Region, Arbeitsmodell, Kapazität und Verfügbarkeit</b></article></div><section><span>VERTRAUEN & QUALITÄT</span><div className="trustChecklist"><p><b>✓</b><span>Profil durch Portaladministration freigegeben</span></p><p><b>○</b><span>Nachweise und Zertifizierungen werden hier angezeigt</span></p><p><b>○</b><span>Referenzen werden strukturiert und nachvollziehbar dargestellt</span></p></div></section><section><span>WARUM DIESER MATCH?</span><h4>Transparente Bewertung je Kriterium</h4><div className="matchingFactors"><p><b>Fachkompetenz</b><i/><small>Keine Daten</small></p><p><b>Muss-Kriterien</b><i/><small>Keine Daten</small></p><p><b>Branchenerfahrung</b><i/><small>Keine Daten</small></p><p><b>Verfügbarkeit</b><i/><small>Keine Daten</small></p></div></section><div className="providerDecisionBar"><button type="button" className="portalReject">Ablehnen</button><button type="button" className="portalSecondary">☆ Favorisieren</button><button type="button" className="portalPrimary">Bedarf für Dienstleister freigeben</button></div></div>;
 return <><p className="dialogIntro">{moduleCopy[kind]?.[1]||"Öffnen Sie Details, bearbeiten Sie den Status und dokumentieren Sie den nächsten Schritt."}</p><div className="dialogFeatureGrid"><button type="button">Übersicht anzeigen</button><button type="button">Filtern und suchen</button><button type="button">Aktivität exportieren</button><button type="button">Einstellungen öffnen</button></div></>;
}

export function PortalInteractions({role,children}:{role:Role;children:ReactNode}){
 const [dialog,setDialog]=useState<Dialog>(null);const [toast,setToast]=useState("");const [accountEmail,setAccountEmail]=useState("");
 useEffect(()=>{
  const token=getPortalSession();if(!token)return;
  portalRequest<{email:string}>("/auth/session/check",{method:"POST",token}).then(session=>setAccountEmail(session.email)).catch(()=>{});
 },[]);
 useEffect(()=>{
  if(!dialog)return;
  const frame=requestAnimationFrame(()=>{
   const dialogElement=document.querySelector<HTMLElement>(".companyDialog");
   if(dialog.kind==="profile"&&role==="unternehmen"){
    try{
     const saved=JSON.parse(localStorage.getItem(PROFILE_KEY)||"null") as {values?:Record<string,string|boolean>}|null;
     const controls=document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(".companyProfileForm input,.companyProfileForm textarea,.companyProfileForm select");
     controls.forEach((control,index)=>{const value=saved?.values?.[`field-${index}`];if(typeof value==="boolean"&&control instanceof HTMLInputElement)control.checked=value;else if(typeof value==="string")control.value=value});
    }catch{}
   }
   if(dialog.kind==="profile"&&dialog.context&&dialogElement){
    const section=dialogElement.querySelectorAll<HTMLElement>(".companyProfileForm fieldset")[Number(dialog.context)-1];
    if(!section)return;
    dialogElement.scrollTo({top:Math.max(0,section.offsetTop-96),behavior:"smooth"});
    section.setAttribute("tabindex","-1");
    section.focus({preventScroll:true});
   }
  });
  return ()=>cancelAnimationFrame(frame);
 },[dialog,role]);
 function open(title:string,kind:string,context?:string){setDialog({title,kind,context})}
 function click(e:MouseEvent<HTMLDivElement>){
  const target=e.target as HTMLElement;const link=target.closest("a");const button=target.closest("button");
  if(target.closest(".portalSearch")){open("Portal durchsuchen","search");return}
  if(link){const href=link.getAttribute("href")||"";if(href.startsWith("#")){const label=(link.textContent||"").trim().replace(/\d+$/,"");const targetEl=document.querySelector(href);if(targetEl){targetEl.scrollIntoView({behavior:"smooth"});return}e.preventDefault();open(moduleCopy[label]?.[0]||label,label)}return}
  if(!button&&target.closest(".conversationRows article")){open("Nachricht und Terminabstimmung","message");return}
  if(!button&&target.closest(".compactPeople p")){open("Profil im Detail","profile-preview");return}
  if(!button&&target.closest(".activity p")){open("Aktivitätsdetails","Historie");return}
  if(!button)return;
  const text=(button.getAttribute("aria-label")||button.textContent||"").trim();
  if(button.closest(".portalDialog")){if(text.includes("Abmelden")){localStorage.removeItem("b2b-matching-session");sessionStorage.removeItem("b2b-matching-session");window.location.href="/anmelden";return}if(text.includes("Dialog schließen")||text.includes("Abbrechen"))return;if(text.includes("Nachweis")||text.includes("Datei auswählen")||text.includes("Datei anhängen"))setToast("Die Dateiauswahl wird mit dem sicheren Dokumentenspeicher verbunden.");else if(text.includes("Hinzufügen"))setToast("Das Keyword wird nach Eingabe zur Matchingliste ergänzt.");else if(text.includes("Ablehnen"))setToast("Der Match wurde abgelehnt und in der Historie dokumentiert.");else if(text.includes("Favorisieren"))setToast("Der Dienstleister wurde als Favorit gespeichert.");else if(text.includes("freigeben"))setToast("Der Bedarf wurde für diesen Dienstleister freigegeben.");else if(text.includes("Termin"))setToast("Die Terminabstimmung wurde geöffnet.");else if(button.getAttribute("type")==="button")setToast(`„${text}“ wurde geöffnet.`);return}
  if(button.closest(".workspaceTabs")){setToast(`Ansicht „${text.replace(/\d+/g,"").trim()}“ wurde ausgewählt.`);return}
  const profileSectionButton=button.closest(".profileSectionGrid button") as HTMLButtonElement|null;
  if(profileSectionButton){
   const sectionButtons=Array.from(profileSectionButton.parentElement?.querySelectorAll("button")||[]);
   return open("Unternehmensprofil bearbeiten","profile",String(sectionButtons.indexOf(profileSectionButton)+1));
  }
  if(button.closest(".portalUser"))return open("Mein Konto","account");
  if(text.includes("Benachrichtig"))return open("Benachrichtigungen","notifications");
  if(text.includes("Neuen Bedarf")||text.includes("Ersten Bedarf"))return open("Neuen Bedarf erstellen","new-need");
  if(text.includes("KI erstellen")||text.includes("Bedarf mit KI"))return open("KI-Bedarfsassistent","ai");
  if(text.includes("Mitglied anlegen")||text.includes("Mitglied einladen")||text.includes("Teammitglied"))return open("Teammitglied einladen","member");
  if(text.includes("Leistungsseite")||text.includes("Profil vervollständigen")||text.includes("Unternehmensprofil"))return open(role==="dienstleister"?"Leistungsprofil bearbeiten":"Unternehmensprofil bearbeiten","profile");
  if(text.includes("Prüfen")||text.includes("bearbeiten")||text.includes("Prüfzentrum"))return open(text.includes("Profil")?"Dienstleisterprofil prüfen":"Profilprüfung","review");
  if(text.includes("Chance ansehen")||text.includes("Geschäftschance ansehen"))return open("Anonymisiertes Anforderungsprofil","Geschäftschancen");
  if(text.includes("Dienstleisterprofil"))return open("Dienstleisterprofil prüfen","provider-preview");
  if(text.includes("Vorschau"))return open("Öffentliche Profilvorschau","profile-preview");
  if(text.includes("Abonnement")||text.includes("Tarife"))return open("Tarife und Abonnement","Abonnement");
  if(text.includes("Ablehnen")){setToast("Match wurde abgelehnt und in der Historie dokumentiert.");return}
  if(text.includes("entfernen")){setToast("Favorit wurde entfernt.");return}
  if(text.includes("Alle Bedarfe"))return open("Alle Bedarfe","Meine Bedarfe");
  if(text.includes("Matching")||text.includes("Chancen"))return open(text.replace("→",""),role==="dienstleister"?"Geschäftschancen":"Matches");
  if(text==="Jetzt bearbeiten")return open("Offene Profilprüfungen","review");
  open(text||"Details","generic");
 }
 function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();
  const controls=Array.from(e.currentTarget.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>("input,textarea,select")).filter(control=>control.type!=="range");
  const values:Record<string,string|boolean>={};
  controls.forEach((control,index)=>values[`field-${index}`]=control instanceof HTMLInputElement&&(control.type==="checkbox"||control.type==="radio")?control.checked:control.value);
  if(dialog?.kind==="profile"&&role==="unternehmen"){
   localStorage.setItem(PROFILE_KEY,JSON.stringify({values,updatedAt:new Date().toISOString()}));
   window.dispatchEvent(new Event(PORTAL_UPDATE_EVENT));
   setToast("Unternehmensprofil gespeichert. Der Profilfortschritt wurde aktualisiert.");
  }else if(dialog?.kind==="new-need"||dialog?.kind==="ai"){
   const title=(controls.find(control=>control instanceof HTMLInputElement&&control.type==="text")?.value||"Neuer geschäftlicher Bedarf").trim();
   const category=(controls.find(control=>control instanceof HTMLSelectElement)?.value||"Noch nicht eingeordnet").trim();
   const summary=(controls.find(control=>control instanceof HTMLTextAreaElement)?.value||"").trim();
   const need:StoredNeed={id:crypto.randomUUID(),title,category,summary,status:"Entwurf",updatedAt:new Date().toISOString(),values};
   localStorage.setItem(NEEDS_KEY,JSON.stringify([need,...readNeeds()]));
   window.dispatchEvent(new Event(PORTAL_UPDATE_EVENT));
   setToast(dialog.kind==="ai"?"KI-Entwurf wurde erstellt und als Bedarf gespeichert.":"Bedarf wurde als Entwurf gespeichert.");
  }else setToast("Änderungen wurden gespeichert.");
  setDialog(null);
 }
 return <div onClick={click}>{children}{dialog&&<div className="portalDialogBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section className={`portalDialog ${dialog.kind==="new-need"?"needDialog":dialog.kind==="profile"&&role==="unternehmen"?"companyDialog":dialog.kind==="account"?"accountDialog":""}`} role="dialog" aria-modal="true" aria-labelledby="portal-dialog-title"><header><div><span>{role.toUpperCase()}</span><h2 id="portal-dialog-title">{dialog.title}</h2></div><button type="button" onClick={()=>setDialog(null)} aria-label="Dialog schließen">×</button></header><form onSubmit={submit}>{fields(dialog.kind,role,accountEmail)}{dialog.kind!=="account"&&<div className="portalDialogActions"><button type="button" className="portalSecondary" onClick={()=>setDialog(null)}>Abbrechen</button><button type="submit" className="portalPrimary">{dialog.kind==="ai"?"Entwurf generieren":dialog.kind==="message"?"Nachricht senden":"Speichern und fortfahren"}</button></div>}</form></section></div>}{toast&&<div className="portalToast" role="status"><span>✓</span>{toast}<button onClick={()=>setToast("")} aria-label="Meldung schließen">×</button></div>}</div>
}
