"use client";
import type {MouseEvent,ReactNode} from "react";
import {useState} from "react";

type Role="admin"|"unternehmen"|"dienstleister";
type Dialog={title:string;kind:string;context?:string}|null;
const moduleCopy:Record<string,[string,string]>={
 "Freigaben":["Freigabezentrum","Prüfen Sie neue Profile, KI-Hinweise, Nachweise und bisherige Entscheidungen."],
 "Mitglieder":["Mitgliederverwaltung","Suchen, filtern, freigeben, sperren und Rollen verwalten."],
 "Bedarfe":["Bedarfsverwaltung","Alle aktiven, pausierten und archivierten Bedarfe zentral verwalten."],
 "Matches":["Matching-Zentrale","Passungen prüfen, neu berechnen, freigeben oder dokumentiert ablehnen."],
 "Kommunikation":["Kommunikationsübersicht","Unterhaltungen und gemeldete Inhalte nachvollziehen."],
 "Abonnements":["Abonnements","Tarife, Zahlungsstatus und Laufzeiten verwalten."],
 "Prüfprotokoll":["Prüfprotokoll","Lückenlose Historie administrativer und automatisierter Prüfungen."],
 "Einstellungen":["Einstellungen","Konto, Benachrichtigungen, Datenschutz und Sicherheit konfigurieren."],
 "Meine Bedarfe":["Meine Bedarfe","Bedarfe bearbeiten, pausieren, archivieren und ihre Reichweite prüfen."],
 "Nachrichten":["Nachrichten","Gespräche, Anhänge und Terminabstimmungen an einem Ort."],
 "Favoriten":["Favoriten","Gespeicherte Unternehmen und Dienstleister organisieren."],
 "Profilaufrufe":["Profilaufrufe","Entwicklung, Herkunft und freigegebene Besucher auswerten."],
 "Historie":["Aktivitätshistorie","Aufrufe, Entscheidungen und Statusänderungen nachvollziehen."],
 "Unternehmensprofil":["Unternehmensprofil","Stammdaten, Ansprechpartner, Branche und Sichtbarkeit bearbeiten."],
 "Leistungsprofil":["Leistungsprofil","Leistungen, Spezialisierungen, Referenzen und Landingpage pflegen."],
 "Geschäftschancen":["Geschäftschancen","Freigegebene Bedarfe nach Passung und Status bearbeiten."],
 "Profilbesucher":["Profilbesucher","Sehen Sie freigegebene Besucher und anonyme Aufrufzahlen."],
 "Abonnement":["Abonnement","Tarif, Rechnungen, Laufzeit und Zahlungsart verwalten."],
 "Verfügbarkeit":["Verfügbarkeit","Kapazität, Regionen, Projektstart und Arbeitsmodell einstellen."]
};

function fields(kind:string,role:Role){
 if(kind==="new-need")return <div className="needForm">
  <div className="needFormIntro"><span>Matching-Grundlage</span><h3>Je genauer Ihr Bedarf, desto relevanter die Empfehlungen.</h3><p>Ihre Unternehmensidentität bleibt verborgen. Dienstleister sehen nach Ihrer Freigabe nur das anonymisierte Anforderungsprofil.</p></div>
  <fieldset><legend>1. Bedarf und Einordnung</legend><div className="dialogSplit"><label>Titel des Bedarfs<input placeholder="z. B. Externe IT-Sicherheitsprüfung"/></label><label>Hauptkategorie<select defaultValue=""><option value="" disabled>Kategorie wählen</option><option>IT & Digitalisierung</option><option>Marketing & Kommunikation</option><option>Personal & Organisation</option><option>Beratung & Strategie</option><option>Finanzen & Recht</option><option>Produktion & Logistik</option></select></label></div><div className="dialogSplit"><label>Unterkategorie<input placeholder="z. B. Cybersecurity / Penetrationstest"/></label><label>Bedarfsart<select><option>Einmaliges Projekt</option><option>Laufende Betreuung</option><option>Interim-Unterstützung</option><option>Strategische Partnerschaft</option><option>Rahmenvertrag</option></select></label></div><label className="full">Kurzbeschreibung für die Match-Übersicht<textarea rows={3} maxLength={500} placeholder="Fassen Sie den Bedarf in 3–5 aussagekräftigen Sätzen zusammen."/></label></fieldset>
  <fieldset><legend>2. Anonymisierter Unternehmenskontext</legend><p className="fieldHint">Diese Angaben verbessern die Passung, ohne Ihren Unternehmensnamen offenzulegen.</p><div className="dialogSplit thirds"><label>Branche<input placeholder="z. B. Maschinenbau"/></label><label>Unternehmensgröße<select><option>1–9 Beschäftigte</option><option>10–49 Beschäftigte</option><option>50–249 Beschäftigte</option><option>250–999 Beschäftigte</option><option>1.000+ Beschäftigte</option></select></label><label>Unternehmenstyp<select><option>Mittelstand</option><option>Start-up</option><option>Konzern</option><option>Verband / Organisation</option><option>Öffentliches Unternehmen</option></select></label></div><div className="dialogSplit"><label>Standort / Region<input placeholder="Bundesland oder Region"/></label><label>Marktgebiet<select><option>Regional</option><option>Deutschlandweit</option><option>DACH</option><option>Europa</option><option>International</option></select></label></div><label className="full">Ausgangslage und Unternehmensumfeld<textarea rows={5} placeholder="Was ist der Hintergrund? Welche Systeme, Strukturen, Zielgruppen oder besonderen Rahmenbedingungen bestehen bereits?"/></label></fieldset>
  <fieldset><legend>3. Ziele und Leistungsumfang</legend><label className="full">Ziel und gewünschtes Ergebnis<textarea rows={5} placeholder="Welche konkrete Veränderung oder welches messbare Ergebnis soll erreicht werden?"/></label><label className="full">Erwarteter Leistungsumfang<textarea rows={7} placeholder="Welche Aufgaben, Arbeitspakete und Liefergegenstände soll der Dienstleister übernehmen? Was gehört ausdrücklich nicht zum Auftrag?"/></label><div className="dialogSplit"><label>Muss-Kriterien<textarea rows={5} placeholder="Je Zeile ein zwingendes Kriterium, z. B. ISO-27001-Erfahrung"/></label><label>Kann-Kriterien<textarea rows={5} placeholder="Je Zeile ein wünschenswertes Kriterium"/></label></div><label className="full">Erfolgskriterien / Abnahme<textarea rows={4} placeholder="Woran erkennen Sie, dass die Zusammenarbeit erfolgreich war?"/></label></fieldset>
  <fieldset><legend>4. Gesuchte Kompetenz</legend><label className="full">Matching-Keywords<div className="keywordInput"><input placeholder="Keyword eingeben, z. B. ISO 27001"/><button type="button">＋ Hinzufügen</button></div><small>Fachbegriffe, Methoden, Systeme, Technologien und Branchenwissen. Die KI ergänzt Synonyme und verwandte Begriffe.</small></label><div className="keywordExamples"><span>Strategieberatung</span><span>Prozessoptimierung</span><span>Microsoft 365</span><span>ISO 27001</span><span>B2B</span></div><div className="dialogSplit"><label>Erforderliche Fachkenntnisse<textarea rows={4} placeholder="Methoden, Technologien, Software, Fachgebiete …"/></label><label>Nachweise und Zertifizierungen<textarea rows={4} placeholder="Zertifikate, Zulassungen, Referenzen, Mitgliedschaften …"/></label></div><div className="dialogSplit"><label>Gewünschte Branchenerfahrung<input placeholder="Branchen oder vergleichbare Umfelder"/></label><label>Sprachen<input placeholder="z. B. Deutsch C1, Englisch B2"/></label></div></fieldset>
  <fieldset><legend>5. Projekt- und Vertragsrahmen</legend><div className="dialogSplit thirds"><label>Frühester Start<input type="date"/></label><label>Spätester Start<input type="date"/></label><label>Voraussichtliche Dauer<select><option>Noch offen</option><option>Bis 1 Monat</option><option>1–3 Monate</option><option>3–6 Monate</option><option>6–12 Monate</option><option>Dauerhaft</option></select></label></div><div className="dialogSplit thirds"><label>Arbeitsmodell<select><option>Flexibel</option><option>Vor Ort</option><option>Remote</option><option>Hybrid</option></select></label><label>Erforderliche Kapazität<input placeholder="z. B. 2 Tage/Woche"/></label><label>Entscheidung geplant<select><option>Innerhalb 2 Wochen</option><option>Innerhalb 4 Wochen</option><option>Innerhalb 3 Monaten</option><option>Noch offen</option></select></label></div><div className="dialogSplit"><label>Budgetrahmen (optional)<select><option>Nicht öffentlich anzeigen</option><option>Unter 5.000 €</option><option>5.000–15.000 €</option><option>15.000–50.000 €</option><option>50.000–100.000 €</option><option>Über 100.000 €</option><option>Nach Aufwand / offen</option></select></label><label>Bevorzugtes Vergütungsmodell<select><option>Offen</option><option>Festpreis</option><option>Tagessatz</option><option>Stundensatz</option><option>Monatliche Pauschale</option><option>Erfolgsabhängig</option></select></label></div></fieldset>
  <fieldset><legend>6. Matchinggewichtung und Sichtbarkeit</legend><p className="fieldHint">Bestimmen Sie, was für die prozentuale Bewertung besonders wichtig ist.</p><div className="weightGrid"><label><span>Fachkompetenz <b>sehr wichtig</b></span><input type="range" min="1" max="5" defaultValue="5"/></label><label><span>Branchenerfahrung <b>wichtig</b></span><input type="range" min="1" max="5" defaultValue="4"/></label><label><span>Region / Arbeitsmodell <b>mittel</b></span><input type="range" min="1" max="5" defaultValue="3"/></label><label><span>Verfügbarkeit <b>wichtig</b></span><input type="range" min="1" max="5" defaultValue="4"/></label><label><span>Budgetpassung <b>mittel</b></span><input type="range" min="1" max="5" defaultValue="3"/></label></div><div className="privacyChoices"><label><input type="checkbox" defaultChecked/> Unternehmensname und Kontaktdaten bis zu meiner Freigabe vollständig verbergen</label><label><input type="checkbox" defaultChecked/> Nur verifizierte und freigegebene Dienstleister berücksichtigen</label><label><input type="checkbox"/> Bedarf nach Veröffentlichung automatisch nach 90 Tagen deaktivieren</label></div></fieldset>
  <fieldset><legend>7. Ergänzende Unterlagen</legend><div className="uploadBox"><span>⇧</span><b>Dateien hier ablegen oder auswählen</b><small>Briefings, Anforderungskataloge oder technische Unterlagen · PDF, DOCX, XLSX · vertraulich</small><button type="button" className="portalSecondary">Datei auswählen</button></div><label className="full">Interne Notiz – für Dienstleister nicht sichtbar<textarea rows={3} placeholder="Eigene Hinweise für die spätere Prüfung und Freigabe"/></label></fieldset>
 </div>;
 if(kind==="ai")return <><div className="dialogAiHint">✦ Die KI formuliert aus Ihren Angaben einen strukturierten, anonymisierten Bedarf.</div><label className="full">Beschreiben Sie Ihre Situation<textarea rows={7} placeholder="Wir möchten … Uns fehlt derzeit … Wichtig ist uns …"/></label><label><input type="checkbox" defaultChecked/> Unternehmensidentität weiterhin verbergen</label></>;
 if(kind==="profile")return <><div className="dialogSplit"><label>Unternehmensname<input defaultValue={role==="dienstleister"?"Nordlicht Digital GmbH":"Bergwerk GmbH"}/></label><label>Branche<input defaultValue={role==="dienstleister"?"IT & Cybersecurity":"Maschinenbau"}/></label></div><label className="full">{role==="dienstleister"?"Leistungsversprechen":"Unternehmensbeschreibung"}<textarea rows={5} defaultValue={role==="dienstleister"?"Wir schützen mittelständische Unternehmen durch verständliche und umsetzbare IT-Sicherheit.":"Innovativer Mittelständler mit deutschlandweiter Geschäftstätigkeit."}/></label><div className="dialogSplit"><label>Region<input defaultValue="Deutschlandweit"/></label><label>Website<input defaultValue="https://"/></label></div></>;
 if(kind==="member")return <><div className="dialogSplit"><label>Unternehmen<input placeholder="Firmenname"/></label><label>Rolle<select><option>Unternehmer</option><option>Dienstleister</option><option>Administrator</option></select></label></div><div className="dialogSplit"><label>Ansprechpartner<input placeholder="Vor- und Nachname"/></label><label>E-Mail<input type="email" placeholder="name@unternehmen.de"/></label></div><label><input type="checkbox" defaultChecked/> Einladungs-E-Mail versenden</label></>;
 if(kind==="message")return <><div className="dialogMessage"><b>Bergwerk GmbH</b><p>Vielen Dank für Ihr Interesse. Wir würden gern die nächsten Schritte abstimmen.</p><small>Heute, 09:42 Uhr</small></div><label className="full">Nachricht<textarea rows={5} placeholder="Ihre Nachricht …"/></label><div className="dialogSplit"><button type="button" className="portalSecondary">＋ Datei anhängen</button><button type="button" className="portalSecondary">Termin vorschlagen</button></div></>;
 if(kind==="review")return <><div className="reviewSummary"><span>91%</span><div><b>Automatische Qualitätsbewertung</b><p>Unternehmensdaten plausibel · Leistungstexte vollständig · ein Nachweis offen</p></div></div><label>Prüfentscheidung<select><option>Profil freigeben</option><option>Rückfrage senden</option><option>Zurückstellen</option><option>Ablehnen</option></select></label><label className="full">Interne Notiz<textarea rows={4} placeholder="Entscheidung dokumentieren …"/></label></>;
 if(kind==="search")return <><label className="full">Portal durchsuchen<input autoFocus placeholder="Unternehmen, Bedarf, Dienstleistung oder Nachricht …"/></label><div className="searchEmpty">Noch keine durchsuchbaren Inhalte vorhanden.</div></>;
 if(kind==="Geschäftschancen")return <div className="needPreview"><div className="anonymousBanner"><span>◉</span><div><b>Anonymisiertes Unternehmen</b><p>Identität und Kontaktdaten werden erst nach Freigabe sichtbar.</p></div><strong>0 %</strong></div><section><span>BEDARF</span><h3>Noch keine freigegebene Geschäftschance</h3><p>Sobald ein suchendes Unternehmen einen Match für Sie freigibt, erscheint hier das vollständige anonymisierte Anforderungsprofil.</p></section><div className="previewGrid"><article><small>Unternehmenskontext</small><b>Branche, Größe, Region, Marktgebiet</b></article><article><small>Projektumfang</small><b>Ziele, Leistungen und Ergebnisse</b></article><article><small>Anforderungen</small><b>Muss-/Kann-Kriterien und Nachweise</b></article><article><small>Rahmenbedingungen</small><b>Start, Dauer, Modell und Budget</b></article></div><section><span>MATCHING-TRANSPARENZ</span><h4>So wird die Passung erklärt</h4><div className="matchingFactors"><p><b>Fachkompetenz</b><i/><small>Keine Daten</small></p><p><b>Branchenerfahrung</b><i/><small>Keine Daten</small></p><p><b>Verfügbarkeit</b><i/><small>Keine Daten</small></p><p><b>Region & Arbeitsmodell</b><i/><small>Keine Daten</small></p></div></section></div>;
 return <><p className="dialogIntro">{moduleCopy[kind]?.[1]||"Öffnen Sie Details, bearbeiten Sie den Status und dokumentieren Sie den nächsten Schritt."}</p><div className="dialogFeatureGrid"><button type="button">Übersicht anzeigen</button><button type="button">Filtern und suchen</button><button type="button">Aktivität exportieren</button><button type="button">Einstellungen öffnen</button></div></>;
}

export function PortalInteractions({role,children}:{role:Role;children:ReactNode}){
 const [dialog,setDialog]=useState<Dialog>(null);const [toast,setToast]=useState("");
 function open(title:string,kind:string,context?:string){setDialog({title,kind,context})}
 function click(e:MouseEvent<HTMLDivElement>){
  const target=e.target as HTMLElement;const link=target.closest("a");const button=target.closest("button");
  if(target.closest(".portalSearch")){open("Portal durchsuchen","search");return}
  if(link){const href=link.getAttribute("href")||"";if(href.startsWith("#")){const label=(link.textContent||"").trim().replace(/\d+$/,"");const targetEl=document.querySelector(href);if(targetEl){targetEl.scrollIntoView({behavior:"smooth"});return}e.preventDefault();open(moduleCopy[label]?.[0]||label,label)}return}
  if(!button&&target.closest(".conversationRows article")){open("Nachricht und Terminabstimmung","message");return}
  if(!button&&target.closest(".compactPeople p")){open("Profil im Detail","profile-preview");return}
  if(!button&&target.closest(".activity p")){open("Aktivitätsdetails","Historie");return}
  if(!button||button.closest(".portalDialog"))return;
  const text=(button.getAttribute("aria-label")||button.textContent||"").trim();
  if(button.closest(".portalUser"))return open("Mein Konto","Einstellungen");
  if(text.includes("Benachrichtig"))return open("Benachrichtigungen","notifications");
  if(text.includes("Neuen Bedarf")||text.includes("Ersten Bedarf"))return open("Neuen Bedarf erstellen","new-need");
  if(text.includes("KI erstellen")||text.includes("Bedarf mit KI"))return open("KI-Bedarfsassistent","ai");
  if(text.includes("Mitglied anlegen")||text.includes("Mitglied einladen"))return open("Mitglied anlegen","member");
  if(text.includes("Leistungsseite")||text.includes("Profil vervollständigen")||text.includes("Unternehmensprofil"))return open(role==="dienstleister"?"Leistungsprofil bearbeiten":"Unternehmensprofil bearbeiten","profile");
  if(text.includes("Prüfen")||text.includes("bearbeiten")||text.includes("Prüfzentrum"))return open(text.includes("Profil")?"Dienstleisterprofil prüfen":"Profilprüfung","review");
  if(text.includes("Chance ansehen")||text.includes("Geschäftschance ansehen"))return open("Anonymisiertes Anforderungsprofil","Geschäftschancen");
  if(text.includes("Vorschau"))return open("Öffentliche Profilvorschau","profile-preview");
  if(text.includes("Abonnement")||text.includes("Tarife"))return open("Tarife und Abonnement","Abonnement");
  if(text.includes("Ablehnen")){setToast("Match wurde abgelehnt und in der Historie dokumentiert.");return}
  if(text.includes("entfernen")){setToast("Favorit wurde entfernt.");return}
  if(text.includes("Alle Bedarfe"))return open("Alle Bedarfe","Meine Bedarfe");
  if(text.includes("Matching")||text.includes("Chancen"))return open(text.replace("→",""),role==="dienstleister"?"Geschäftschancen":"Matches");
  if(text==="Jetzt bearbeiten")return open("Offene Profilprüfungen","review");
  open(text||"Details","generic");
 }
 function submit(e:React.FormEvent){e.preventDefault();setDialog(null);setToast(dialog?.kind==="ai"?"KI-Entwurf wurde erstellt und zur Prüfung vorgemerkt.":"Änderungen wurden in der Frontend-Demonstration übernommen.")}
 return <div onClick={click}>{children}{dialog&&<div className="portalDialogBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section className={`portalDialog ${dialog.kind==="new-need"?"needDialog":""}`} role="dialog" aria-modal="true" aria-labelledby="portal-dialog-title"><header><div><span>{role.toUpperCase()}</span><h2 id="portal-dialog-title">{dialog.title}</h2></div><button type="button" onClick={()=>setDialog(null)} aria-label="Dialog schließen">×</button></header><form onSubmit={submit}>{fields(dialog.kind,role)}<div className="portalDialogActions"><button type="button" className="portalSecondary" onClick={()=>setDialog(null)}>Abbrechen</button><button type="submit" className="portalPrimary">{dialog.kind==="ai"?"Entwurf generieren":dialog.kind==="message"?"Nachricht senden":"Speichern und fortfahren"}</button></div></form></section></div>}{toast&&<div className="portalToast" role="status"><span>✓</span>{toast}<button onClick={()=>setToast("")} aria-label="Meldung schließen">×</button></div>}</div>
}
