"use client";
import type {ChangeEvent,FormEvent,MouseEvent,ReactNode} from "react";
import {useEffect,useState} from "react";
import Link from "next/link";
import {PORTAL_UPDATE_EVENT,type StoredProfile} from "../lib/entrepreneur-state";
import {getPortalSession,portalRequest} from "../lib/portal-api";

type Role="admin"|"unternehmen"|"dienstleister";
type Dialog={title:string;kind:string;context?:string}|null;
const moduleCopy:Record<string,[string,string]>={
 "Freigaben":["Freigabezentrum","Prüfen Sie neue Profile, KI-Hinweise, Nachweise und bisherige Entscheidungen."],
 "Mitglieder":["Mitgliederverwaltung","Suchen, filtern, freigeben, sperren und Rollen verwalten."],
 "Bedarfe":["Bedarfsverwaltung","Alle aktiven, pausierten und archivierten Bedarfe zentral verwalten."],
 "Matches":["Matching-Zentrale","Passungen prüfen, neu berechnen, freigeben oder dokumentiert ablehnen."],
 "Kommunikation":["Kommunikationsübersicht","Unterhaltungen und gemeldete Inhalte nachvollziehen."],
 "Abonnements":["Abonnements","Tarife, Zahlungsstatus und Laufzeiten verwalten."],
 "Prüfprotokoll":["Prüfprotokoll","Lückenlose Historie administrativer und automatisierter Prüfungen."],
 "Einstellungen":["Einstellungen","Konto, Benachrichtigungen, Datenschutz und Sicherheit konfigurieren."],
 "Meine Bedarfe":["Meine Bedarfe","Bedarfe bearbeiten, pausieren, archivieren und ihre Reichweite prüfen."],
 "Nachrichten":["Nachrichten","Gespräche, Anhänge und Terminabstimmungen an einem Ort."],
 "Favoriten":["Favoriten","Gespeicherte Unternehmen und Dienstleister organisieren."],
 "Profilaufrufe":["Profilaufrufe","Entwicklung, Herkunft und freigegebene Besucher auswerten."],
 "Historie":["Aktivitätshistorie","Aufrufe, Entscheidungen und Statusänderungen nachvollziehen."],
 "Unternehmensprofil":["Unternehmensprofil","Stammdaten, Ansprechpartner, Branche und Sichtbarkeit bearbeiten."],
 "Leistungsprofil":["Leistungsprofil","Leistungen, Spezialisierungen, Referenzen und Landingpage pflegen."],
 "Geschäftschancen":["Geschäftschancen","Freigegebene Bedarfe nach Passung und Status bearbeiten."],
 "Profilbesucher":["Profilbesucher","Sehen Sie freigegebene Besucher und anonyme Aufrufzahlen."],
 "Abonnement":["Abonnement","Tarif, Rechnungen, Laufzeit und Zahlungsart verwalten."],
 "Verfügbarkeit":["Verfügbarkeit","Kapazität, Regionen, Projektstart und Arbeitsmodell einstellen."]
};

type NeedDraft={title:string;category:string;subcategory:string;needType:string;summary:string;industry:string;companySize:string;market:string;companyContext:string;goal:string;scope:string;must:string;nice:string;keywords:string;expertise:string;proofs:string;industryExperience:string;start:string;duration:string;workModel:string;capacity:string;budget:string};
const profileValue=(profile:StoredProfile|null,index:number)=>{const value=profile?.values?.[`field-${index}`];return typeof value==="string"?value:""};
const sizeLabel=(value:string)=>["1–9","10–49","50–249","250–999"].includes(value)?`${value} Beschäftigte`:value?"1.000+ Beschäftigte":"1–9 Beschäftigte";

function NeedCreationForm({profile}:{profile:StoredProfile|null}){
 const [draft,setDraft]=useState<NeedDraft>(()=>{
  const short=profileValue(profile,35),description=profileValue(profile,36),products=profileValue(profile,37),targets=profileValue(profile,38);
  const names=[profileValue(profile,15),profileValue(profile,17)].filter(Boolean);
  const companyContext=names.reduce((text,name)=>text.replaceAll(name,"[Unternehmensname verborgen]"),[short,description,products&&`Angebot: ${products}`,targets&&`Zielgruppen: ${targets}`].filter(Boolean).join("\n\n"));
  return {title:"",category:"",subcategory:"",needType:"Einmaliges Projekt",summary:"",industry:profileValue(profile,29),companySize:sizeLabel(profileValue(profile,30)),market:profileValue(profile,32)||"Regional",companyContext,goal:"",scope:"",must:"",nice:"",keywords:"",expertise:"",proofs:"",industryExperience:profileValue(profile,29),start:"",duration:"Noch offen",workModel:profileValue(profile,43)||"Flexibel",capacity:"",budget:profileValue(profile,42)||"Noch offen"};
 });
 const set=(key:keyof NeedDraft)=>(event:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setDraft(current=>({...current,[key]:event.target.value}));
 const aiContext=JSON.stringify({anonymizedCompany:{industry:draft.industry,size:draft.companySize,market:draft.market,context:draft.companyContext},need:{title:draft.title,category:draft.category,subcategory:draft.subcategory,type:draft.needType,summary:draft.summary,goal:draft.goal,scope:draft.scope,must:draft.must,nice:draft.nice,keywords:draft.keywords,expertise:draft.expertise,proofs:draft.proofs,industryExperience:draft.industryExperience,start:draft.start,duration:draft.duration,workModel:draft.workModel,capacity:draft.capacity,budget:draft.budget}});
 return <div className="guidedNeedBuilder"><div className="needBuilderMain"><div className="needFormIntro"><span>VORBEREITETER BEDARFSASSISTENT</span><h3>Ihr Unternehmenskontext ist bereits berücksichtigt.</h3><p>Ergänzen Sie nur die Angaben zu diesem konkreten Bedarf. Rechts sehen Sie jederzeit die spätere anonymisierte Dienstleisteransicht.</p></div>
  <section className="needBuilderSection"><header><span>01</span><div><h3>Worum geht es?</h3><p>Kurze Einordnung für Suche und Matching</p></div></header><div className="needBuilderFields"><div className="dialogSplit"><label>Titel des Bedarfs<input name="title" required value={draft.title} onChange={set("title")} placeholder="z. B. Animiertes Kampagnenvideo erstellen"/></label><label>Hauptkategorie<select name="category" required value={draft.category} onChange={set("category")}><option value="" disabled>Kategorie wählen</option><option>IT & Digitalisierung</option><option>Marketing & Kommunikation</option><option>Personal & Organisation</option><option>Beratung & Strategie</option><option>Finanzen & Recht</option><option>Produktion & Logistik</option></select></label></div><div className="dialogSplit"><label>Unterkategorie<input value={draft.subcategory} onChange={set("subcategory")} placeholder="z. B. Videoproduktion / Motion Design"/></label><label>Bedarfsart<select value={draft.needType} onChange={set("needType")}><option>Einmaliges Projekt</option><option>Laufende Betreuung</option><option>Interim-Unterstützung</option><option>Strategische Partnerschaft</option></select></label></div><label>Kurzbeschreibung<textarea name="summary" required rows={5} value={draft.summary} onChange={set("summary")} placeholder="Was wird benötigt und warum?"/></label></div></section>
  <section className="needBuilderSection profileContext"><header><span>02</span><div><h3>Aus Ihrem Unternehmensprofil übernommen</h3><p>Anonymisiert und für diesen Bedarf anpassbar</p></div></header><div className="needBuilderFields"><div className="contextNotice">✓ Vorbefüllt aus Ihrem Unternehmensprofil. Firmenname und Kontaktdaten werden nicht übernommen.</div><div className="dialogSplit thirds"><label>Branche<input value={draft.industry} onChange={set("industry")}/></label><label>Unternehmensgröße<select value={draft.companySize} onChange={set("companySize")}><option>1–9 Beschäftigte</option><option>10–49 Beschäftigte</option><option>50–249 Beschäftigte</option><option>250–999 Beschäftigte</option><option>1.000+ Beschäftigte</option></select></label><label>Marktgebiet<select value={draft.market} onChange={set("market")}><option>Regional</option><option>Deutschlandweit</option><option>DACH</option><option>Europa</option><option>International</option></select></label></div><label>Anonymisierter Unternehmenskontext<textarea rows={6} value={draft.companyContext} onChange={set("companyContext")} placeholder="Relevante Strukturen, Märkte und Rahmenbedingungen"/></label></div></section>
  <section className="needBuilderSection"><header><span>03</span><div><h3>Ziel und Leistungsumfang</h3><p>Was soll der Dienstleister konkret erreichen?</p></div></header><div className="needBuilderFields"><label>Ziel und gewünschtes Ergebnis<textarea required rows={5} value={draft.goal} onChange={set("goal")} placeholder="Welches Ergebnis soll erreicht werden?"/></label><label>Erwarteter Leistungsumfang<textarea required rows={7} value={draft.scope} onChange={set("scope")} placeholder="Aufgaben, Arbeitspakete und Liefergegenstände"/></label><div className="dialogSplit"><label>Muss-Kriterien<textarea required rows={5} value={draft.must} onChange={set("must")} placeholder="Je Zeile ein zwingendes Kriterium"/></label><label>Kann-Kriterien<textarea rows={5} value={draft.nice} onChange={set("nice")} placeholder="Je Zeile ein wünschenswertes Kriterium"/></label></div></div></section>
  <section className="needBuilderSection"><header><span>04</span><div><h3>Gesuchte Kompetenz</h3><p>Grundlage für die prozentuale Match-Bewertung</p></div></header><div className="needBuilderFields"><label>Matching-Keywords<input required value={draft.keywords} onChange={set("keywords")} placeholder="z. B. Motion Design, After Effects, B2B, Eventvideo"/></label><div className="dialogSplit"><label>Erforderliche Fachkenntnisse<textarea required rows={4} value={draft.expertise} onChange={set("expertise")}/></label><label>Nachweise und Referenzen<textarea rows={4} value={draft.proofs} onChange={set("proofs")}/></label></div><label>Gewünschte Branchenerfahrung<input value={draft.industryExperience} onChange={set("industryExperience")}/></label></div></section>
  <section className="needBuilderSection"><header><span>05</span><div><h3>Projekt- und Vertragsrahmen</h3><p>Nur die Rahmenbedingungen dieses Bedarfs</p></div></header><div className="needBuilderFields"><div className="dialogSplit thirds"><label>Frühester Start<input type="date" value={draft.start} onChange={set("start")}/></label><label>Dauer<select value={draft.duration} onChange={set("duration")}><option>Noch offen</option><option>Bis 1 Monat</option><option>1–3 Monate</option><option>3–6 Monate</option><option>Dauerhaft</option></select></label><label>Arbeitsmodell<select value={draft.workModel} onChange={set("workModel")}><option>Flexibel</option><option>Vor Ort</option><option>Remote</option><option>Hybrid</option></select></label></div><div className="dialogSplit"><label>Kapazität<input value={draft.capacity} onChange={set("capacity")} placeholder="z. B. 2 Tage pro Woche"/></label><label>Budgetrahmen<select value={draft.budget} onChange={set("budget")}><option>Noch offen</option><option>Bis 5.000 €</option><option>5.000–15.000 €</option><option>15.000–50.000 €</option><option>50.000–100.000 €</option><option>Über 100.000 €</option></select></label></div><input type="hidden" name="aiContext" value={aiContext}/></div></section>
 </div><aside className="needLivePreview"><div><span>LIVE-VORSCHAU</span><b>Ansicht für Dienstleister</b><small>Alle weißen Textflächen können Sie auch direkt hier bearbeiten.</small></div><div className="anonymousPreview"><span>◉</span><div><b>Anonymisiertes Unternehmen</b><small>{draft.industry||"Branche offen"} · {draft.companySize}</small></div></div><span className="status amber">Entwurf</span><input className="previewInlineTitle" aria-label="Titel in der Vorschau bearbeiten" value={draft.title} onChange={set("title")} placeholder="Titel Ihres Bedarfs"/><p className="previewCategory">{[draft.category,draft.subcategory].filter(Boolean).join(" · ")||"Kategorie noch offen"}</p><section><h3>Gesuchte Unterstützung</h3><textarea className="previewInlineText" aria-label="Kurzbeschreibung in der Vorschau bearbeiten" rows={5} value={draft.summary} onChange={set("summary")} placeholder="Ihre Kurzbeschreibung erscheint hier."/></section><section><h3>Ziel und Umfang</h3><textarea className="previewInlineText" aria-label="Ziel in der Vorschau bearbeiten" rows={4} value={draft.goal} onChange={set("goal")} placeholder="Ziel noch ergänzen"/><textarea className="previewInlineText" aria-label="Leistungsumfang in der Vorschau bearbeiten" rows={5} value={draft.scope} onChange={set("scope")} placeholder="Leistungsumfang noch ergänzen"/></section><section><h3>Wichtige Kriterien</h3><textarea className="previewInlineText" aria-label="Muss-Kriterien in der Vorschau bearbeiten" rows={4} value={draft.must} onChange={set("must")} placeholder="Muss-Kriterien noch ergänzen"/></section><dl><div><dt>Start</dt><dd>{draft.start||"Flexibel"}</dd></div><div><dt>Arbeitsmodell</dt><dd>{draft.workModel}</dd></div><div><dt>Budget</dt><dd>{draft.budget}</dd></div><div><dt>Marktgebiet</dt><dd>{draft.market}</dd></div></dl><div className="previewPrivacyNote">Unternehmens- und Kontaktdaten werden erst nach Ihrer ausdrücklichen Match-Freigabe sichtbar.</div></aside></div>;
}

function fields(kind:string,role:Role,accountEmail="",profile:StoredProfile|null=null){
 if(kind==="account"){
  return <div className="accountMenu"><div className="accountSummary"><span>{role==="admin"?"MK":role==="unternehmen"?"UN":"DL"}</span><div><b>{role==="admin"?"Martin Kelm":role==="unternehmen"?"Unternehmenskonto":"Dienstleisterkonto"}</b><small>Angemeldeter Arbeitsbereich · Sitzung geschützt</small></div></div><nav aria-label="Kontobereiche">{role==="unternehmen"&&<><Link href="/portal/unternehmen/profil"><span>▣</span><div><b>Unternehmensprofil</b><small>Stammdaten, Ansprechpartner und Sichtbarkeit bearbeiten</small></div><strong>→</strong></Link><Link href="/portal/unternehmen/team"><span>♙</span><div><b>Team und Zugänge</b><small>Mitglieder, Rollen und Berechtigungen verwalten</small></div><strong>→</strong></Link></>}<Link href={role==="unternehmen"?"/portal/unternehmen/einstellungen":role==="dienstleister"?"/portal/dienstleister":"/portal/admin"}><span>⚙</span><div><b>Einstellungen</b><small>Konto, Benachrichtigungen, Datenschutz und Sicherheit</small></div><strong>→</strong></Link><Link href={role==="unternehmen"?"/portal/unternehmen":role==="dienstleister"?"/portal/dienstleister":"/portal/admin"}><span>⌂</span><div><b>Zur Übersicht</b><small>Zurück in Ihren persönlichen Arbeitsbereich</small></div><strong>→</strong></Link></nav><button type="button" className="accountLogout">Abmelden</button></div>;
 }
 if(kind==="new-need"||kind==="ai")return <NeedCreationForm profile={profile}/>;
 if(kind==="new-need-legacy")return <div className="needForm">
  <div className="needFormIntro"><span>Matching-Grundlage</span><h3>Je genauer Ihr Bedarf, desto relevanter die Empfehlungen.</h3><p>Ihre Unternehmensidentität bleibt verborgen. Dienstleister sehen nach Ihrer Freigabe nur das anonymisierte Anforderungsprofil.</p></div>
  <fieldset><legend>1. Bedarf und Einordnung</legend><div className="dialogSplit"><label>Titel des Bedarfs<input placeholder="z. B. Externe IT-Sicherheitsprüfung"/></label><label>Hauptkategorie<select defaultValue=""><option value="" disabled>Kategorie wählen</option><option>IT & Digitalisierung</option><option>Marketing & Kommunikation</option><option>Personal & Organisation</option><option>Beratung & Strategie</option><option>Finanzen & Recht</option><option>Produktion & Logistik</option></select></label></div><div className="dialogSplit"><label>Unterkategorie<input placeholder="z. B. Cybersecurity / Penetrationstest"/></label><label>Bedarfsart<select><option>Einmaliges Projekt</option><option>Laufende Betreuung</option><option>Interim-Unterstützung</option><option>Strategische Partnerschaft</option><option>Rahmenvertrag</option></select></label></div><label className="full">Kurzbeschreibung für die Match-Übersicht<textarea rows={3} maxLength={500} placeholder="Fassen Sie den Bedarf in 3–5 aussagekräftigen Sätzen zusammen."/></label></fieldset>
  <fieldset><legend>2. Anonymisierter Unternehmenskontext</legend><p className="fieldHint">Diese Angaben verbessern die Passung, ohne Ihren Unternehmensnamen offenzulegen.</p><div className="dialogSplit thirds"><label>Branche<input placeholder="z. B. Maschinenbau"/></label><label>Unternehmensgröße<select><option>1–9 Beschäftigte</option><option>10–49 Beschäftigte</option><option>50–249 Beschäftigte</option><option>250–999 Beschäftigte</option><option>1.000+ Beschäftigte</option></select></label><label>Unternehmenstyp<select><option>Mittelstand</option><option>Start-up</option><option>Konzern</option><option>Verband / Organisation</option><option>Öffentliches Unternehmen</option></select></label></div><div className="dialogSplit"><label>Standort / Region<input placeholder="Bundesland oder Region"/></label><label>Marktgebiet<select><option>Regional</option><option>Deutschlandweit</option><option>DACH</option><option>Europa</option><option>International</option></select></label></div><label className="full">Ausgangslage und Unternehmensumfeld<textarea rows={5} placeholder="Was ist der Hintergrund? Welche Systeme, Strukturen, Zielgruppen oder besonderen Rahmenbedingungen bestehen bereits?"/></label></fieldset>
  <fieldset><legend>3. Ziele und Leistungsumfang</legend><label className="full">Ziel und gewünschtes Ergebnis<textarea rows={5} placeholder="Welche konkrete Veränderung oder welches messbare Ergebnis soll erreicht werden?"/></label><label className="full">Erwarteter Leistungsumfang<textarea rows={7} placeholder="Welche Aufgaben, Arbeitspakete und Liefergegenstände soll der Dienstleister übernehmen? Was gehört ausdrücklich nicht zum Auftrag?"/></label><div className="dialogSplit"><label>Muss-Kriterien<textarea rows={5} placeholder="Je Zeile ein zwingendes Kriterium, z. B. ISO-27001-Erfahrung"/></label><label>Kann-Kriterien<textarea rows={5} placeholder="Je Zeile ein wünschenswertes Kriterium"/></label></div><label className="full">Erfolgskriterien / Abnahme<textarea rows={4} placeholder="Woran erkennen Sie, dass die Zusammenarbeit erfolgreich war?"/></label></fieldset>
  <fieldset><legend>4. Gesuchte Kompetenz</legend><label className="full">Matching-Keywords<div className="keywordInput"><input placeholder="Keyword eingeben, z. B. ISO 27001"/><button type="button">＋ Hinzufügen</button></div><small>Fachbegriffe, Methoden, Systeme, Technologien und Branchenwissen. Die KI ergänzt Synonyme und verwandte Begriffe.</small></label><div className="keywordExamples"><span>Strategieberatung</span><span>Prozessoptimierung</span><span>Microsoft 365</span><span>ISO 27001</span><span>B2B</span></div><div className="dialogSplit"><label>Erforderliche Fachkenntnisse<textarea rows={4} placeholder="Methoden, Technologien, Software, Fachgebiete …"/></label><label>Nachweise und Zertifizierungen<textarea rows={4} placeholder="Zertifikate, Zulassungen, Referenzen, Mitgliedschaften …"/></label></div><div className="dialogSplit"><label>Gewünschte Branchenerfahrung<input placeholder="Branchen oder vergleichbare Umfelder"/></label><label>Sprachen<input placeholder="z. B. Deutsch C1, Englisch B2"/></label></div></fieldset>
  <fieldset><legend>5. Projekt- und Vertragsrahmen</legend><div className="dialogSplit thirds"><label>Frühester Start<input type="date"/></label><label>Spätester Start<input type="date"/></label><label>Voraussichtliche Dauer<select><option>Noch offen</option><option>Bis 1 Monat</option><option>1–3 Monate</option><option>3–6 Monate</option><option>6–12 Monate</option><option>Dauerhaft</option></select></label></div><div className="dialogSplit thirds"><label>Arbeitsmodell<select><option>Flexibel</option><option>Vor Ort</option><option>Remote</option><option>Hybrid</option></select></label><label>Erforderliche Kapazität<input placeholder="z. B. 2 Tage/Woche"/></label><label>Entscheidung geplant<select><option>Innerhalb 2 Wochen</option><option>Innerhalb 4 Wochen</option><option>Innerhalb 3 Monaten</option><option>Noch offen</option></select></label></div><div className="dialogSplit"><label>Budgetrahmen (optional)<select><option>Nicht öffentlich anzeigen</option><option>Unter 5.000 €</option><option>5.000–15.000 €</option><option>15.000–50.000 €</option><option>50.000–100.000 €</option><option>Über 100.000 €</option><option>Nach Aufwand / offen</option></select></label><label>Bevorzugtes Vergütungsmodell<select><option>Offen</option><option>Festpreis</option><option>Tagessatz</option><option>Stundensatz</option><option>Monatliche Pauschale</option><option>Erfolgsabhängig</option></select></label></div></fieldset>
  <fieldset><legend>6. Matchinggewichtung und Sichtbarkeit</legend><p className="fieldHint">Bestimmen Sie, was für die prozentuale Bewertung besonders wichtig ist.</p><div className="weightGrid"><label><span>Fachkompetenz <b>sehr wichtig</b></span><input type="range" min="1" max="5" defaultValue="5"/></label><label><span>Branchenerfahrung <b>wichtig</b></span><input type="range" min="1" max="5" defaultValue="4"/></label><label><span>Region / Arbeitsmodell <b>mittel</b></span><input type="range" min="1" max="5" defaultValue="3"/></label><label><span>Verfügbarkeit <b>wichtig</b></span><input type="range" min="1" max="5" defaultValue="4"/></label><label><span>Budgetpassung <b>mittel</b></span><input type="range" min="1" max="5" defaultValue="3"/></label></div><div className="privacyChoices"><label><input type="checkbox" defaultChecked/> Unternehmensname und Kontaktdaten bis zu meiner Freigabe vollständig verbergen</label><label><input type="checkbox" defaultChecked/> Nur verifizierte und freigegebene Dienstleister berücksichtigen</label><label><input type="checkbox"/> Bedarf nach Veröffentlichung automatisch nach 90 Tagen deaktivieren</label></div></fieldset>
  <fieldset><legend>7. Ergänzende Unterlagen</legend><div className="uploadBox"><span>⇧</span><b>Dateien hier ablegen oder auswählen</b><small>Briefings, Anforderungskataloge oder technische Unterlagen · PDF, DOCX, XLSX · vertraulich</small><button type="button" className="portalSecondary">Datei auswählen</button></div><label className="full">Interne Notiz – für Dienstleister nicht sichtbar<textarea rows={3} placeholder="Eigene Hinweise für die spätere Prüfung und Freigabe"/></label></fieldset>
 </div>;
 if(kind==="ai")return <><div className="dialogAiHint">✦ Die KI formuliert aus Ihren Angaben einen strukturierten, anonymisierten Bedarf.</div><label className="full">Beschreiben Sie Ihre Situation<textarea rows={7} placeholder="Wir möchten … Uns fehlt derzeit … Wichtig ist uns …"/></label><label><input type="checkbox" defaultChecked/> Unternehmensidentität weiterhin verbergen</label></>;
 if(kind==="profile"&&role==="unternehmen")return <div className="companyProfileForm">
  <div className="profilePrivacyIntro"><span>Geschütztes Unternehmensprofil</span><h3>Vollständige Angaben schaffen Vertrauen und bessere Matches.</h3><p>Pflichtfelder sind links farbig markiert und werden beim Speichern geprüft. Optionale Angaben beeinflussen den Status nicht. Ihre Daten bleiben bis zu einer bewussten Match-Freigabe verborgen.</p></div>
  <fieldset><legend>1. Persönlicher Ansprechpartner</legend><div className="dialogSplit thirds"><label>Anrede<select required defaultValue=""><option value="" disabled>Bitte wählen</option><option>Frau</option><option>Herr</option><option>Divers</option><option>Keine Angabe</option></select></label><label>Vorname<input required autoComplete="given-name" placeholder="Vorname"/></label><label>Nachname<input required autoComplete="family-name" placeholder="Nachname"/></label></div><div className="dialogSplit"><label>Position / Funktion<input required placeholder="z. B. Geschäftsführung, Einkauf, IT-Leitung"/></label><label>Abteilung / Bereich<input required placeholder="z. B. Einkauf, Marketing, Personal"/></label></div><div className="dialogSplit"><label>Geschäftliche E-Mail-Adresse<input required type="email" autoComplete="email" placeholder="vorname.nachname@unternehmen.de"/></label><label>Geschäftliche Telefonnummer<input required type="tel" autoComplete="tel" placeholder="+49 …"/></label></div><label className="full">Bevorzugter Kontaktweg<select required><option>E-Mail</option><option>Telefon</option><option>Portalnachricht</option><option>Nach Terminvereinbarung</option></select></label></fieldset>
  <fieldset><legend>2. Berechtigung und Verantwortung</legend><div className="authorityBox"><strong>Dürfen Sie für dieses Unternehmen Bedarfe einstellen und Kooperationen anbahnen?</strong><label><input required type="radio" name="authority" value="yes"/> Ja, ich bin entscheidungs- oder vertretungsbevollmächtigt.</label><label><input type="radio" name="authority" value="limited"/> Teilweise – eine weitere interne Freigabe ist erforderlich.</label><label><input type="radio" name="authority" value="no"/> Nein, ich erfasse Bedarfe im Auftrag einer berechtigten Person.</label></div><div className="dialogSplit"><label>Name der freigabeberechtigten Person<input placeholder="Nur falls eine weitere Freigabe erforderlich ist"/></label><label>Funktion der freigabeberechtigten Person<input placeholder="z. B. Geschäftsführung"/></label></div><label><input required type="checkbox"/> Ich bestätige, dass ich zur geschäftlichen Registrierung für das angegebene Unternehmen berechtigt bin.</label><label><input required type="checkbox"/> Ich bestätige, dass Bedarfe ausschließlich für geschäftliche Zwecke eingestellt werden.</label></fieldset>
  <fieldset><legend>3. Unternehmensstammdaten</legend><div className="dialogSplit"><label>Vollständige Firmierung<input required autoComplete="organization" placeholder="Unternehmen inklusive Rechtsform"/></label><label>Rechtsform<select required defaultValue=""><option value="" disabled>Rechtsform wählen</option><option>Einzelunternehmen</option><option>GbR</option><option>UG (haftungsbeschränkt)</option><option>GmbH</option><option>GmbH & Co. KG</option><option>KG</option><option>AG</option><option>e. V.</option><option>Sonstige</option></select></label></div><div className="dialogSplit"><label>Handelsname / Kurzbezeichnung<input placeholder="Optional"/></label><label>Gründungsjahr<input required type="number" min="1800" max="2100" placeholder="JJJJ"/></label></div><div className="dialogSplit thirds"><label>Straße<input required autoComplete="street-address" placeholder="Straße"/></label><label>Hausnummer<input required placeholder="Nr."/></label><label>Adresszusatz<input placeholder="Optional"/></label></div><div className="dialogSplit thirds"><label>Postleitzahl<input required autoComplete="postal-code" inputMode="numeric" placeholder="PLZ"/></label><label>Ort<input required autoComplete="address-level2" placeholder="Ort"/></label><label>Land<select required><option>Deutschland</option><option>Österreich</option><option>Schweiz</option><option>Anderes Land</option></select></label></div><div className="dialogSplit"><label>Website<input required type="url" placeholder="https://www.unternehmen.de"/></label><label>Zentrale Telefonnummer<input required type="tel" placeholder="+49 …"/></label></div><div className="dialogSplit"><label>Allgemeine E-Mail-Adresse<input required type="email" placeholder="info@unternehmen.de"/></label><label>Weitere Standorte<input placeholder="Städte oder Regionen, optional"/></label></div></fieldset>
  <fieldset><legend>4. Unternehmensstruktur</legend><div className="dialogSplit thirds"><label>Hauptbranche<select required defaultValue=""><option value="" disabled>Branche wählen</option><option>Industrie & Produktion</option><option>Handel & E-Commerce</option><option>IT & Telekommunikation</option><option>Finanzen & Versicherungen</option><option>Gesundheit & Soziales</option><option>Bau & Immobilien</option><option>Logistik & Mobilität</option><option>Medien & Kommunikation</option><option>Beratung & Dienstleistungen</option><option>Öffentlicher Sektor</option><option>Sonstige</option></select></label><label>Mitarbeitendenzahl<select required><option>1–9</option><option>10–49</option><option>50–249</option><option>250–999</option><option>1.000–4.999</option><option>5.000+</option></select></label><label>Jahresumsatz (optional)<select><option>Keine Angabe</option><option>Bis 2 Mio. €</option><option>2–10 Mio. €</option><option>10–50 Mio. €</option><option>50–250 Mio. €</option><option>Über 250 Mio. €</option></select></label></div><div className="dialogSplit"><label>Geschäftsgebiet<select required><option>Regional</option><option>Deutschlandweit</option><option>DACH</option><option>Europa</option><option>International</option></select></label><label>Kundenausrichtung<select required><option>B2B</option><option>B2C</option><option>B2B und B2C</option><option>Öffentlicher Sektor</option></select></label></div><label className="full">Weitere Branchen und Tätigkeitsfelder<input required placeholder="Mehrere Begriffe mit Komma trennen"/></label></fieldset>
  <fieldset><legend>5. Unternehmensbeschreibung</legend><label className="full">Kurzprofil<textarea required rows={4} maxLength={600} placeholder="Beschreiben Sie Ihr Unternehmen kompakt: Tätigkeit, Markt, Zielgruppen und Besonderheiten."/></label><label className="full">Ausführliche Unternehmensbeschreibung<textarea required rows={8} placeholder="Geschäftsmodell, Produkte oder Leistungen, Zielgruppen, Marktposition, Standorte, Strukturen, aktuelle Entwicklung und alles, was für passende Dienstleister relevant sein kann."/></label><div className="dialogSplit"><label>Produkte und Leistungen<textarea required rows={5} placeholder="Wichtigste Angebote oder Leistungsbereiche"/></label><label>Zielgruppen und Märkte<textarea required rows={5} placeholder="Kundengruppen, Branchen und Absatzmärkte"/></label></div><label className="full">Unternehmens-Keywords<div className="keywordInput"><input required placeholder="z. B. Maschinenbau, Mittelstand, Export"/><button type="button">＋ Hinzufügen</button></div><small>Diese Begriffe helfen, Bedarfe und Dienstleister fachlich besser einzuordnen.</small></label></fieldset>
  <fieldset><legend>6. Beschaffungs- und Kooperationsprofil</legend><div className="dialogSplit"><label>Typischer Beschaffungsbedarf<textarea required rows={5} placeholder="Welche externen Leistungen benötigt Ihr Unternehmen regelmäßig?"/></label><label>Bevorzugte Zusammenarbeit<textarea required rows={5} placeholder="Projektarbeit, Rahmenverträge, langfristige Betreuung, Interim …"/></label></div><div className="dialogSplit"><label>Übliche Projektgröße<select required><option>Noch offen</option><option>Bis 5.000 €</option><option>5.000–15.000 €</option><option>15.000–50.000 €</option><option>50.000–100.000 €</option><option>Über 100.000 €</option></select></label><label>Bevorzugtes Arbeitsmodell<select required><option>Flexibel</option><option>Vor Ort</option><option>Remote</option><option>Hybrid</option></select></label></div><label className="full">Übergeordnete Anforderungen an Dienstleister<textarea required rows={4} placeholder="z. B. Zertifizierungen, Datenschutz, Nachhaltigkeit, Reaktionszeiten, Sprachkenntnisse"/></label></fieldset>
  <fieldset><legend>7. Kontostatus und optionale Nachweise</legend><div className="verificationGrid single"><div className="verifiedAccount"><strong aria-hidden="true">✓</strong><span><b>E-Mail-Adresse bestätigt</b><small>{accountEmail||"Die geschäftliche E-Mail-Adresse wurde bereits bei der Registrierung bestätigt."}</small></span></div></div><div className="uploadBox"><span>⇧</span><b>Optionalen Unternehmensnachweis hochladen</b><small>z. B. Gewerbenachweis oder Handelsregisterauszug · nicht öffentlich sichtbar</small><button type="button" className="portalSecondary">Datei auswählen</button></div></fieldset>
  <fieldset><legend>8. Sichtbarkeit und Datenschutz</legend><div className="privacyChoices"><label><input type="checkbox" defaultChecked/> Unternehmens- und Kontaktdaten vor einer Match-Freigabe vollständig verbergen</label><label><input type="checkbox" defaultChecked/> Nach Freigabe Firmenname, Beschreibung, Website und geschäftliche Kontaktdaten anzeigen</label><label><input type="checkbox"/> Ansprechpartner bereits im freigegebenen Unternehmensprofil namentlich anzeigen</label><label><input type="checkbox"/> Über passende Dienstleister und neue Matchings per E-Mail informieren</label></div><p className="fieldHint">Ihre Einstellungen können später pro Bedarf und pro Dienstleister nochmals individuell entschieden werden.</p></fieldset>
 </div>;
 if(kind==="profile")return <><div className="dialogSplit"><label>Unternehmensname<input placeholder="Vollständige Firmierung"/></label><label>Branche<input placeholder="Hauptbranche"/></label></div><label className="full">Leistungsversprechen<textarea rows={5} placeholder="Positionierung und Nutzenversprechen des Dienstleisters"/></label><div className="dialogSplit"><label>Region<input placeholder="Einsatzgebiet"/></label><label>Website<input type="url" placeholder="https://"/></label></div></>;
 if(kind==="member")return <><div className="dialogSplit"><label>Unternehmen<input placeholder="Firmenname"/></label><label>Rolle<select><option>Unternehmer</option><option>Dienstleister</option><option>Administrator</option></select></label></div><div className="dialogSplit"><label>Ansprechpartner<input placeholder="Vor- und Nachname"/></label><label>E-Mail<input type="email" placeholder="name@unternehmen.de"/></label></div><label><input type="checkbox" defaultChecked/> Einladungs-E-Mail versenden</label></>;
 if(kind==="message")return <div className="portalInlineAlert"><b>Keine Unterhaltung ausgewählt</b><p>Nachrichten und Termine werden ausschließlich innerhalb eines beidseitig freigegebenen Matches geöffnet.</p></div>;
 if(kind==="review")return <><div className="reviewSummary"><span>91%</span><div><b>Automatische Qualitätsbewertung</b><p>Unternehmensdaten plausibel · Leistungstexte vollständig · ein Nachweis offen</p></div></div><label>Prüfentscheidung<select><option>Profil freigeben</option><option>Rückfrage senden</option><option>Zurückstellen</option><option>Ablehnen</option></select></label><label className="full">Interne Notiz<textarea rows={4} placeholder="Entscheidung dokumentieren …"/></label></>;
 if(kind==="search")return <><label className="full">Portal durchsuchen<input autoFocus placeholder="Unternehmen, Bedarf, Dienstleistung oder Nachricht …"/></label><div className="searchEmpty">Noch keine durchsuchbaren Inhalte vorhanden.</div></>;
 if(kind==="Geschäftschancen")return <div className="needPreview"><div className="anonymousBanner"><span>◉</span><div><b>Anonymisiertes Unternehmen</b><p>Identität und Kontaktdaten werden erst nach Freigabe sichtbar.</p></div><strong>0 %</strong></div><section><span>BEDARF</span><h3>Noch keine freigegebene Geschäftschance</h3><p>Sobald ein suchendes Unternehmen einen Match für Sie freigibt, erscheint hier das vollständige anonymisierte Anforderungsprofil.</p></section><div className="previewGrid"><article><small>Unternehmenskontext</small><b>Branche, Größe, Region, Marktgebiet</b></article><article><small>Projektumfang</small><b>Ziele, Leistungen und Ergebnisse</b></article><article><small>Anforderungen</small><b>Muss-/Kann-Kriterien und Nachweise</b></article><article><small>Rahmenbedingungen</small><b>Start, Dauer, Modell und Budget</b></article></div><section><span>MATCHING-TRANSPARENZ</span><h4>So wird die Passung erklärt</h4><div className="matchingFactors"><p><b>Fachkompetenz</b><i/><small>Keine Daten</small></p><p><b>Branchenerfahrung</b><i/><small>Keine Daten</small></p><p><b>Verfügbarkeit</b><i/><small>Keine Daten</small></p><p><b>Region & Arbeitsmodell</b><i/><small>Keine Daten</small></p></div></section></div>;
 if(kind==="provider-preview")return <div className="providerPreview"><div className="providerPreviewHero"><span>DL</span><div><small>GEPRÜFTES DIENSTLEISTERPROFIL</small><h3>Noch kein Dienstleister ausgewählt</h3><p>Hier erscheinen Positionierung, Leistungen und verifizierte Unternehmensangaben.</p></div><strong>—<small>%</small></strong></div><div className="providerPreviewNav"><button type="button" className="active">Übersicht</button><button type="button">Leistungen</button><button type="button">Referenzen</button><button type="button">Nachweise</button><button type="button">Matchanalyse</button></div><section><span>POSITIONIERUNG</span><h4>Leistungsversprechen und Unternehmensbeschreibung</h4><p>Ausführliche Informationen zur Spezialisierung, Arbeitsweise, Zielgruppe und Erfahrung des Dienstleisters.</p></section><div className="previewGrid"><article><small>Unternehmensdaten</small><b>Firmierung, Standort, Größe und Gründungsjahr</b></article><article><small>Leistungsschwerpunkte</small><b>Kategorien, Methoden, Technologien und Keywords</b></article><article><small>Erfahrung</small><b>Branchen, Referenzen und vergleichbare Projekte</b></article><article><small>Zusammenarbeit</small><b>Region, Arbeitsmodell, Kapazität und Verfügbarkeit</b></article></div><section><span>VERTRAUEN & QUALITÄT</span><div className="trustChecklist"><p><b>✓</b><span>Profil durch Portaladministration freigegeben</span></p><p><b>○</b><span>Nachweise und Zertifizierungen werden hier angezeigt</span></p><p><b>○</b><span>Referenzen werden strukturiert und nachvollziehbar dargestellt</span></p></div></section><section><span>WARUM DIESER MATCH?</span><h4>Transparente Bewertung je Kriterium</h4><div className="matchingFactors"><p><b>Fachkompetenz</b><i/><small>Keine Daten</small></p><p><b>Muss-Kriterien</b><i/><small>Keine Daten</small></p><p><b>Branchenerfahrung</b><i/><small>Keine Daten</small></p><p><b>Verfügbarkeit</b><i/><small>Keine Daten</small></p></div></section><div className="providerDecisionBar"><button type="button" className="portalReject">Ablehnen</button><button type="button" className="portalSecondary">☆ Favorisieren</button><button type="button" className="portalPrimary">Bedarf für Dienstleister freigeben</button></div></div>;
 return moduleCopy[kind]?<div className="dialogContextNotice"><b>{moduleCopy[kind][0]}</b><p>{moduleCopy[kind][1]}</p></div>:null;
}

export function PortalInteractions({role,children}:{role:Role;children:ReactNode}){
 const [dialog,setDialog]=useState<Dialog>(null);const [toast,setToast]=useState("");const [accountEmail,setAccountEmail]=useState("");const [storedProfile,setStoredProfile]=useState<StoredProfile|null>(null);
 useEffect(()=>{if(role!=="unternehmen")return;const token=getPortalSession();if(!token)return;const load=()=>portalRequest<Array<{id:string;profileData?:Record<string,string|boolean>;profileUpdatedAt?:string|null;profileRequiredTotal?:number;profileRequiredCompleted?:number;profileRequiredSections?:boolean[]}>>("/organizations/mine",{token}).then(organizations=>{const organization=organizations[0];setStoredProfile(organization?.profileData?{values:organization.profileData,updatedAt:organization.profileUpdatedAt||new Date().toISOString(),requiredTotal:organization.profileRequiredTotal,requiredCompleted:organization.profileRequiredCompleted,requiredSections:organization.profileRequiredSections}:null)}).catch(()=>setToast("Das Unternehmensprofil konnte nicht geladen werden."));void load();window.addEventListener(PORTAL_UPDATE_EVENT,load);return()=>window.removeEventListener(PORTAL_UPDATE_EVENT,load)},[role]);
 useEffect(()=>{
  const token=getPortalSession();if(!token)return;
  portalRequest<{email:string}>("/auth/session/check",{method:"POST",token}).then(session=>setAccountEmail(session.email)).catch(()=>{});
 },[]);
 useEffect(()=>{
  if(!dialog)return;
  const frame=requestAnimationFrame(()=>{
   const dialogElement=document.querySelector<HTMLElement>(".companyDialog");
   if(dialog.kind==="profile"&&role==="unternehmen"){
    const controls=document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(".companyProfileForm input,.companyProfileForm textarea,.companyProfileForm select");
    controls.forEach((control,index)=>{const value=storedProfile?.values?.[`field-${index}`];if(typeof value==="boolean"&&control instanceof HTMLInputElement)control.checked=value;else if(typeof value==="string")control.value=value});
   }
   if(dialog.kind==="profile"&&dialog.context&&dialogElement){
    const section=dialogElement.querySelectorAll<HTMLElement>(".companyProfileForm fieldset")[Number(dialog.context)-1];
    if(!section)return;
    dialogElement.scrollTo({top:Math.max(0,section.offsetTop-96),behavior:"smooth"});
    section.setAttribute("tabindex","-1");
    section.focus({preventScroll:true});
   }
  });
  return ()=>cancelAnimationFrame(frame);
 },[dialog,role,storedProfile]);
 function open(title:string,kind:string,context?:string){setDialog({title,kind,context})}
 function click(e:MouseEvent<HTMLDivElement>){
   const target=e.target as HTMLElement;const link=target.closest("a");const button=target.closest("button");
   if(target.closest(".adminNetworkWorkspace"))return;
   if(target.closest(".needManageModal,.needModalBackdrop,.needIconAction"))return;
   if(target.closest(".portalSearch")){open("Portal durchsuchen","search");return}
  if(link){const href=link.getAttribute("href")||"";if(href.startsWith("#")){const label=(link.textContent||"").trim().replace(/\d+$/,"");const targetEl=document.querySelector(href);if(targetEl){targetEl.scrollIntoView({behavior:"smooth"});return}e.preventDefault();open(moduleCopy[label]?.[0]||label,label)}return}
  if(!button&&target.closest(".conversationRows article")){open("Nachricht und Terminabstimmung","message");return}
  if(!button&&target.closest(".compactPeople p")){open("Profil im Detail","profile-preview");return}
  if(!button&&target.closest(".activity p")){open("Aktivitätsdetails","Historie");return}
  if(!button)return;
  const text=(button.getAttribute("aria-label")||button.textContent||"").trim();
  if(button.closest(".portalDialog")){if(text.includes("Abmelden")){localStorage.removeItem("b2b-matching-session");sessionStorage.removeItem("b2b-matching-session");window.location.href="/anmelden";return}return}
  if(button.closest(".workspaceTabs"))return;
  const profileSectionButton=button.closest(".profileSectionGrid button") as HTMLButtonElement|null;
  if(profileSectionButton){
   const sectionButtons=Array.from(profileSectionButton.parentElement?.querySelectorAll("button")||[]);
   return open("Unternehmensprofil bearbeiten","profile",String(sectionButtons.indexOf(profileSectionButton)+1));
  }
  if(button.closest(".portalUser"))return open("Mein Konto","account");
  if(text.includes("Benachrichtig"))return open("Benachrichtigungen","notifications");
  if(text.includes("Neuen Bedarf")||text.includes("Ersten Bedarf"))return open("Neuen Bedarf erstellen","new-need");
  if(text.includes("KI erstellen")||text.includes("Bedarf mit KI"))return open("KI-Bedarfsassistent","ai");
  if(text.includes("Mitglied anlegen")||text.includes("Mitglied einladen")||text.includes("Teammitglied"))return open("Teammitglied einladen","member");
  if(text.includes("Leistungsseite")||text.includes("Profil vervollständigen")||text.includes("Unternehmensprofil"))return open(role==="dienstleister"?"Leistungsprofil bearbeiten":"Unternehmensprofil bearbeiten","profile");
  if(text.includes("Prüfen")||text.includes("bearbeiten")||text.includes("Prüfzentrum"))return open(text.includes("Profil")?"Dienstleisterprofil prüfen":"Profilprüfung","review");
  if(text.includes("Chance ansehen")||text.includes("Geschäftschance ansehen"))return open("Anonymisiertes Anforderungsprofil","Geschäftschancen");
  if(text.includes("Dienstleisterprofil"))return open("Dienstleisterprofil prüfen","provider-preview");
  if(text.includes("Vorschau"))return open("Öffentliche Profilvorschau","profile-preview");
  if(text.includes("Abonnement")||text.includes("Tarife"))return open("Tarife und Abonnement","Abonnement");
  if(text.includes("Ablehnen")||text.includes("entfernen"))return;
  if(text.includes("Alle Bedarfe"))return open("Alle Bedarfe","Meine Bedarfe");
  if(text.includes("Matching")||text.includes("Chancen"))return open(text.replace("→",""),role==="dienstleister"?"Geschäftschancen":"Matches");
  if(text==="Jetzt bearbeiten")return open("Offene Profilprüfungen","review");
  return;
 }
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();
  const controls=Array.from(e.currentTarget.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>("input,textarea,select")).filter(control=>control.type!=="range");
  const values:Record<string,string|boolean>={};
  controls.forEach((control,index)=>values[`field-${index}`]=control instanceof HTMLInputElement&&(control.type==="checkbox"||control.type==="radio")?control.checked:control.value);
  if(dialog?.kind==="profile"&&role==="unternehmen"){
   const required=controls.filter(control=>control.required);
   const requiredCompleted=required.filter(control=>{
    if(control instanceof HTMLInputElement&&control.type==="radio")return Boolean(e.currentTarget.querySelector<HTMLInputElement>(`input[type="radio"][name="${control.name}"]:checked`));
    if(control instanceof HTMLInputElement&&control.type==="checkbox")return control.checked;
    return control.value.trim().length>0;
   }).length;
   const requiredSections=Array.from(e.currentTarget.querySelectorAll<HTMLFieldSetElement>(".companyProfileForm fieldset")).map(section=>{
    const sectionRequired=Array.from(section.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>("input:required,textarea:required,select:required"));
    return sectionRequired.every(control=>{
     if(control instanceof HTMLInputElement&&control.type==="radio")return Boolean(section.querySelector<HTMLInputElement>(`input[type="radio"][name="${control.name}"]:checked`));
     if(control instanceof HTMLInputElement&&control.type==="checkbox")return control.checked;
     return control.value.trim().length>0;
    });
   });
    const token=getPortalSession();
    if(!token){setToast("Bitte melden Sie sich erneut an.");return}
    try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");await portalRequest(`/organizations/${organizations[0].id}/profile`,{token,body:{profileData:values,requiredTotal:required.length,requiredCompleted,requiredSections}});setStoredProfile({values,requiredTotal:required.length,requiredCompleted,requiredSections,updatedAt:new Date().toISOString()})}catch(error){setToast(error instanceof Error?error.message:"Das Profil konnte nicht zentral gespeichert werden.");return}
   window.dispatchEvent(new Event(PORTAL_UPDATE_EVENT));
   setToast("Unternehmensprofil gespeichert. Der Profilfortschritt wurde aktualisiert.");
  }else if(dialog?.kind==="new-need"||dialog?.kind==="ai"){
   const summaryControl=controls.find(control=>control instanceof HTMLTextAreaElement);
   const titleControl=controls.find(control=>control instanceof HTMLInputElement&&control.type==="text");
   const categoryControl=controls.find(control=>control instanceof HTMLSelectElement);
   const summary=(summaryControl?.value||"").trim();
   const manualTitle=(titleControl?.value||"").trim();
   const generatedTitle=summary.split(/[.!?]/)[0]?.trim().slice(0,80);
   const title=manualTitle||(dialog.kind==="ai"&&generatedTitle?`KI-Entwurf: ${generatedTitle}`:"Neuer geschäftlicher Bedarf");
   const category=(categoryControl?.value||(dialog.kind==="ai"?"KI-Entwurf · Einordnung offen":"Noch nicht eingeordnet")).trim();
   const details=controls.flatMap(control=>{
    if(control.closest(".needLivePreview"))return [];
    if(control===titleControl||control===categoryControl||control===summaryControl)return [];
    if(control instanceof HTMLInputElement&&(control.type==="checkbox"||control.type==="radio"||control.type==="range"||control.type==="hidden"))return [];
    const value=control.value.trim();if(!value)return [];
    const label=control.closest("label")?.childNodes[0]?.textContent?.trim()||"Weitere Angabe";
    return [{label,value}];
   });
   const token=getPortalSession();if(!token){setToast("Bitte melden Sie sich erneut an.");return}
   try{const organizations=await portalRequest<Array<{id:string}>>("/organizations/mine",{token});if(!organizations[0])throw new Error("Kein Unternehmenskonto gefunden.");await portalRequest(`/organizations/${organizations[0].id}/needs`,{token,body:{title,description:summary||title,categoryId:category,requiredSkills:details.filter(item=>/keyword|fachkennt|kompetenz/i.test(item.label)).flatMap(item=>item.value.split(",").map(value=>value.trim()).filter(Boolean)),preferredIndustries:[],region:null,deliveryModes:["hybrid"],details,submitForReview:false}})}catch(error){setToast(error instanceof Error?error.message:"Der Bedarf konnte nicht gespeichert werden.");return}
   window.dispatchEvent(new Event(PORTAL_UPDATE_EVENT));
   window.location.assign("/portal/unternehmen/bedarfe");
   return;
  }else return;
  setDialog(null);
 }
 return <div onClick={click}>{children}{dialog&&<div className="portalDialogBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section className={`portalDialog ${dialog.kind==="new-need"||dialog.kind==="ai"?"needDialog":dialog.kind==="profile"&&role==="unternehmen"?"companyDialog":dialog.kind==="account"?"accountDialog":""}`} role="dialog" aria-modal="true" aria-labelledby="portal-dialog-title"><header><div><span>{role.toUpperCase()}</span><h2 id="portal-dialog-title">{dialog.title}</h2></div><button type="button" onClick={()=>setDialog(null)} aria-label="Dialog schließen">×</button></header><form onSubmit={submit}>{fields(dialog.kind,role,accountEmail,storedProfile)}{dialog.kind!=="account"&&<div className="portalDialogActions"><button type="button" className="portalSecondary" onClick={()=>setDialog(null)}>Abbrechen</button><button type="submit" className="portalPrimary">{dialog.kind==="message"?"Nachricht senden":"Speichern und Vorschau"}</button></div>}</form></section></div>}{toast&&<div className="portalToast" role="status"><span>✓</span>{toast}<button onClick={()=>setToast("")} aria-label="Meldung schließen">×</button></div>}</div>
}
