"use client";
import {useCallback,useEffect,useState} from "react";
import type {FormEvent} from "react";
import {getPortalSession,portalRequest} from "../lib/portal-api";
import {PortalEmpty,PortalPanel,PortalStats,Status} from "./portal-shell";

type Org={id:string;reviewStatus:string}; type Category={id:string;name:string};
type Page={id:string;title:string;summary:string;description:string;categoryId:string;skills:string[];targetIndustries:string[];serviceRegions:string[];deliveryModes:string[];reviewStatus:string};
type Chance={match:{id:string;score:number;status:string};need:{title:string;description:string;categoryId:string;region:string|null}};
const labels:Record<string,string>={draft:"Entwurf",submitted:"In Prüfung",approved:"Freigegeben",changes_requested:"Änderung erforderlich",rejected:"Abgelehnt"};
const csv=(value:FormDataEntryValue|null)=>String(value||"").split(",").map(v=>v.trim()).filter(Boolean);

export function ProviderWorkspace(){
 const [org,setOrg]=useState<Org|null>(null),[pages,setPages]=useState<Page[]>([]),[categories,setCategories]=useState<Category[]>([]),[chances,setChances]=useState<Chance[]>([]),[editing,setEditing]=useState<Page|null|"new">(null),[message,setMessage]=useState("");
 const refresh=useCallback(async()=>{const token=getPortalSession();if(!token){setMessage("Bitte melden Sie sich erneut an.");return}try{const [organizations,servicePages,categoryData,matchData]=await Promise.all([portalRequest<Org[]>("/organizations/mine",{token}),portalRequest<Page[]>("/services/mine",{token}),portalRequest<Category[]>("/categories",{token}),portalRequest<Chance[]>("/provider/matches",{token})]);setOrg(organizations[0]||null);setPages(servicePages);setCategories(categoryData);setChances(matchData);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Die Daten konnten nicht geladen werden.")}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const action=async(path:string,body:unknown={})=>{const token=getPortalSession();if(!token)return;try{await portalRequest(path,{token,body});await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Die Aktion konnte nicht ausgeführt werden.")}};
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!org)return;const data=new FormData(event.currentTarget),body={title:String(data.get("title")||""),summary:String(data.get("summary")||""),description:String(data.get("description")||""),categoryId:String(data.get("categoryId")||""),skills:csv(data.get("skills")),targetIndustries:csv(data.get("industries")),serviceRegions:csv(data.get("regions")),deliveryModes:data.getAll("modes").map(String)};await action(editing==="new"?`/organizations/${org.id}/services`:`/services/${(editing as Page).id}/update`,body);setEditing(null)};
 const approved=org?.reviewStatus==="approved";
 return <>{message&&<p className="portalInlineAlert" role="alert">{message}</p>}<div className="portalSetup"><div><span>DIENSTLEISTERFREIGABE</span><h2>{approved?"Unternehmen freigegeben – Leistungen und Chancen zentral verwalten.":"Unternehmen und Leistungen werden getrennt geprüft."}</h2></div><b>{approved?pages.length?75:50:25} %</b><div className="setupBar"><i style={{width:approved?pages.length?"75%":"50%":"25%"}}/></div><ol><li className="done">E-Mail bestätigt</li><li className={approved?"done":""}>Unternehmen freigegeben</li><li className={pages.length?"done":""}>Leistung erstellt</li><li className={pages.some(p=>p.reviewStatus==="approved")?"done":""}>Leistung freigegeben</li></ol></div>
 <PortalStats items={[[String(pages.length),"Leistungsseiten","Serverseitig gespeichert"],[String(chances.length),"Geschäftschancen","Ausdrücklich freigegeben"],[String(pages.filter(p=>p.reviewStatus==="submitted").length),"In Prüfung","Eigener Prüfstatus"],[String(chances.filter(c=>c.match.status==="mutual_match").length),"Kontakte","Beidseitig freigegeben"]]}/>
 <div className="portalGrid wideLeft"><div><PortalPanel id="profil" eyebrow="POSITIONIERUNG" title="Leistungsseiten" action={approved?<button className="portalIconCta" aria-label="Leistung hinzufügen" title="Leistung hinzufügen" onClick={()=>setEditing("new")}>＋</button>:undefined}>{!approved&&<div className="portalInlineAlert"><b>Unternehmensfreigabe erforderlich</b><p>Danach können Sie Leistungen veröffentlichen.</p>{["draft","changes_requested"].includes(org?.reviewStatus||"")&&<button className="portalPrimary" onClick={()=>void action(`/organizations/${org?.id}/submit`)}>Unternehmen zur Prüfung einreichen</button>}</div>}{pages.length?<div className="needRows">{pages.map(page=><article key={page.id}><div><Status tone={page.reviewStatus==="approved"?"teal":page.reviewStatus==="submitted"?"blue":"amber"}>{labels[page.reviewStatus]||page.reviewStatus}</Status><h3>{page.title}</h3><p>{page.summary}</p></div><div className="needIconActions">{["draft","changes_requested"].includes(page.reviewStatus)&&<><button className="needIconAction" title="Bearbeiten" onClick={()=>setEditing(page)}>✎</button><button className="needIconAction primary" title="Einreichen" onClick={()=>void action(`/services/${page.id}/submit`)}>◉</button></>}<button className="needIconAction" title="Duplizieren" onClick={()=>void action(`/services/${page.id}/duplicate`)}>⧉</button>{["draft","changes_requested","rejected"].includes(page.reviewStatus)&&<button className="needIconAction danger" title="Löschen" onClick={()=>void action(`/services/${page.id}/delete`)}>⌫</button>}</div></article>)}</div>:<PortalEmpty icon="◇" title="Noch keine Leistungsseite" text="Erstellen Sie nach der Unternehmensfreigabe Ihr matchingrelevantes Leistungsprofil."/>}</PortalPanel>
 <PortalPanel id="matches" eyebrow="GESCHÄFTSCHANCEN" title="Freigegebene Bedarfe">{chances.length?<div className="needRows">{chances.map(item=><article key={item.match.id}><div><Status tone="teal">{item.match.score} % passend</Status><h3>{item.need.title}</h3><p>{item.need.description}</p></div>{item.match.status==="released_anonymously"&&<div className="needIconActions"><button className="needIconAction primary" onClick={()=>void action(`/provider/matches/${item.match.id}/respond`,{interested:true})}>Interesse</button><button className="needIconAction danger" onClick={()=>void action(`/provider/matches/${item.match.id}/respond`,{interested:false})}>Ablehnen</button></div>}</article>)}</div>:<PortalEmpty icon="◎" title="Noch keine Geschäftschancen" text="Hier erscheinen ausschließlich vom Unternehmen für Sie freigegebene Bedarfe."/>}</PortalPanel></div><aside><PortalPanel title="Unternehmensstatus"><Status tone={approved?"teal":org?.reviewStatus==="submitted"?"blue":"amber"}>{labels[org?.reviewStatus||"draft"]||"Entwurf"}</Status><p className="panelNote">Unternehmen, Leistungsseiten und Matches besitzen getrennte Freigaben.</p></PortalPanel></aside></div>
 {editing&&<div className="needModalBackdrop"><section className="needManageModal" role="dialog" aria-modal="true"><header><div><span>LEISTUNGSPROFIL</span><h2>{editing==="new"?"Leistung erstellen":"Leistung bearbeiten"}</h2></div><button onClick={()=>setEditing(null)} aria-label="Schließen">×</button></header><form onSubmit={save}><label>Titel<input name="title" required minLength={5} defaultValue={editing==="new"?"":editing.title}/></label><label>Kurzbeschreibung<textarea name="summary" required minLength={20} defaultValue={editing==="new"?"":editing.summary}/></label><label>Ausführliche Beschreibung<textarea name="description" required minLength={80} rows={7} defaultValue={editing==="new"?"":editing.description}/></label><label>Kategorie<select name="categoryId" required defaultValue={editing==="new"?"":editing.categoryId}><option value="">Bitte wählen</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Kompetenzen, kommagetrennt<input name="skills" required defaultValue={editing==="new"?"":editing.skills.join(", ")}/></label><label>Zielbranchen<input name="industries" defaultValue={editing==="new"?"":editing.targetIndustries.join(", ")}/></label><label>Regionen<input name="regions" required defaultValue={editing==="new"?"Deutschland":editing.serviceRegions.join(", ")}/></label><fieldset><legend>Arbeitsmodell</legend>{[["online","Online"],["onsite","Vor Ort"],["hybrid","Hybrid"]].map(([v,l])=><label className="checkRow" key={v}><input name="modes" type="checkbox" value={v} defaultChecked={editing==="new"?v==="online":editing.deliveryModes.includes(v)}/><span>{l}</span></label>)}</fieldset><footer><button type="button" className="portalSecondary" onClick={()=>setEditing(null)}>Abbrechen</button><button className="portalPrimary">Entwurf speichern</button></footer></form></section></div>}</>;
}
