import Link from "next/link";
import { CookieSettingsButton } from "./cookie-consent";
import { HomeMotion } from "./home-motion";

export function Logo(){return <Link className="v2Logo" href="/" aria-label="B2B Matching Startseite"><img src="/images/b2b-matching-logo-brand.png" alt="B2B Matching"/></Link>}
export function SiteHeader(){return <><HomeMotion/><header className="v2Header"><Logo/><nav aria-label="Hauptnavigation"><Link href="/unternehmen">Für Unternehmen</Link><Link href="/dienstleister">Für Dienstleister</Link><Link href="/netzwerke">Für Netzwerke</Link><Link href="/so-funktionierts">So funktioniert&apos;s</Link><Link href="/sicherheit">Sicherheit</Link></nav><div className="desktopActions"><Link className="v2Login" href="/anmelden">Anmelden</Link><Link className="v2Button small" href="/registrieren">Registrieren</Link></div><details className="mobileMenu"><summary aria-label="Menü öffnen"><span/><span/><span/></summary><div><Link href="/unternehmen">Für Unternehmen</Link><Link href="/dienstleister">Für Dienstleister</Link><Link href="/netzwerke">Für Netzwerke</Link><Link href="/so-funktionierts">So funktioniert&apos;s</Link><Link href="/sicherheit">Sicherheit &amp; Qualität</Link><hr/><Link href="/anmelden">Anmelden</Link><Link className="v2Button" href="/registrieren">Registrieren</Link></div></details></header></>}
export function SiteFooter(){return <footer className="v2Footer"><div className="v2FooterTop"><div><Logo/><p>Bedarf trifft Kompetenz. Das geschützte Netzwerk für bessere B2B-Kooperationen in Deutschland.</p></div><div><b>Für Unternehmen</b><Link href="/unternehmen">Vorteile</Link><Link href="/so-funktionierts">Bedarf veröffentlichen</Link><Link href="/sicherheit">Vertraulichkeit</Link></div><div><b>Für Dienstleister</b><Link href="/dienstleister">Chancen entdecken</Link><Link href="/dienstleister#profil">Leistungsprofil</Link><Link href="/registrieren">Registrieren</Link></div><div><b>Für Netzwerke</b><Link href="/netzwerke">Netzwerkportal</Link><Link href="/netzwerke#funktionen">Funktionen</Link><Link href="/netzwerke#preise">Preise und Testzugang</Link></div><div><b>B2B Matching</b><Link href="/so-funktionierts">So funktioniert&apos;s</Link><Link href="/sicherheit">Qualität &amp; Sicherheit</Link><Link href="/barrierefreiheit">Barrierefreiheit</Link></div><div><b>Rechtliches</b><Link href="/impressum">Impressum</Link><Link href="/agb">AGB</Link><Link href="/datenschutz/unternehmen">Datenschutz Unternehmen</Link><Link href="/datenschutz/dienstleister">Datenschutz Dienstleister</Link><Link href="/cookies">Cookies</Link><CookieSettingsButton/></div></div><div className="v2FooterBottom"><span>© 2026 B2B Matching</span><span>b2bmatching.de · Entwickelt für starke Verbindungen.</span></div></footer>}
const roleFacts={
  company:[["Volle Kontrolle","Sie entscheiden, wer Ihren Bedarf sehen darf"],["Vertraulich starten","Unternehmensdaten bleiben zunächst geschützt"],["Passender auswählen","Nachvollziehbare Empfehlungen statt Trefferlisten"]],
  provider:[["Relevante Chancen","Konkrete Bedarfe statt kalter Kontakte"],["Kompetenz im Fokus","Leistung, Erfahrung und Passung überzeugen"],["Qualifiziert sprechen","Strukturiert vom Match zum Erstgespräch"]],
} as const;

export function PageHero({eyebrow,title,lead,action,secondary}:{eyebrow:string;title:string;lead:string;action:string;secondary?:string}){
  const role=eyebrow.includes("DIENSTLEISTER")?"provider":eyebrow.includes("UNTERNEHMEN")?"company":null;
  return <><section className="subHero"><div><span>{eyebrow}</span><h1>{title}</h1><p>{lead}</p><div><Link className="v2Button" href="/registrieren">{action} →</Link>{secondary&&<Link className="v2Button outline" href="/so-funktionierts">{secondary}</Link>}</div></div></section>{role&&<><div className={`roleHeroAccent roleHeroAccent-${role}`} aria-hidden="true"/><section className={`roleImpactStrip roleImpactStrip-${role}`} aria-label="Die wichtigsten Vorteile">{roleFacts[role].map(([heading,text])=><p key={heading}><b>{heading}</b><span>{text}</span></p>)}</section></>}</>
}
export function CTA({title,text,role}:{title:string;text:string;role:string}){const roleClass=role==="Dienstleister"?"provider":"company";return <section className={`v2Cta v2Cta-${roleClass}`}><span>JETZT TEIL DES NETZWERKS WERDEN</span><h2>{title}</h2><p>{text}</p><Link className="v2Button light" href="/registrieren">Als {role} registrieren →</Link></section>}
