"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {SiteFooter,SiteHeader} from "../components/site-chrome";
import {NetworkAuthFrame,useNetworkBrand} from "../components/network-auth-brand";
import {portalRequest,routeForRole,savePortalSession} from "../lib/portal-api";
type LoginResult={token:string;user:{accountRole:string}};
type Organization={role:"buyer"|"provider"|"both"|"network"};
type NetworkAccess={membership:{role:string};network:{slug:string;settings?:{setupCompletedAt?:string|null}}};
export default function Anmelden(){
 const router=useRouter(),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[networkSlug,setNetworkSlug]=useState("");const brand=useNetworkBrand(networkSlug);
 useEffect(()=>{setNetworkSlug(new URLSearchParams(window.location.search).get("network")||"")},[]);
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");setLoading(true);const form=new FormData(event.currentTarget);try{const result=await portalRequest<LoginResult>("/auth/login",{body:{email:form.get("email"),password:form.get("password")}});savePortalSession(result.token,form.get("remember")==="on");if(result.user.accountRole==="platform_admin"||result.user.accountRole==="reviewer"){router.push("/portal/admin");return}await portalRequest("/networks/invitations/claim",{token:result.token,body:{}});const networks=await portalRequest<NetworkAccess[]>("/networks/mine",{token:result.token}),initiated=networks.find(item=>item.membership.role==="network_admin"&&(networkSlug?item.network.slug===networkSlug:true));if(initiated){router.push((initiated.network.settings?.setupCompletedAt?`/portal/netzwerk/${initiated.network.slug}`:`/portal/netzwerk/${initiated.network.slug}/einstellungen?setup=1`) as never);return}const organizations=await portalRequest<Organization[]>("/organizations/mine",{token:result.token});if(!organizations.length){router.push("/registrieren?onboarding=1");return}const requested=networkSlug?networks.find(item=>item.network.slug===networkSlug):networks[0];if(requested){router.push(`/portal/netzwerk/${requested.network.slug}` as never);return}router.push(routeForRole(organizations[0]?.role as "buyer"|"provider"|"both"))}catch(error){setMessage(error instanceof Error?error.message:"Die Anmeldung ist fehlgeschlagen.")}finally{setLoading(false)}}
 const card=<section className="authCard authCardV2"><p className="sectionKicker">SICHERER ZUGANG</p><h2>{brand?`Bei ${brand.name} anmelden`:"Bei B2B Matching anmelden"}</h2><p className="lead">Geben Sie Ihre persönlichen Zugangsdaten ein.</p><form className="formGrid" onSubmit={login}><label className="full">Geschäftliche E-Mail-Adresse<input type="email" name="email" required autoComplete="email" placeholder="name@unternehmen.de"/></label><label className="full">Passwort<input type="password" name="password" required autoComplete="current-password" placeholder="••••••••••••"/></label><div className="loginOptions"><label><input type="checkbox" name="remember"/> Angemeldet bleiben</label><Link href="/passwort-vergessen">Passwort vergessen?</Link></div><button className="primary full" disabled={loading}>{loading?"Anmeldung wird geprüft …":"Sicher anmelden"}</button></form>{message&&<p className="error" role="alert">{message}</p>}{!brand&&<p className="authHint">Noch nicht dabei? <Link href="/registrieren">Geschäftlich registrieren</Link></p>}<p className="authSecurity">Geschützter Zugang · Verschlüsselte Übertragung</p></section>;
 if(networkSlug&&!brand)return <main className="networkAccessState"><section><span>GESCHÜTZTER ZUGANG</span><h1>Netzwerkportal wird geladen.</h1></section></main>;
 if(brand)return <NetworkAuthFrame brand={brand} kind="login">{card}</NetworkAuthFrame>;
 return <main className="v2"><SiteHeader/><section className="authPage loginPage"><aside className="authStory"><span>WILLKOMMEN ZURÜCK</span><h1>Ihre nächsten Geschäftschancen warten.</h1><p>Öffnen Sie Ihren persönlichen Arbeitsbereich und setzen Sie dort fort, wo Sie aufgehört haben.</p><div className="loginPreview"><div><b>Matches prüfen</b><span>Passung verstehen und gezielt entscheiden</span></div><div><b>Gespräche fortsetzen</b><span>Nachrichten, Termine und nächste Schritte</span></div><div><b>Status im Blick behalten</b><span>Alle Aktivitäten zentral dokumentiert</span></div></div></aside>{card}</section><SiteFooter/></main>
}
