import type {Metadata} from "next";import {LegalPage,LegalSection} from "../components/legal-page";
export const metadata:Metadata={title:"Barrierefreiheit",description:"Erklärung zur digitalen Barrierefreiheit von B2B Matching."};
export default function Page(){return <LegalPage eyebrow="ZUGÄNGLICHKEIT" title="Barrierefreiheit" intro="B2B Matching soll unabhängig von Gerät, Eingabemethode oder individuellen Fähigkeiten gut nutzbar sein.">
<LegalSection title="Unser Anspruch"><p>Das Portal richtet sich ausschließlich an Unternehmen. Unabhängig von der rechtlichen Einordnung orientieren wir Entwicklung und Redaktion freiwillig an WCAG 2.2 auf Konformitätsstufe AA und den einschlägigen Anforderungen der EN 301 549.</p></LegalSection>
<LegalSection title="Bereits berücksichtigt"><ul><li>semantische Überschriften, Regionen und verständliche Linktexte</li><li>Tastaturbedienung, sichtbarer Fokus und Sprunglink</li><li>responsive Darstellung, ausreichende Zielgrößen und Vergrößerbarkeit</li><li>Alternativtexte für bedeutungstragende Bilder</li><li>reduzierte Animation nach Betriebssystemeinstellung</li><li>beschriftete Formulare und verständliche Statushinweise</li><li>lesbare Schriftgrößen und kontrastreiche Farben</li></ul></LegalSection>
<LegalSection title="Noch in Prüfung"><p>Das Portal befindet sich im Aufbau. Neue Funktionen, Chats, Terminabläufe, Dokumente und externe Komponenten werden vor Freigabe weiter geprüft. Eine formelle externe Konformitätsprüfung ist noch nicht abgeschlossen; einzelne Inhalte können vorübergehend noch Barrieren enthalten.</p></LegalSection>
<LegalSection title="Barriere melden"><p>Nennen Sie bitte Seite, Gerät oder Hilfsmittel und eine kurze Beschreibung. E-Mail: <a href="mailto:service@b2b-matching.de?subject=Barriere%20auf%20B2B%20Matching">service@b2b-matching.de</a>, Telefon: <a href="tel:+4921433014060">0214 / 330 140 60</a>. Wir prüfen Hinweise und melden uns möglichst innerhalb von zehn Werktagen.</p></LegalSection>
<LegalSection title="Erstellung"><p>Diese Erklärung wurde am 23. Juli 2026 aufgrund einer internen Selbstbewertung aktualisiert und wird bei wesentlichen Änderungen sowie nach weiteren Prüfungen fortgeschrieben.</p></LegalSection>
</LegalPage>}
