import { BadRequestException, ForbiddenException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { AuthService } from "../auth/auth.service";
import { PortalStore } from "../core/portal.store";
import type { MatchRecord, NeedRecord, ServicePageRecord } from "../core/domain";

@Injectable()
export class MatchingService{
  constructor(@Inject(PortalStore) private readonly store:PortalStore,@Inject(AuthService) private readonly auth:AuthService){}
  recalculate(needId:string){const need=this.need(needId);if(need.status!=="active")return[];const networkOrganizations=need.networkId?new Set(this.store.networkMemberships.filter(m=>m.networkId===need.networkId&&m.status==="active").map(m=>m.organizationId)):null;const pages=[...this.store.servicePages.values()].filter(p=>p.matchingEligible&&p.reviewStatus==="approved"&&p.organizationId!==need.organizationId&&p.categoryId===need.categoryId&&(!networkOrganizations||networkOrganizations.has(p.organizationId)));return pages.map(page=>this.upsert(need,page)).sort((a,b)=>b.score-a.score);}
  buyerMatches(authHeader:string|undefined,needId:string){const user=this.auth.authenticate(authHeader);const need=this.need(needId);this.requireMember(user.id,need.organizationId);return [...this.store.matches.values()].filter(m=>m.needId===needId);}
  buyerMatchDetails(authHeader:string|undefined,needId:string){
    const matches=this.buyerMatches(authHeader,needId);
    return matches.map(match=>{
      const servicePage=this.store.servicePages.get(match.servicePageId);
      const provider=this.store.organizations.get(match.providerOrganizationId);
      if(!servicePage||!provider)throw new NotFoundException("Dienstleisterprofil des Matches nicht gefunden.");
      return{match,servicePage,provider:{id:provider.id,displayName:provider.displayName,legalName:provider.legalName,websiteUrl:provider.websiteUrl,profileData:provider.profileData||{}}};
    });
  }
  release(authHeader:string|undefined,matchId:string){const user=this.auth.authenticate(authHeader);const match=this.match(matchId);this.requireMember(user.id,match.buyerOrganizationId);if(!["buyer_review","deferred"].includes(match.status))throw new BadRequestException("Der Match kann nicht freigegeben werden.");match.status="released_anonymously";match.buyerDecisionAt=new Date().toISOString();return match;}
  rejectBuyer(authHeader:string|undefined,matchId:string){const user=this.auth.authenticate(authHeader);const match=this.match(matchId);this.requireMember(user.id,match.buyerOrganizationId);match.status="rejected_by_buyer";match.buyerDecisionAt=new Date().toISOString();return match;}
  providerInbox(authHeader:string|undefined){const user=this.auth.authenticate(authHeader);const orgs=new Set(this.store.memberships.filter(m=>m.userId===user.id).map(m=>m.organizationId));return [...this.store.matches.values()].filter(m=>orgs.has(m.providerOrganizationId)&&["released_anonymously","provider_interested","mutual_match"].includes(m.status)).map(m=>({match:m,need:this.anonymousNeed(this.need(m.needId))}));}
  providerDecision(authHeader:string|undefined,matchId:string,interested:boolean){const user=this.auth.authenticate(authHeader);const match=this.match(matchId);this.requireMember(user.id,match.providerOrganizationId);if(match.status!=="released_anonymously")throw new BadRequestException("Der Match kann nicht beantwortet werden.");match.status=interested?"provider_interested":"rejected_by_provider";match.providerDecisionAt=new Date().toISOString();return match;}
  releaseIdentity(authHeader:string|undefined,matchId:string){const user=this.auth.authenticate(authHeader);const match=this.match(matchId);this.requireMember(user.id,match.buyerOrganizationId);if(match.status!=="provider_interested")throw new BadRequestException("Die Identität kann erst nach Interesse des Dienstleisters freigegeben werden.");match.status="mutual_match";match.identityReleasedAt=new Date().toISOString();return match;}
  private upsert(need:NeedRecord,page:ServicePageRecord){const existing=[...this.store.matches.values()].find(m=>m.needId===need.id&&m.servicePageId===page.id);if(existing&&["rejected_by_buyer","rejected_by_provider","mutual_match"].includes(existing.status))return existing;const skillHits=need.requiredSkills.length?need.requiredSkills.filter(s=>page.skills.some(p=>p.toLowerCase()===s.toLowerCase())).length/need.requiredSkills.length:1;const industry=need.preferredIndustries.length?need.preferredIndustries.some(i=>page.targetIndustries.map(x=>x.toLowerCase()).includes(i.toLowerCase()))?1:.45:1;const delivery=need.deliveryModes.some(m=>page.deliveryModes.includes(m))?1:0;const region=!need.region||page.serviceRegions.some(r=>r.toLowerCase().includes(need.region!.toLowerCase())||r.toLowerCase()==="deutschland")?1:.35;const score=Math.round((.40*skillHits+.20*industry+.20*delivery+.20*region)*100);const values={skills:Math.round(skillHits*100),industry:Math.round(industry*100),delivery:delivery*100,region:Math.round(region*100)};const explanation=[`${values.skills} % der Pflichtfähigkeiten stimmen überein.`,delivery?"Das gewünschte Liefermodell wird angeboten.":"Das gewünschte Liefermodell fehlt.",region===1?"Die regionale Anforderung wird erfüllt.":"Die regionale Abdeckung ist nur teilweise passend."];if(existing){existing.score=score;existing.components=values;existing.explanation=explanation;return existing;}const match:MatchRecord={id:randomUUID(),needId:need.id,servicePageId:page.id,buyerOrganizationId:need.organizationId,providerOrganizationId:page.organizationId,score,components:values,explanation,status:"buyer_review",buyerDecisionAt:null,providerDecisionAt:null,identityReleasedAt:null,createdAt:new Date().toISOString()};this.store.matches.set(match.id,match);return match;}
  private anonymousNeed(need:NeedRecord){return {id:need.id,networkId:need.networkId,title:need.title,description:need.description,categoryId:need.categoryId,requiredSkills:need.requiredSkills,preferredIndustries:need.preferredIndustries,region:need.region,deliveryModes:need.deliveryModes};}
  private need(id:string){const value=this.store.needs.get(id);if(!value)throw new NotFoundException("Bedarf nicht gefunden.");return value;}
  private match(id:string){const value=this.store.matches.get(id);if(!value)throw new NotFoundException("Match nicht gefunden.");return value;}
  private requireMember(userId:string,organizationId:string){if(!this.store.memberships.some(m=>m.userId===userId&&m.organizationId===organizationId))throw new ForbiddenException();}
}
