import{describe,expect,it}from"vitest";import{PortalStore}from"./core/portal.store";import{AuthService}from"./auth/auth.service";import{OrganizationsService}from"./organizations/organizations.service";import{ServicesService}from"./services/services.service";import{MatchingService}from"./matching/matching.service";import{NeedsService}from"./matching/needs.service";
import{CollaborationService}from"./collaboration/collaboration.service";
import{EmailService}from"./auth/email.service";

async function account(auth:AuthService,email:string){const r=await auth.register({email,password:"Sehr-Sicher-2026!",firstName:"Test",lastName:"Person"});auth.verifyEmail(r.verificationToken);return `Bearer ${(await auth.login({email,password:"Sehr-Sicher-2026!"})).token}`;}
describe("controlled double opt-in matching",()=>{it("reveals the anonymous need only after buyer release and identity only after mutual interest",async()=>{
 const store=new PortalStore(),auth=new AuthService(store),organizations=new OrganizationsService(store,auth,new EmailService()),services=new ServicesService(store,auth),matching=new MatchingService(store,auth),needs=new NeedsService(store,auth,matching),collaboration=new CollaborationService(store,auth);
 const buyerToken=await account(auth,"buyer@example.de"),providerToken=await account(auth,"provider@example.de");
 const buyer=organizations.create(buyerToken,{legalName:"Käufer GmbH",displayName:"Käufer",role:"buyer",websiteUrl:"https://buyer.example"});buyer.reviewStatus="approved";
 const provider=organizations.create(providerToken,{legalName:"Security GmbH",displayName:"Security",role:"provider",websiteUrl:"https://provider.example"});provider.reviewStatus="approved";
 const page=services.create(providerToken,provider.id,{title:"Web Penetrationstest",summary:"Sicherheitsprüfung für geschäftliche Webanwendungen und Portale.",description:"Wir prüfen geschäftskritische Webanwendungen nach anerkannten Standards, dokumentieren alle Befunde nachvollziehbar und liefern priorisierte Maßnahmen zur Behebung.",categoryId:"it-security",skills:["OWASP","Web Security"],targetIndustries:["Industrie"],serviceRegions:["Deutschland"],deliveryModes:["online"]});page.reviewStatus="approved";page.matchingEligible=true;
 const need=needs.create(buyerToken,buyer.id,{title:"Sicherheitsprüfung Kundenportal",description:"Gesucht wird ein unabhängiger Dienstleister für einen Penetrationstest unseres Kundenportals einschließlich Abschlussbericht.",categoryId:"it-security",requiredSkills:["OWASP"],preferredIndustries:["Industrie"],region:"Deutschland",deliveryModes:["online"]});
 needs.submit(buyerToken,need.id);needs.decide(need.id,"approved","Bedarf ist vollständig und plausibel.");const matches=matching.buyerMatches(buyerToken,need.id);expect(matches[0].score).toBe(100);expect(matching.providerInbox(providerToken)).toHaveLength(0);
 const match=matches[0];matching.release(buyerToken,match.id);const inbox=matching.providerInbox(providerToken);expect(inbox).toHaveLength(1);expect(inbox[0].need).not.toHaveProperty("organizationId");
 matching.providerDecision(providerToken,match.id,true);expect(match.status).toBe("provider_interested");matching.releaseIdentity(buyerToken,match.id);expect(match.status).toBe("mutual_match");expect(match.identityReleasedAt).not.toBeNull();
 collaboration.message(buyerToken,match.id,"Guten Tag, möchten Sie die Anforderungen in einem Gespräch vertiefen?");expect(collaboration.conversation(providerToken,match.id).messages).toHaveLength(1);
 const meeting=collaboration.meeting(providerToken,match.id,{title:"Kennenlerngespräch",startsAt:"2026-08-03T08:00:00Z",durationMinutes:30,mode:"online"});collaboration.meetingStatus(buyerToken,meeting.id,"confirmed");expect(meeting.status).toBe("confirmed");expect(collaboration.timeline(buyerToken,match.id).length).toBeGreaterThan(2);expect(collaboration.notifications(providerToken).length).toBeGreaterThan(0);
});});
