import {describe,expect,it} from "vitest";
import {AuthService} from "../auth/auth.service";
import {EmailService} from "../auth/email.service";
import {hashPassword} from "../auth/password";
import {PortalStore} from "../core/portal.store";
import {OrganizationsService} from "../organizations/organizations.service";
import {NetworksService} from "./networks.service";

describe("network tenancy",()=>{
 it("allows only the platform owner to activate trials and appoint network administrators",async()=>{
  const store=new PortalStore();const auth=new AuthService(store);const organizations=new OrganizationsService(store,auth,new EmailService());const networks=new NetworksService(store,auth,new EmailService());
  const adminId="platform-admin";store.users.set(adminId,{id:adminId,email:"admin@b2bmatching.de",passwordHash:await hashPassword("Sehr-Sicher-2026!"),firstName:"Portal",lastName:"Admin",accountRole:"platform_admin",emailVerifiedAt:new Date().toISOString(),createdAt:new Date().toISOString()});store.userByEmail.set("admin@b2bmatching.de",adminId);
  const adminLogin=await auth.login({email:"admin@b2bmatching.de",password:"Sehr-Sicher-2026!"});const adminBearer=`Bearer ${adminLogin.token}`;
  expect(()=>networks.publicBySlug(undefined,"test-netzwerk")).toThrow();
  const created=networks.create(adminBearer,{name:"Test Netzwerk",slug:"test-netzwerk",websiteUrl:"https://netzwerk.example",enabledModules:["members","events"]});
  const trial=networks.setAccess(adminBearer,created.id,{status:"trial",trialDays:10,selfRegistration:false});
  expect(trial.status).toBe("trial");expect(trial.trialEndsAt).not.toBeNull();

  const registration=await auth.register({email:"mitglied@example.de",password:"Sehr-Sicher-2026!",firstName:"Mara",lastName:"Klein"});auth.verifyEmail(registration.verificationToken);
  const login=await auth.login({email:"mitglied@example.de",password:"Sehr-Sicher-2026!"});const bearer=`Bearer ${login.token}`;
  const organization=organizations.create(bearer,{legalName:"Mitglied GmbH",displayName:"Mitglied",role:"both",websiteUrl:"https://example.de"});
  const membership=networks.addMember(adminBearer,created.id,{organizationId:organization.id,userId:registration.user.id,role:"organization_admin"});
  expect(membership).toMatchObject({networkId:created.id,organizationId:organization.id,status:"active",role:"organization_admin"});
  expect(networks.mine(bearer)[0].network.slug).toBe("test-netzwerk");
  expect(networks.publicBySlug(bearer,"test-netzwerk").slug).toBe("test-netzwerk");
  const outsiderRegistration=await auth.register({email:"extern@example.de",password:"Sehr-Sicher-2026!",firstName:"Eva",lastName:"Extern"});auth.verifyEmail(outsiderRegistration.verificationToken);
  const outsiderLogin=await auth.login({email:"extern@example.de",password:"Sehr-Sicher-2026!"});
  expect(()=>networks.publicBySlug(`Bearer ${outsiderLogin.token}`,"test-netzwerk")).toThrow();
  expect(()=>networks.apply(`Bearer ${outsiderLogin.token}`,"test-netzwerk",{organizationId:organization.id})).toThrow(/Einladungslink/);
  expect(()=>networks.addMember(bearer,created.id,{organizationId:organization.id,userId:registration.user.id,role:"network_admin"})).toThrow();
  const networkAdmin=await networks.appointAdministrator(adminBearer,created.id,{email:"mitglied@example.de"});
  expect(networkAdmin.role).toBe("network_admin");
  expect(networks.adminList(adminBearer)[0].administrator?.user?.email).toBe("mitglied@example.de");
  networks.updateSettings(bearer,created.id,{enabledModules:["profiles","events"],name:"Test Netzwerk"});
  networks.setAccess(adminBearer,created.id,{status:"active"});
  const order=networks.order(bearer,created.id,{invoiceCompany:"Mitglied GmbH",invoiceContact:"Mara Klein",invoiceEmail:"rechnung@example.de",invoiceStreet:"Musterstraße 1",invoicePostalCode:"12345",invoiceCity:"Musterstadt",invoiceCountry:"Deutschland",billingCycle:"annual",participantCount:1,pricingMode:"individual",selectedModules:["profiles","events"],authorityConfirmed:true,termsAccepted:true,paymentObligationAccepted:true});
  expect(order.monthlyNetCents).toBe(2600);expect(order.selectedModules).toEqual(["profiles","events"]);expect(order.status).toBe("accepted");expect(order.paymentStatus).toBe("open");
  expect(networks.publicBySlug(bearer,"test-netzwerk").enabledModules).toEqual(expect.arrayContaining(["members","branding","profiles","events"]));
  const partnerProfile=networks.updateOwnProfile(bearer,created.id,{companyName:"Mitglied GmbH",tagline:"Gemeinsam besser zusammenarbeiten",description:"Wir unterstützen Netzwerkpartner persönlich und zuverlässig bei anspruchsvollen Projekten.",services:"Beratung, Projektmanagement und Umsetzung",industries:"Mittelstand, Sport",street:"Musterstraße 1",postalCode:"12345",city:"Musterstadt",country:"Deutschland",websiteUrl:"https://example.de",contactName:"Mara Klein",contactPosition:"Geschäftsführung",contactEmail:"mitglied@example.de",contactPhone:"+49 123 456789",publish:true});
  expect(partnerProfile.status).toBe("published");
  expect(networks.listMembers(bearer,created.id)[0].organization?.networkProfile?.services).toContain("Beratung");
  expect(()=>networks.revenues(adminBearer,created.id)).toThrow(/nicht angeboten/);
  networks.addMember(adminBearer,created.id,{organizationId:organization.id,userId:outsiderRegistration.user.id,role:"member"});
  expect(networks.publicBySlug(`Bearer ${outsiderLogin.token}`,"test-netzwerk").enabledModules).not.toContain("events");
  const second=networks.create(adminBearer,{name:"Zweites Netzwerk",slug:"zweites-netzwerk",websiteUrl:"https://zweites.example",enabledModules:["members","events"]});
  expect(second).toMatchObject({status:"draft",trialEndsAt:null});
  expect(second.settings.selfRegistration).toBe(false);
  expect(networks.adminList(adminBearer)).toHaveLength(2);
 });
});
