import {PortalPanel,PortalShell,PortalStats,Status} from "../../components/portal-shell";
export default function UnternehmenPortal(){return <PortalShell role="unternehmen" title="Guten Morgen, Herr Weber." intro="Verwalten Sie Ihre Bedarfe, prüfen Sie neue Empfehlungen und behalten Sie jede Aktivität im Blick." action={<button className="portalPrimary">＋ Neuen Bedarf erstellen</button>}>
<PortalStats items={[["4","Aktive Bedarfe","+1 diese Woche"],["12","Neue Matches","Ø 86 % Passung"],["3","Ungelesene Nachrichten","2 Antworten heute"],["128","Bedarfsaufrufe","+18 % im Monat"]]}/>
<div className="portalGrid wideLeft"><div>
<PortalPanel id="bedarfe" eyebrow="BEDARFSMANAGEMENT" title="Meine aktuellen Bedarfe" action={<button className="portalLink">Alle Bedarfe ansehen →</button>}><div className="needList">
{[["Externe IT-Sicherheitsprüfung","IT & Digitalisierung","8 Matches","148 Aufrufe","Aktiv"],["Neue Markenpositionierung","Marketing & Kommunikation","5 Matches","91 Aufrufe","Aktiv"],["Interim HR-Leitung","Personal & Organisation","3 Matches","37 Aufrufe","Entwurf"]].map((x,i)=><article key={x[0]}><div className="needIcon">{["IT","MK","HR"][i]}</div><div><h3>{x[0]}</h3><p>{x[1]} · Aktualisiert vor {i+1} Tagen</p><span>{x[2]}</span><span>{x[3]}</span></div><Status tone={i===2?"gray":"teal"}>{x[4]}</Status><button aria-label={`${x[0]} bearbeiten`}>•••</button></article>)}</div></PortalPanel>
<PortalPanel id="matches" eyebrow="NEUE EMPFEHLUNGEN" title="Passende Dienstleister" action={<button className="portalLink">Matching-Zentrale →</button>}><div className="matchRows">{[["92","Nordlicht Digital GmbH","IT-Sicherheit · Hamburg","Erfahrung, Branche und Leistungsmodell passen sehr gut."],["87","Rheinwerk Solutions","Cybersecurity · Köln","Starke Fachnähe und kurzfristig verfügbar."],["81","SecureCore Consulting","Informationssicherheit · Berlin","Passende Zertifizierungen, Einsatz überwiegend remote."]].map(([score,name,meta,text])=><article key={name}><b>{score}<small>%</small></b><div><h3>{name}</h3><span>{meta}</span><p>{text}</p></div><button className="portalSecondary">Profil prüfen</button><button className="portalReject">Ablehnen</button></article>)}</div></PortalPanel>
<PortalPanel id="historie" eyebrow="AKTIVITÄTSDOKUMENTATION" title="Ihre Historie"><div className="activity">{[["heute, 09:42","Profil von Nordlicht Digital geöffnet"],["gestern, 16:18","Rheinwerk Solutions als Favorit gespeichert"],["gestern, 11:05","Bedarf „IT-Sicherheitsprüfung“ aktualisiert"],["15. Juli, 14:20","Match mit SecureCore zurückgestellt"]].map(([time,text])=><p key={time}><span/><small>{time}</small><strong>{text}</strong></p>)}</div></PortalPanel>
</div><aside>
<PortalPanel title="KI-Bedarfsassistent" className="portalAi"><span className="aiMark">✦</span><h3>Aus einer Idee wird ein klarer Bedarf.</h3><p>Beschreiben Sie Ihr Ziel in wenigen Sätzen. Die KI strukturiert Leistungsumfang, Kriterien, Zeitraum und wichtige Rückfragen.</p><button className="portalPrimary">Bedarf mit KI erstellen</button></PortalPanel>
<PortalPanel id="favoriten" title="Favorisierte Dienstleister"><div className="compactPeople">{[["ND","Nordlicht Digital","IT-Sicherheit"],["RW","Rheinwerk Solutions","Digitalisierung"],["MP","Mittelstand Partner","Strategieberatung"]].map(([a,n,r])=><p key={n}><b>{a}</b><span><strong>{n}</strong><small>{r}</small></span><button aria-label={`${n} entfernen`}>★</button></p>)}</div></PortalPanel>
<PortalPanel id="aufrufe" title="Bedarfsreichweite"><div className="miniChart"><b style={{height:"43%"}}/><b style={{height:"62%"}}/><b style={{height:"48%"}}/><b style={{height:"76%"}}/><b style={{height:"68%"}}/><b style={{height:"92%"}}/><b style={{height:"84%"}}/></div><p className="panelNote">128 qualifizierte Aufrufe in den letzten 30 Tagen</p></PortalPanel>
</aside></div></PortalShell>}
