import Link from "next/link";
import {notFound} from "next/navigation";
import {NetworkShell} from "../../../../components/network-shell";
import {networkBase} from "../../../../lib/network-config";

const content:Record<string,{title:string;intro:string;eyebrow:string;description:string;features:string[]}>={
 veranstaltungen:{title:"Veranstaltungen und Treffen",intro:"Einmalige und wiederkehrende Treffen planen, Anmeldungen verwalten und Anwesenheit dokumentieren.",eyebrow:"VERANSTALTUNGSMODUL",description:"Das Veranstaltungszentrum bündelt Unternehmerfrühstücke, interne Treffen und Sonderveranstaltungen.",features:["Terminserien und individuelle Wiederholungen","Zu- und Absagen mit Warteliste","Teilnehmerzahl und Anmeldeschluss","Online-, Vor-Ort- und Hybridtermine","Erinnerungen und Anwesenheit","Dokumente, Protokolle und Folgetermine"]},
 matching:{title:"Bedarfe und Matching",intro:"Bedarfe und Leistungen innerhalb des Netzwerks intelligent und kontrolliert zusammenführen.",eyebrow:"NETZWERK-MATCHING",description:"Matches entstehen zunächst ausschließlich zwischen aktiven Mitgliedsunternehmen der Unternehmerfreunde NRW.",features:["Ausführliche Bedarfsprofile","Leistungsangebote der Mitglieder","Prozentuale Matchbewertung","Nachvollziehbare Kriterien","Freigabe oder Ablehnung","Optionale spätere Portalöffnung"]},
 kommunikation:{title:"Nachrichten und Zusammenarbeit",intro:"Freigegebene Kontakte, Gespräche, Termine und nächste Schritte geschützt koordinieren.",eyebrow:"KOMMUNIKATION",description:"Mitglieder kommunizieren erst nach entsprechender Freigabe in einem geschützten Netzwerkbereich.",features:["Einzelgespräche","Terminabstimmungen","Dateien und Anhänge","Wiedervorlagen","Gesprächsstatus","Aktivitätshistorie"]},
 themen:{title:"Themen und Gruppen",intro:"Netzwerkthemen, Ankündigungen, Interessengruppen und Abstimmungen organisieren.",eyebrow:"NETZWERKAUSTAUSCH",description:"Wissen und Interessen werden strukturiert gesammelt und für die passenden Mitglieder sichtbar gemacht.",features:["Themenvorschläge","Fach- und Interessengruppen","Ankündigungen","Diskussionsbereiche","Umfragen und Abstimmungen","Agenda-Vorschläge"]},
 aufgaben:{title:"Aufgaben und Zuständigkeiten",intro:"Vereinbarte Maßnahmen, Verantwortlichkeiten und Fälligkeiten nachvollziehbar steuern.",eyebrow:"ORGANISATION",description:"Aus Treffen, Themen und Kooperationen entstehende Aufgaben bleiben zentral sichtbar.",features:["Aufgaben zuweisen","Fälligkeiten","Prioritäten","Statusverfolgung","Verknüpfung mit Terminen","Erledigungshistorie"]},
 dokumente:{title:"Dokumente und Wissen",intro:"Netzwerkunterlagen, Protokolle und Downloads sicher und strukturiert bereitstellen.",eyebrow:"WISSENSBEREICH",description:"Mitglieder finden freigegebene Informationen und Dokumente in einer zentralen Wissenssammlung.",features:["Ordner und Kategorien","Rollenbasierte Sichtbarkeit","Veranstaltungsunterlagen","Protokolle","Versionen","Sichere Downloads"]},
 auswertungen:{title:"Statistiken und Auswertungen",intro:"Mitgliederentwicklung, Aktivitäten, Matching und Veranstaltungen transparent auswerten.",eyebrow:"NETZWERKANALYSE",description:"Das Netzwerk erhält belastbare Kennzahlen über frei definierbare Zeiträume.",features:["Mitgliederentwicklung","Profilvollständigkeit","Bedarfe und Leistungen","Match- und Kontaktquoten","Veranstaltungsteilnahme","CSV- und PDF-Exporte"]},
 einstellungen:{title:"Netzwerkeinstellungen",intro:"Branding, Module, Regeln, Datenschutz und Berechtigungen des Netzwerks konfigurieren.",eyebrow:"MANDANTENVERWALTUNG",description:"Alle wesentlichen Einstellungen gelten ausschließlich für Unternehmerfreunde NRW.",features:["Logo und Netzwerkfarben","Module aktivieren","Aufnahmebedingungen","Rollen und Rechte","Sichtbarkeit und Datenschutz","Benachrichtigungsvorgaben"]}
};

export function generateStaticParams(){return Object.keys(content).map(bereich=>({bereich}))}
export default async function Page({params}:{params:Promise<{bereich:string}>}){const {bereich}=await params;const page=content[bereich];if(!page)notFound();return <NetworkShell title={page.title} intro={page.intro}><section className="networkModuleHero"><span>{page.eyebrow}</span><h2>{page.title}</h2><p>{page.description}</p><button className="networkPrimary">＋ Neu anlegen</button></section><section className="networkFeatureGrid">{page.features.map((feature,index)=><article key={feature}><b>0{index+1}</b><h3>{feature}</h3><p>Dieser Funktionsbereich wird auf der gemeinsamen modularen Netzwerkbasis geführt und ausschließlich entsprechend Ihrer Rolle freigegeben.</p></article>)}</section><section className="networkCard networkModuleEmpty"><span>MODUL BEREIT</span><h2>Noch keine Inhalte vorhanden</h2><p>Die Oberfläche und Navigation sind eingerichtet. Sobald erste Inhalte angelegt werden, erscheinen sie hier mit Suche, Filtern und Statusverwaltung.</p><Link href={networkBase}>Zur Netzwerkübersicht</Link></section></NetworkShell>}
