import{BadRequestException,ForbiddenException,Inject,Injectable,NotFoundException}from"@nestjs/common";import{randomUUID}from"node:crypto";import{AuthService}from"../auth/auth.service";import{PortalStore}from"../core/portal.store";import{requiredText}from"../core/validation";
@Injectable()export class CollaborationService{
 constructor(@Inject(PortalStore)private readonly store:PortalStore,@Inject(AuthService)private readonly auth:AuthService){}
 conversation(authHeader:string|undefined,matchId:string){const user=this.auth.authenticate(authHeader),match=this.allowedMatch(user.id,matchId);let conversation=[...this.store.conversations.values()].find(c=>c.matchId===matchId);if(!conversation){conversation={id:randomUUID(),matchId,createdAt:new Date().toISOString()};this.store.conversations.set(conversation.id,conversation);this.activity(matchId,user.id,"conversation.opened",{});}return{conversation,messages:this.store.messages.filter(m=>m.conversationId===conversation!.id),meetings:[...this.store.meetings.values()].filter(m=>m.matchId===matchId).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))};}
 message(authHeader:string|undefined,matchId:string,body:unknown){const user=this.auth.authenticate(authHeader);this.allowedMatch(user.id,matchId);const{conversation}=this.conversation(authHeader,matchId);const message={id:randomUUID(),conversationId:conversation.id,senderUserId:user.id,body:requiredText(body,"Nachricht",1,5000),createdAt:new Date().toISOString()};this.store.messages.push(message);this.activity(matchId,user.id,"message.sent",{messageId:message.id});this.notifyOther(matchId,user.id,"message.received",{matchId});return message;}
 meeting(authHeader:string|undefined,matchId:string,input:Record<string,unknown>){const user=this.auth.authenticate(authHeader);this.allowedMatch(user.id,matchId);const startsAt=requiredText(input.startsAt,"Startzeit",10,50);if(Number.isNaN(Date.parse(startsAt)))throw new BadRequestException("Ungültige Startzeit.");const duration=Number(input.durationMinutes);if(!Number.isInteger(duration)||duration<15||duration>480)throw new BadRequestException("Die Dauer muss zwischen 15 und 480 Minuten liegen.");const mode=String(input.mode);if(!["online","onsite"].includes(mode))throw new BadRequestException("Ungültige Terminart.");const meeting={id:randomUUID(),matchId,createdByUserId:user.id,title:requiredText(input.title,"Termintitel",3,200),startsAt:new Date(startsAt).toISOString(),durationMinutes:duration,mode:mode as"online"|"onsite",location:typeof input.location==="string"&&input.location.trim()?input.location.trim():null,status:"proposed"as const,createdAt:new Date().toISOString()};this.store.meetings.set(meeting.id,meeting);this.activity(matchId,user.id,"meeting.proposed",{meetingId:meeting.id,startsAt:meeting.startsAt});this.notifyOther(matchId,user.id,"meeting.proposed",{meetingId:meeting.id});return meeting;}
 meetingStatus(authHeader:string|undefined,meetingId:string,status:unknown){const user=this.auth.authenticate(authHeader),meeting=this.store.meetings.get(meetingId);if(!meeting)throw new NotFoundException("Termin nicht gefunden.");this.allowedMatch(user.id,meeting.matchId);if(!["confirmed","cancelled"].includes(String(status)))throw new BadRequestException("Ungültiger Terminstatus.");meeting.status=status as"confirmed"|"cancelled";this.activity(meeting.matchId,user.id,`meeting.${status}`,{meetingId});return meeting;}
 timeline(authHeader:string|undefined,matchId:string){const user=this.auth.authenticate(authHeader),match=this.allowedMatch(user.id,matchId);const side=this.side(user.id,match);return this.store.activities.filter(a=>a.matchId===matchId&&(a.visibility==="shared"||a.visibility===`${side}_internal`));}
 notifications(authHeader:string|undefined){const user=this.auth.authenticate(authHeader);return this.store.notifications.filter(n=>n.userId===user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
 readNotification(authHeader:string|undefined,id:string){const user=this.auth.authenticate(authHeader),notification=this.store.notifications.find(n=>n.id===id&&n.userId===user.id);if(!notification)throw new NotFoundException("Benachrichtigung nicht gefunden.");notification.readAt=notification.readAt||new Date().toISOString();return notification;}
 private allowedMatch(userId:string,matchId:string){const match=this.store.matches.get(matchId);if(!match)throw new NotFoundException("Match nicht gefunden.");if(match.status!=="mutual_match")throw new ForbiddenException("Kommunikation ist erst nach beidseitigem Match möglich.");if(!this.store.memberships.some(m=>m.userId===userId&&[match.buyerOrganizationId,match.providerOrganizationId].includes(m.organizationId)))throw new ForbiddenException();return match;}
 private side(userId:string,match:{buyerOrganizationId:string;providerOrganizationId:string}){return this.store.memberships.some(m=>m.userId===userId&&m.organizationId===match.buyerOrganizationId)?"buyer":"provider";}
 private activity(matchId:string,actorUserId:string,type:string,data:Record<string,unknown>){this.store.activities.push({id:randomUUID(),matchId,organizationId:null,actorUserId,type,visibility:"shared",data,createdAt:new Date().toISOString()});}
 private notifyOther(matchId:string,actorUserId:string,type:string,data:Record<string,unknown>){const match=this.store.matches.get(matchId)!;const actorOrgs=new Set(this.store.memberships.filter(m=>m.userId===actorUserId).map(m=>m.organizationId));const other=actorOrgs.has(match.buyerOrganizationId)?match.providerOrganizationId:match.buyerOrganizationId;for(const member of this.store.memberships.filter(m=>m.organizationId===other))this.store.notifications.push({id:randomUUID(),userId:member.userId,type,data,readAt:null,createdAt:new Date().toISOString()});}
}
